project:
  type: book
  output-dir: ../../docs
  
book:
  title: "MAIN"
  author: "Amy Rae Fox"
  date: "4/29/2022"
  
  chapters:
    - index.qmd
    - part : analysis/SGC3A/SGC3A.qmd 
      chapters: 
        - analysis/SGC3A/1_sgc3A_harmonize.qmd
        - analysis/SGC3A/2_sgc3A_scoring.qmd
        - analysis/SGC3A/2_sgc3A_exploreResponse.qmd
        
    - references.qmd
    
  sidebar:
    style: docked
    background: light

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    code-summary: "Show the code"
    code-tools: true
    css: styles.css
  pdf:
    documentclass: scrreprt

editor: visual

