project:
  type: book
  execute-dir: project
  output-dir: ../../docs
  
book:
  title: "SGC-X"
  author: "Amy Rae Fox"
  date: "4/29/2022"
  
  chapters:
    - index.qmd
    - part : "General"
      chapters:
        - analysis/utils/scoring.qmd
    - part : analysis/SGC3A/SGC3A.qmd 
      chapters: 
        - analysis/SGC3A/1_sgc3A_introduction.qmd
        - analysis/SGC3A/2_sgc3A_scoring.qmd
        - analysis/SGC3A/3_sgc3A_description.qmd
        - analysis/SGC3A/4_sgc3A_hypotesting.qmd
        - analysis/SGC3A/5_sgc3A_exploration.qmd
    - part : "SGC4A"
      chapters: 
      - analysis/SGC4A/1_sgc4A_introduction.qmd
      - analysis/SGC4A/2_sgc4A_scoring.qmd
    - part : "SGC5"
      chapters: 
      - analysis/SGC5/1_sgc5_introduction.qmd
      - analysis/SGC5/2_sgc5_scoring.qmd
    
      
        
    - references.qmd
    
  sidebar:
    style: docked
    background: light

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    smooth-scroll: true
    citations-hover: true
    footnotes-hover: true
    toc-depth: 5
    code-tools: true
    code-link: true
    code-overflow: wrap
    code-fold: true
    code-summary: "CODE"
    number-depth : 1
    number-offset: 3

  pdf:
    documentclass: scrreprt

editor: visual

execute:
  freeze: auto  # re-render docs only when source changes

