project:
  type: book
  execute-dir: project
  output-dir: ../../docs
  
book:
  title: "SGC-X"
  author: "Amy Rae Fox"
  
  chapters:
    - part : index.qmd
      chapters:
        - analysis/utils/scoring.qmd
        - analysis/SGC3A/x_learning.qmd
    - part : "SGC2"
      chapters: 
        - analysis/SGC2/1_sgc2_introduction.qmd
        - analysis/SGC2/3_sgc2_description.qmd
        - analysis/SGC2/4_sgc2_hypotesting.qmd
        # - analysis/SGC3A/5_sgc3A_exploration.qmd
    - part : "SGC3A"
      chapters: 
        - analysis/SGC3A/1_sgc3A_introduction.qmd
        - analysis/SGC3A/2_sgc3A_scoring.qmd
        - analysis/SGC3A/3_sgc3A_description.qmd
        - analysis/SGC3A/4_sgc3A_hypotesting.qmd
        - analysis/SGC3A/5_sgc3A_exploration.qmd
    - part : "SGC3B"
      chapters: 
      - analysis/SGC3B/1_sgc3B_introduction.qmd
      - analysis/SGC3B/2_sgc3B_scoring.qmd
    - part : "SGC4A"
      chapters: 
      - analysis/SGC4A/1_sgc4A_introduction.qmd
      - analysis/SGC4A/2_sgc4A_scoring.qmd
    - part : "SGC4B"
      chapters: 
      - analysis/SGC4B/1_sgc4B_introduction.qmd
      - analysis/SGC4B/2_sgc4B_scoring.qmd
    - part : "SGC4C"
      chapters: 
      - analysis/SGC4C/1_sgc4C_introduction.qmd
      - analysis/SGC4C/2_sgc4C_scoring.qmd
    - part : "SGC5A"
      chapters: 
      - analysis/SGC5A/1_sgc5A_introduction.qmd
      - analysis/SGC5A/2_sgc5A_scoring.qmd
    - part : "COMBINED"
      chapters: 
      - analysis/combined/combined.qmd

    - references.qmd
    
  sidebar:
    style: docked
    background: light

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    smooth-scroll: true
    citations-hover: true
    footnotes-hover: true
    toc-depth: 5
    code-tools: true
    code-link: true
    code-overflow: wrap
    code-fold: true
    code-summary: "CODE"
    number-depth : 1
    number-offset: 3

  pdf:
    documentclass: scrreprt

execute:
  freeze: auto  # re-render docs only when source changes

