{
  "hash": "9672a9231c3e48d29ed7c04f5c68b037",
  "result": {
    "markdown": "---\nsubtitle: 'Study SGC3A | 3 Description'\n---\n\n\\newpage\n\n# Description {#sec-SGC3A-description}\n\n**TODO**\n\n-   finish description of latency\n-   consider raincloud/boxplots/violins with ggpubr/ggdist\n\n*The purpose of this notebook is describe the distributions of dependent variables for Study SGC3A.*\n\n+------------------------+\n| Pre-Requisite          |\n+========================+\n| 1_sgc3A_harmonize.qmd\\ |\n| 2_sgc3A_scoring.qmd    |\n+------------------------+\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/SETUP_79aabdc79d14156d1614a2e99a2f9afa'}\n\n```{.r .cell-code}\nlibrary(Hmisc) # %nin% operator\nlibrary(mosaic) #simple descriptives [favstats]\nlibrary(multimode) #test for multimodality\nlibrary(fitdistrplus) #fitting distributions\nlibrary(performance) #multimodality\nlibrary(kableExtra) #printing tables \nlibrary(vcd) #mosaicplots\nlibrary(ggpubr) #arrange plots\nlibrary(tidyverse) #ALL THE THINGS\n\n#OUTPUT OPTIONS\nlibrary(dplyr, warn.conflicts = FALSE)\noptions(dplyr.summarise.inform = FALSE)\noptions(ggplot2.summarise.inform = FALSE)\noptions(scipen=1, digits=3)\n```\n:::\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/IMPORT-DATA_e0765391384e465f1ee496913ad32390'}\n\n```{.r .cell-code}\n# HACK WD FOR LOCAL RUNNING?\nimac = \"/Users/amyraefox/Code/SGC-Scaffolding_Graph_Comprehension/SGC-X/ANALYSIS/MAIN\"\n# # mbp = \"/Users/amyfox/Sites/RESEARCH/SGC—Scaffolding Graph Comprehension/SGC-X/ANALYSIS/MAIN\"\nsetwd(imac)\n\n#IMPORT DATA \ndf_items <- read_rds('analysis/SGC3A/data/2-scored-data/sgc3a_scored_items.rds')\ndf_subjects <- read_rds('analysis/SGC3A/data/2-scored-data/sgc3a_scored_participants.rds') \n\n#SEPARATE ITEM DATA BY QUESTION TYPE\ndf_scaffold <- df_items %>% filter(q < 6)\ndf_test <- df_items %>% filter(q > 6) %>% filter (q %nin% c(6,9))\ndf_nondiscrim <- df_items %>% filter (q %in% c(6,9))\n\n#SEPARATE ITEM AND SUBJECTS BY MODALITY\ndf_lab <- df_subjects %>% filter(mode == \"lab-synch\")\ndf_online <- df_subjects %>% filter(mode == \"asynch\")\n```\n:::\n\n## SAMPLE\n\n### Data Collection\n\nData was initially collected (in person, SONA groups in computer lab) in Fall 2017. In Spring 2018, additional data were collected after small modifications were made to the experimental platform to increase the size of multiple-choice input buttons, and to add an additional free-response question following the main task block. In Fall 2021, the study was replicated using asynchronous, online SONA pool, with additional participants collected in Winter 2022.\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/label - INSPECT-DATA-COLLECTION_2b0d62193fd2f6dc88885382d0bf1bfc'}\n\n```{.r .cell-code}\ntitle = \"Participants by Condition and Data Collection Period\"\ncols = c(\"Control Condition\",\"Impasse Condition\",\"Total for Period\")\ncont <- table(df_subjects$pretty_mode, df_subjects$condition)\ncont %>% addmargins() %>% kbl(caption = title, col.names = cols) %>%  kable_classic()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\n\\caption{\\label{tab:label : INSPECT-DATA-COLLECTION}Participants by Condition and Data Collection Period}\n\\centering\n\\begin{tabular}[t]{l|r|r|r}\n\\hline\n  & Control Condition & Impasse Condition & Total for Period\\\\\n\\hline\nlaboratory & 62 & 64 & 126\\\\\n\\hline\nonline-replication & 96 & 108 & 204\\\\\n\\hline\nSum & 158 & 172 & 330\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n:::\n\n### Participants\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/DESC-PARTICIPANTS_eebd1d8b3a83a0d6b00c21ec63765a09'}\n\n```{.r .cell-code}\n#Describe participants\nsubject.stats <- rbind(\n  \"lab\"= df_lab %>% dplyr::select(age) %>% unlist() %>% favstats(),\n  \"online\" = df_online %>% filter(mode == \"asynch\") %>% dplyr::select(age) %>% unlist() %>% favstats(),\n  \"combined\" = df_subjects %>% dplyr::select(age) %>% unlist() %>% favstats()\n) \nsubject.stats$percent.female <- c(\n  (df_lab %>%  filter(gender==\"Female\") %>% count())$n/count(df_lab) %>% unlist(),\n  (df_online %>% filter(gender==\"Female\") %>% count())$n/count(df_online) %>% unlist(),\n  (df_subjects %>% filter(gender==\"Female\") %>% count())$n/count(df_subjects) %>% unlist()\n)\n\ntitle = \"Descriptive Statistics of Participant Age and Gender\"\nsubject.stats %>% kbl (caption = title) %>% kable_classic()%>% \n  footnote(general = \"Age in Years\", \n           general_title = \"Note: \",footnote_as_chunk = T) \n```\n\n::: {.cell-output-display}\n\\begin{table}\n\n\\caption{\\label{tab:DESC-PARTICIPANTS}Descriptive Statistics of Participant Age and Gender}\n\\centering\n\\begin{tabular}[t]{l|r|r|r|r|r|r|r|r|r|r}\n\\hline\n  & min & Q1 & median & Q3 & max & mean & sd & n & missing & percent.female\\\\\n\\hline\nlab & 18 & 19 & 20 & 21 & 33 & 20.4 & 2.12 & 126 & 0 & 0.619\\\\\n\\hline\nonline & 18 & 20 & 20 & 21 & 31 & 20.6 & 2.00 & 204 & 0 & 0.672\\\\\n\\hline\ncombined & 18 & 19 & 20 & 21 & 33 & 20.5 & 2.05 & 330 & 0 & 0.652\\\\\n\\hline\n\\multicolumn{11}{l}{\\rule{0pt}{1em}\\textit{Note: } Age in Years}\\\\\n\\end{tabular}\n\\end{table}\n:::\n:::\n\nFor **in-person** collection, 126 participants (61.905 % female ) undergraduate STEM majors at a public American University participated *in person* in exchange for course credit (age: 18 - 33 years). Participants were randomly assigned to one of two experimental groups.\n\nFor **online replication** 204 participants (67.157 % female ) undergraduate STEM majors at a public American University participated *online, asynchronously* in exchange for course credit (age: 18 - 31 years). Participants were randomly assigned to one of two experimental groups.\n\nCombined **overall** 330 participants (65.152` % female ) undergraduate STEM majors at a public American University participated in exchange for course credit (age: 18 - 33 years). \n\n## RESPONSE ACCURACY\n\n### Total Scores\n\nTotal scores indicate the response accuracy by a particular participant across all discriminant items (n=13) in the graph comprehension task. (Although there were 15 questions in the graph comprehension task, questions 6 and 9 were non-discriminant (the correct response was the same for both triangular and orthogonal interpretations). We do not include these questions in our hypothesis testing analysis of performance, but evaluate them separately in our exploratory analysis.)\n\n#### Total Absolute Score\n\nRecall from [Section -@sec-absolute-scoring] that the absolute score (following the dichotomous scoring approach) `s_NABS` indicates if the subject's response for a particular item was *perfectly* correct: whether they selected all correct answer options and no others (excluding certain allowed exceptions, such as also selecting the data point referenced in the question). The absolute score for an individual item is either 0 or 1. When summarized across the entire set of discriminant items, the cumulative absolute score for an individual subject ranges from \\[0,13\\].\n\n##### Test Phase \n\nFirst we examine performance on the test phase (final 8 questions, appears after scaffolding phase). This tells us how the participants perform _after_ exposure to the 5 scaffolding questions (in the impasse condition). \n\n::: {.cell hash='3_sgc3A_description_cache/pdf/DESC-SUBJ-ABS-TEST_607781007519e8618198510bb330f134'}\n\n```{.r .cell-code}\ntitle = \"Descriptive Statistics of TEST PHASE Response Accuracy (Total Absolute Score)\"\nabs.stats <- rbind(\n  \"lab\"= df_lab %>% dplyr::select(item_test_NABS) %>% unlist() %>% favstats(),\n  \"online\" = df_online %>% dplyr::select(item_test_NABS) %>% unlist() %>% favstats(),\n  \"combined\" = df_subjects %>% dplyr::select(item_test_NABS) %>% unlist() %>% favstats()\n) \nabs.stats %>% kbl (caption = title) %>% kable_classic() %>% \n  footnote(general = \"# questions correct [0,8]\", \n           general_title = \"Note: \",footnote_as_chunk = T) \n```\n\n::: {.cell-output-display}\n\\begin{table}\n\n\\caption{\\label{tab:DESC-SUBJ-ABS-TEST}Descriptive Statistics of TEST PHASE Response Accuracy (Total Absolute Score)}\n\\centering\n\\begin{tabular}[t]{l|r|r|r|r|r|r|r|r|r}\n\\hline\n  & min & Q1 & median & Q3 & max & mean & sd & n & missing\\\\\n\\hline\nlab & 0 & 0 & 0 & 6 & 8 & 2.53 & 3.32 & 126 & 0\\\\\n\\hline\nonline & 0 & 0 & 0 & 6 & 8 & 2.16 & 3.19 & 204 & 0\\\\\n\\hline\ncombined & 0 & 0 & 0 & 6 & 8 & 2.30 & 3.24 & 330 & 0\\\\\n\\hline\n\\multicolumn{10}{l}{\\rule{0pt}{1em}\\textit{Note: } \\# questions correct [0,8]}\\\\\n\\end{tabular}\n\\end{table}\n:::\n:::\n\nFor *in person* collection, total absolute scores in the TEST phase (n = 126) range from 0 to 8 with a mean score of (M = 2.53, SD = 3.32).\n\nFor *online replication*, (online) total absolute scores in the TEST phase (n = 204) range from 0 to 8 with a slightly lower mean score of (M = 2.16, SD = 3.19).\n\nWhen combined *overall*, total absolute accuracy scores in the TEST phase (n = 330) range from 0 to 8 with a slightly lower mean score of (M = 2.3, SD = 3.24).\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/VIS-SUBJ-ABS-TEST_2eb85979fa54c11e387349e21639f46e'}\n\n```{.r .cell-code}\n#GGFORMULA | DENSITY HISTOGRAM SUBJECT TOTAL ABSOLUTE\n  gf_props(~item_test_NABS, data = df_subjects) + \n  labs(x = \"number of correct responses\",\n       y = \"% of subjects\",\n       title = \"Distribution of Subject Total Absolute Score — TEST Phase\",\n       subtitle = \"Modes at high and low ends of scale suggest concentration of high (vs) low understanding\") + \n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Absolute Score — TEST\nPhase' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Absolute Score — TEST\nPhase' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Absolute Score — TEST\nPhase' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Absolute Score — TEST\nPhase' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Absolute Score — TEST\nPhase' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Absolute Score — TEST\nPhase' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Absolute Score — TEST\nPhase' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Absolute Score — TEST\nPhase' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Absolute Score — TEST\nPhase' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Absolute Score — TEST\nPhase' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Absolute Score — TEST\nPhase' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Absolute Score — TEST\nPhase' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Absolute Score — TEST\nPhase' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Absolute Score — TEST\nPhase' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Absolute Score — TEST\nPhase' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Absolute Score — TEST\nPhase' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Absolute Score — TEST\nPhase' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Absolute Score — TEST\nPhase' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Absolute Score — TEST\nPhase' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Absolute Score — TEST\nPhase' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Absolute Score — TEST\nPhase' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Absolute Score — TEST\nPhase' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Absolute Score — TEST\nPhase' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Absolute Score — TEST\nPhase' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/VIS-SUBJ-ABS-TEST-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n##GGPUBR | HIST+DENSITY SCORE BY CONDITION/MODE\np <- gghistogram(df_subjects, x = \"item_test_NABS\", binwidth = 0.5,\n   add = \"mean\", rug = TRUE,\n   fill = \"pretty_condition\", #, palette = c(\"#00AFBB\", \"#E7B800\"),\n   add_density = TRUE)\nfacet(p, facet.by=c(\"pretty_condition\",\"pretty_mode\")) +\n  labs( title = \"Distribution of Total Absolute Score in TEST Phase\",\n        subtitle =\"Pattern of response is the same across data collection modes but differs by condition\",\n        x = \"Total Absolute Score\", y = \"number of subjects\") +\n  theme_minimal() + theme(legend.position = \"blank\")\n```\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/VIS-SUBJ-ABS-TEST-2.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n#PLOT EMPIRICIAL CUMULATIVE DISTRIBUTION FUNCTION\nggplot(data = df_subjects, aes(item_test_NABS)) + \n  stat_ecdf(geom = \"step\") + \n  facet_grid(pretty_condition~pretty_mode) + \n  labs( title = \"Empirical Cumulative Density Function — Test Phase Absolute Score\",\n        x = \"Test Phase Absolute Score [0,8]\", \n        y = \"Cumulative Probability\") + theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase\nAbsolute Score' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase\nAbsolute Score' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase\nAbsolute Score' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase\nAbsolute Score' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase\nAbsolute Score' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase\nAbsolute Score' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase\nAbsolute Score' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase\nAbsolute Score' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase\nAbsolute Score' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase\nAbsolute Score' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase\nAbsolute Score' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase\nAbsolute Score' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase\nAbsolute Score' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase\nAbsolute Score' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase\nAbsolute Score' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase\nAbsolute Score' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase\nAbsolute Score' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase\nAbsolute Score' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase\nAbsolute Score' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase\nAbsolute Score' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase\nAbsolute Score' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase\nAbsolute Score' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase\nAbsolute Score' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase\nAbsolute Score' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/VIS-SUBJ-ABS-TEST-3.pdf){fig-pos='H'}\n:::\n:::\n\nVisual inspection of this distribution suggests it is not normal, and likely bimodal. We verify this via an excess mass test (Ameijeiras-Alsonso et. al 2018). TODO REFERENCE\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/CHECK-SUBJ-ABS-TEST_43dbcc32cc3dc9f091f568e27a6d2aee'}\n\n```{.r .cell-code}\nmultimode::modetest(df_subjects$item_test_NABS)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in multimode::modetest(df_subjects$item_test_NABS): A modification of\nthe data was made in order to compute the excess mass or the dip statistic\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tAmeijeiras-Alonso et al. (2019) excess mass test\n\ndata:  df_subjects$item_test_NABS\nExcess mass = 0.1, p-value <2e-16\nalternative hypothesis: true number of modes is greater than 1\n```\n:::\n\n```{.r .cell-code}\nn_modes = multimode::nmodes(df_subjects$item_test_NABS, bw=2) #bw = 2questions/15 = 0.15%\nl_modes = multimode::locmodes(df_subjects$item_test_NABS,mod0 =  n_modes, display = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in multimode::locmodes(df_subjects$item_test_NABS, mod0 = n_modes, : If\nthe density function has an unbounded support, artificial modes may have been\ncreated in the tails\n```\n:::\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/CHECK-SUBJ-ABS-TEST-1.pdf){fig-pos='H'}\n:::\n:::\n\nThe excess mass test for multimodality suggests the distribution is infact multimodal (m = 0.1, p \\< 0.001), with two identifiable modes at 0.013 and 7.894, and an antimode at 2.867.\n\nBut what kind of distribution is this data? Next, we use the `fitdistrplus` package to compare the distribution of this variable to a variety of probability distribution families. First, we transform the \\# correct items to % correct items by dividing it by the total number of items (n = 13).\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/FIT-DIST-TOTAL-ABS-TEST_917b9be9de9728b88e89d31976d1d0b5'}\n\n```{.r .cell-code}\n#describe the distribution\ndescdist(data = df_subjects$item_test_NABS/8, discrete = FALSE, boot = 1000)\n```\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/FIT-DIST-TOTAL-ABS-TEST-1.pdf){fig-pos='H'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nsummary statistics\n------\nmin:  0   max:  1 \nmedian:  0 \nmean:  0.287 \nestimated sd:  0.405 \nestimated skewness:  0.876 \nestimated kurtosis:  1.93 \n```\n:::\n\n```{.r .cell-code}\nprint(\"FIT A NORMAL DISTRIBUTION\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"FIT A NORMAL DISTRIBUTION\"\n```\n:::\n\n```{.r .cell-code}\nnormal_ = fitdist(df_subjects$item_test_NABS/8,\"norm\")\nplot(normal_)\n```\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/FIT-DIST-TOTAL-ABS-TEST-2.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nprint(\"FIT A BETA DISTRIBUTION\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"FIT A BETA DISTRIBUTION\"\n```\n:::\n\n```{.r .cell-code}\nbeta_ = fitdist(df_subjects$item_test_NABS/8,\"beta\", method=\"mme\" )\nplot(beta_)\n```\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/FIT-DIST-TOTAL-ABS-TEST-3.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nsummary(beta_)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFitting of the distribution ' beta ' by matching moments \nParameters : \n       estimate\nshape1   0.0721\nshape2   0.1786\nLoglikelihood:  Inf   AIC:  -Inf   BIC:  -Inf \n```\n:::\n:::\n\nInterpreting the Cullen and Frey graph, it _appears_ that number percentage of correct responses per subject may follow a beta distribution (u-shape tpe). If we fit this variable using both a normal and beta distribution (using method of moments), it appears that the beta distribution provides a much better fit. The parameter estimates for the beta distribution are: shape1 = 0.072, shape2 = 0.179. The beta distribution is a flexible distribution insofar as it can model a wide range of shapes with its two parameters. TODO: HOW might this be applied to the total score data? \n\n**Analysis Notes**\n- This distribution is very bimodal, so OLS linear regression estimating means may not be informative, as the mean actually falls near the location of the anitmode (least common value)\n- Should investigate log transform to see if residuals of LM will be normal\n- Should investigate beta regression \n\n::: callout-note\n**Condition appears (through visual inspection) to yield a positive influence on Total Absolute Score in the TEST Phase, across data collection modalities.**\n:::\n\n\n##### Entire Task \n::: {.cell hash='3_sgc3A_description_cache/pdf/DESC-SUBJ-ABS_78403d839787cf10ed2c35255a9af09b'}\n\n```{.r .cell-code}\ntitle = \"Descriptive Statistics of Response Accuracy (Total Absolute Score)\"\nabs.stats <- rbind(\n  \"lab\"= df_lab %>% dplyr::select(s_NABS) %>% unlist() %>% favstats(),\n  \"online\" = df_online %>% dplyr::select(s_NABS) %>% unlist() %>% favstats(),\n  \"combined\" = df_subjects %>% dplyr::select(s_NABS) %>% unlist() %>% favstats()\n) \nabs.stats %>% kbl (caption = title) %>% kable_classic()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\n\\caption{\\label{tab:DESC-SUBJ-ABS}Descriptive Statistics of Response Accuracy (Total Absolute Score)}\n\\centering\n\\begin{tabular}[t]{l|r|r|r|r|r|r|r|r|r}\n\\hline\n  & min & Q1 & median & Q3 & max & mean & sd & n & missing\\\\\n\\hline\nlab & 0 & 0 & 1 & 9.00 & 13 & 4.11 & 5.09 & 126 & 0\\\\\n\\hline\nonline & 0 & 0 & 1 & 8.00 & 13 & 3.52 & 4.89 & 204 & 0\\\\\n\\hline\ncombined & 0 & 0 & 1 & 8.75 & 13 & 3.75 & 4.97 & 330 & 0\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n:::\n\nFor *in person* collection, total absolute scores (n = 126) range from 0 to 13 with a mean score of (M = 4.11, SD = 5.09).\n\nFor *online replication*, (online) total absolute accuracy scores (n = 204) range from 0 to 13 with a slightly lower mean score of (M = 3.52, SD = 4.89).\n\nWhen combined *overall*, total absolute accuracy scores (n = 330) range from 0 to 13 with a slightly lower mean score of (M = 3.75, SD = 4.97).\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/VIS-SUBJ-ABS_bbbd23e89495da989e9f5f0b911342e7'}\n\n```{.r .cell-code}\n#GGFORMULA | DENSITY HISTOGRAM SUBJECT TOTAL ABSOLUTE\n  gf_props(~s_NABS, data = df_subjects) + \n  labs(x = \"number of correct responses\",\n       y = \"% of subjects\",\n       title = \"Distribution of Subject Total Absolute Score\",\n       subtitle = \"Modes at high and low ends of scale suggest concentration of high (vs) low understanding\") + \n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/VIS-SUBJ-ABS-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n##GGPUBR | HIST+DENSITY SCORE BY CONDITION/MODE\np <- gghistogram(df_subjects, x = \"s_NABS\", binwidth = 1,\n   add = \"mean\", rug = TRUE,\n   fill = \"pretty_condition\", #, palette = c(\"#00AFBB\", \"#E7B800\"),\n   add_density = TRUE)\nfacet(p, facet.by=c(\"pretty_condition\",\"pretty_mode\")) +\n  labs( title = \"Distribution of Total Absolute Score (by Mode and Condition)\",\n        subtitle =\"Pattern of response is the same across data collection modes but differs by condition\",\n        x = \"Total Absolute Score\", y = \"number of subjects\") +\n  theme_minimal() + theme(legend.position = \"blank\")\n```\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/VIS-SUBJ-ABS-2.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n#PLOT EMPIRICIAL CUMULATIVE DISTRIBUTION FUNCTION\nggplot(data = df_subjects, aes(s_NABS)) + \n  stat_ecdf(geom = \"step\") + \n  facet_grid(pretty_condition ~ pretty_mode) + \n  labs( title = \"Empirical Cumulative Density Function — Task Absolute Score\",\n        x = \"Test Phase Absolute Score [0,13]\", \n        y = \"Cumulative Probability\") + theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Absolute\nScore' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Absolute\nScore' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Absolute\nScore' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Absolute\nScore' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Absolute\nScore' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Absolute\nScore' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Absolute\nScore' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Absolute\nScore' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Absolute\nScore' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Absolute\nScore' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Absolute\nScore' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Absolute\nScore' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Absolute\nScore' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Absolute\nScore' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Absolute\nScore' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Absolute\nScore' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Absolute\nScore' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Absolute\nScore' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Absolute\nScore' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Absolute\nScore' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Absolute\nScore' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Absolute\nScore' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Absolute\nScore' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Absolute\nScore' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/VIS-SUBJ-ABS-3.pdf){fig-pos='H'}\n:::\n:::\n\nVisual inspection of this distribution suggests it is not normal, and likely bimodal. We verify this via an excess mass test (Ameijeiras-Alsonso et. al 2018). TODO REFERENCE\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/CHECK-SUBJ-ABS_de23ddb9c0548ebb07918bcd04f1fa42'}\n\n```{.r .cell-code}\nmultimode::modetest(df_subjects$s_NABS)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in multimode::modetest(df_subjects$s_NABS): A modification of the data\nwas made in order to compute the excess mass or the dip statistic\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tAmeijeiras-Alonso et al. (2019) excess mass test\n\ndata:  df_subjects$s_NABS\nExcess mass = 0.1, p-value <2e-16\nalternative hypothesis: true number of modes is greater than 1\n```\n:::\n\n```{.r .cell-code}\nn_modes = multimode::nmodes(df_subjects$s_NABS, bw=2) #bw = 2questions/15 = 0.15%\nl_modes = multimode::locmodes(df_subjects$s_NABS,mod0 =  n_modes, display = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in multimode::locmodes(df_subjects$s_NABS, mod0 = n_modes, display =\nTRUE): If the density function has an unbounded support, artificial modes may\nhave been created in the tails\n```\n:::\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/CHECK-SUBJ-ABS-1.pdf){fig-pos='H'}\n:::\n:::\n\nThe excess mass test for multimodality suggests the distribution is infact multimodal (m = 0.1, p \\< 0.001), with two identifiable modes at 0.26 and 12.261, and an antimode at 6.985.\n\nBut what kind of distribution is this data? Next, we use the `fitdistrplus` package to compare the distribution of this variable to a variety of probability distribution families. First, we transform the \\# correct items to % correct items by dividing it by the total number of items (n = 13).\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/FIT-DIST-TOTAL-ABS_acc4f5aa4c65e55f232734905fee8af3'}\n\n```{.r .cell-code}\n#describe the distribution\ndescdist(data = df_subjects$DV_percent_NABS, discrete = FALSE, boot = 1000)\n```\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/FIT-DIST-TOTAL-ABS-1.pdf){fig-pos='H'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nsummary statistics\n------\nmin:  0   max:  1 \nmedian:  0.0769 \nmean:  0.288 \nestimated sd:  0.382 \nestimated skewness:  0.914 \nestimated kurtosis:  2.09 \n```\n:::\n\n```{.r .cell-code}\nprint(\"FIT A NORMAL DISTRIBUTION\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"FIT A NORMAL DISTRIBUTION\"\n```\n:::\n\n```{.r .cell-code}\nnormal_ = fitdist(df_subjects$DV_percent_NABS,\"norm\")\nplot(normal_)\n```\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/FIT-DIST-TOTAL-ABS-2.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nprint(\"FIT A BETA DISTRIBUTION\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"FIT A BETA DISTRIBUTION\"\n```\n:::\n\n```{.r .cell-code}\nbeta_ = fitdist(df_subjects$DV_percent_NABS,\"beta\", method=\"mme\" )\nplot(beta_)\n```\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/FIT-DIST-TOTAL-ABS-3.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nsummary(beta_)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFitting of the distribution ' beta ' by matching moments \nParameters : \n       estimate\nshape1    0.118\nshape2    0.291\nLoglikelihood:  Inf   AIC:  -Inf   BIC:  -Inf \n```\n:::\n:::\n\nInterpreting the Cullen and Frey graph, it _appears_ that number percentage of correct responses per subject may follow a beta distribution (u-shape tpe). If we fit this variable using both a normal and beta distribution (using method of moments), it appears that the beta distribution provides a much better fit. The parameter estimates for the beta distribution are: shape1 = 0.118, shape2 = 0.291. The beta distribution is a flexible distribution insofar as it can model a wide range of shapes with its two parameters. TODO: HOW might this be applied to the total score data? \n\n**Analysis Notes**\n- This distribution is very bimodal, so OLS linear regression estimating means may not be informative, as the mean actually falls near the location of the anitmode (least common value)\n- Should investigate log transform to see if residuals of LM will be normal\n- Should investigate beta regression \n\n::: callout-note\n**Condition appears (through visual inspection) to yield a positive influence on Total Absolute Score across data collection modalities.**\n:::\n\n#### Total Scaled Scores\n\nThe total scaled score `s_SCALED` summarizes the scaled score on the 13 strategy-discriminant questions, for each subject. This score ranges from from -13 (all orthogonal) to 13 (all triangular). Recall that the `s_SCALED` score for an item is a numeric representation of the strategy-consistent response, scaled from -1 to +1 (see [Section -@sec-SGC3A-scaledScore])\n\nMost importantly, the Scaled score gives us a way of quantitatively examining how correctly a participant interpreted the coordinate system across the entire set of items. It offers a more nuanced look into performance than absolute score.\n\n##### Test Phase\n\nFirst we examine performance on the test phase (final 8 questions, appears after scaffolding phase). This tells us how the participants perform _after_ exposure to the 5 scaffolding questions (in the impasse condition). \n\n::: {.cell hash='3_sgc3A_description_cache/pdf/DESC-SUBJ-SCALED-TEST_1cd4f0c634c87b1bd5e2661e91eb7085'}\n\n```{.r .cell-code}\ntitle = \"Descriptive Statistics of Response Accuracy (Total Scaled Score)\"\nscaled.stats <- rbind(\n  \"lab\"= df_lab %>% dplyr::select(item_test_SCALED) %>% unlist() %>% favstats(),\n  \"online\" = df_online %>% dplyr::select(item_test_SCALED) %>% unlist() %>% favstats(),\n  \"combined\" = df_subjects %>% dplyr::select(item_test_SCALED) %>% unlist() %>% favstats()\n) \nscaled.stats %>% kbl (caption = title) %>% kable_classic()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\n\\caption{\\label{tab:DESC-SUBJ-SCALED-TEST}Descriptive Statistics of Response Accuracy (Total Scaled Score)}\n\\centering\n\\begin{tabular}[t]{l|r|r|r|r|r|r|r|r|r}\n\\hline\n  & min & Q1 & median & Q3 & max & mean & sd & n & missing\\\\\n\\hline\nlab & -8 & -8.0 & -6.00 & 6 & 8 & -2.11 & 6.69 & 126 & 0\\\\\n\\hline\nonline & -8 & -7.5 & -5.75 & 5 & 8 & -2.32 & 6.29 & 204 & 0\\\\\n\\hline\ncombined & -8 & -8.0 & -6.00 & 6 & 8 & -2.24 & 6.43 & 330 & 0\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n:::\n\nFor **in person collection**, TEST phase scaled scores (n = 126) range from -8 to 13 with a mean score of (M = -2.11, SD = 6.69).\n\nFor **online replication**, TEST phase scaled scores (n = 204) range from -8 to 8 with a slightly lower mean score of (M = -2.32, SD = 6.29).\n\nWhen combined **overall**, TEST phase scaled scores (n = 330) range from -8 to 8 with a slightly lower mean score of (M = -2.24, SD = 6.44).\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/VIS-SUBJ-SCALED-TEST_7af7c3ba3e0a31454140ead2acd4a050'}\n\n```{.r .cell-code}\n#GGFORMULA | DENSITY HISTOGRAM SUBJECT TOTAL SCALED\ngf_props(~item_test_SCALED, data = df_subjects) +\n  labs(x = \"total scaled score\",\n       y = \"% of subjects\",\n       title = \"Distribution of Subject Total Scaled Score — TEST Phase\",\n       subtitle = \"Modes at high and low ends of scale suggest concentration of high (vs) low understanding\") + \n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Scaled Score — TEST Phase'\nin 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Scaled Score — TEST Phase'\nin 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Scaled Score — TEST Phase'\nin 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Scaled Score — TEST Phase'\nin 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Scaled Score — TEST Phase'\nin 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Scaled Score — TEST Phase'\nin 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Scaled Score — TEST Phase'\nin 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Scaled Score — TEST Phase'\nin 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Scaled Score — TEST Phase'\nin 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Scaled Score — TEST Phase'\nin 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Scaled Score — TEST Phase'\nin 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Scaled Score — TEST Phase'\nin 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Scaled Score — TEST Phase'\nin 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Scaled Score — TEST Phase'\nin 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Scaled Score — TEST Phase'\nin 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Scaled Score — TEST Phase'\nin 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Scaled Score — TEST Phase'\nin 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Scaled Score — TEST Phase'\nin 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Scaled Score — TEST Phase'\nin 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Scaled Score — TEST Phase'\nin 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Scaled Score — TEST Phase'\nin 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Scaled Score — TEST Phase'\nin 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Scaled Score — TEST Phase'\nin 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Subject Total Scaled Score — TEST Phase'\nin 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/VIS-SUBJ-SCALED-TEST-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n##GGPUBR | HIST+DENSITY SCORE BY CONDITION/MODE\np <- gghistogram(df_subjects, x = \"item_test_SCALED\",binwidth=1,\n   add = \"mean\", rug = TRUE,\n   fill = \"pretty_condition\", #, palette = c(\"#00AFBB\", \"#E7B800\"),\n   add_density = TRUE) \nfacet(p, facet.by=c(\"pretty_condition\",\"pretty_mode\")) + \n  labs( title = \"Distribution of Total Scaled Score — TEST Phase\",\n        subtitle =\"Pattern of response is similar across data collection modes but differs by condition\",\n        x = \"total scaled score\", y = \"number of participants\") + \n  theme_minimal() + theme(legend.position = \"blank\") \n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Total Scaled Score — TEST Phase' in\n'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Total Scaled Score — TEST Phase' in\n'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Total Scaled Score — TEST Phase' in\n'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Total Scaled Score — TEST Phase' in\n'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Total Scaled Score — TEST Phase' in\n'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Total Scaled Score — TEST Phase' in\n'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Total Scaled Score — TEST Phase' in\n'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Total Scaled Score — TEST Phase' in\n'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Total Scaled Score — TEST Phase' in\n'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Total Scaled Score — TEST Phase' in\n'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Total Scaled Score — TEST Phase' in\n'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Total Scaled Score — TEST Phase' in\n'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Total Scaled Score — TEST Phase' in\n'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Total Scaled Score — TEST Phase' in\n'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Total Scaled Score — TEST Phase' in\n'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Total Scaled Score — TEST Phase' in\n'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Total Scaled Score — TEST Phase' in\n'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Total Scaled Score — TEST Phase' in\n'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Total Scaled Score — TEST Phase' in\n'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Total Scaled Score — TEST Phase' in\n'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Total Scaled Score — TEST Phase' in\n'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Total Scaled Score — TEST Phase' in\n'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Total Scaled Score — TEST Phase' in\n'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution of Total Scaled Score — TEST Phase' in\n'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/VIS-SUBJ-SCALED-TEST-2.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n#PLOT EMPIRICIAL CUMULATIVE DISTRIBUTION FUNCTION\nggplot(data = df_subjects, aes(item_test_SCALED)) + \n  stat_ecdf(geom = \"step\") + \n  facet_grid(pretty_condition ~ pretty_mode) + \n  labs( title = \"Empirical Cumulative Density Function — Test Phase Scaled Score\",\n        x = \"Test Phase Scaled Score [-8,8]\", \n        y = \"Cumulative Probability\") + theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase Scaled\nScore' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase Scaled\nScore' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase Scaled\nScore' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase Scaled\nScore' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase Scaled\nScore' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase Scaled\nScore' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase Scaled\nScore' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase Scaled\nScore' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase Scaled\nScore' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase Scaled\nScore' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase Scaled\nScore' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase Scaled\nScore' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase Scaled\nScore' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase Scaled\nScore' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase Scaled\nScore' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase Scaled\nScore' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase Scaled\nScore' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase Scaled\nScore' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase Scaled\nScore' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase Scaled\nScore' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase Scaled\nScore' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase Scaled\nScore' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase Scaled\nScore' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Test Phase Scaled\nScore' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/VIS-SUBJ-SCALED-TEST-3.pdf){fig-pos='H'}\n:::\n:::\n\nVisual inspection of this distribution suggests it is not normal, and perhaps perhaps bimodal. We verify this via an excess mass test (Ameijeiras-Alsonso et. al 2018).\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/CHECK-SUBJ-SCALED-TEST_560507bca09c4352ce0129b1f48e90fa'}\n\n```{.r .cell-code}\nmultimode::modetest(df_subjects$item_test_SCALED)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in multimode::modetest(df_subjects$item_test_SCALED): A modification of\nthe data was made in order to compute the excess mass or the dip statistic\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tAmeijeiras-Alonso et al. (2019) excess mass test\n\ndata:  df_subjects$item_test_SCALED\nExcess mass = 0.2, p-value <2e-16\nalternative hypothesis: true number of modes is greater than 1\n```\n:::\n\n```{.r .cell-code}\nn_modes = multimode::nmodes(df_subjects$item_test_SCALED, bw=2) #bw = 2questions/15 = 0.15%\nl_modes = multimode::locmodes(df_subjects$item_test_SCALED,mod0 =  n_modes, display = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in multimode::locmodes(df_subjects$item_test_SCALED, mod0 = n_modes, :\nIf the density function has an unbounded support, artificial modes may have been\ncreated in the tails\n```\n:::\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/CHECK-SUBJ-SCALED-TEST-1.pdf){fig-pos='H'}\n:::\n:::\n\nThe excess mass test for multimodality suggests the distribution is in fact multimodal (m = 0.1, p \\< 0.001), with two identifiable modes at -7.721 and 7.822, and an antimode at 1.93.\n\n**Analysis Notes**\n- As with absolute score, the distribution of scaled score is very bimodal\n- Same need to investigate transformations and alternative distributions for regression\n\n::: callout-note\n**Condition appears (through visual inspection) to yield a positive influence on TEST Phase Scaled Score across data collection modalities.**\n:::\n\n##### Entire Task\nThe total scaled score `s_SCALED` summarizes the scaled score on the 13 strategy-discriminant questions, for each subject. This score ranges from from -13 (all orthogonal) to 13 (all triangular). Recall that the `s_SCALED` score for an item is a numeric representation of the strategy-consistent response, scaled from -1 to +1 (see [Section -@sec-SGC3A-scaledScore])\n\nMost importantly, the Scaled score gives us a way of quantitatively examining how correctly a participant interpreted the coordinate system across the entire set of items. It offers a more nuanced look into performance than absolute score.\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/DESC-SUBJ-SCALED_addee6a51ea18e3a351922a6e7cfc732'}\n\n```{.r .cell-code}\ntitle = \"Descriptive Statistics of Response Accuracy (Total Scaled Score)\"\nscaled.stats <- rbind(\n  \"lab\"= df_lab %>% dplyr::select(s_SCALED) %>% unlist() %>% favstats(),\n  \"online\" = df_online %>% dplyr::select(s_SCALED) %>% unlist() %>% favstats(),\n  \"combined\" = df_subjects %>% dplyr::select(s_SCALED) %>% unlist() %>% favstats()\n) \nscaled.stats %>% kbl (caption = title) %>% kable_classic()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\n\\caption{\\label{tab:DESC-SUBJ-SCALED}Descriptive Statistics of Response Accuracy (Total Scaled Score)}\n\\centering\n\\begin{tabular}[t]{l|r|r|r|r|r|r|r|r|r}\n\\hline\n  & min & Q1 & median & Q3 & max & mean & sd & n & missing\\\\\n\\hline\nlab & -13 & -12.0 & -7.50 & 8.75 & 13 & -2.70 & 10.08 & 126 & 0\\\\\n\\hline\nonline & -13 & -10.0 & -7.00 & 6.62 & 13 & -2.83 & 9.26 & 204 & 0\\\\\n\\hline\ncombined & -13 & -10.5 & -7.25 & 7.50 & 13 & -2.78 & 9.56 & 330 & 0\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n:::\n\nFor **in person collection**, total scaled scores (n = 126) range from -13 to 13 with a mean score of (M = -2.7, SD = 10.08).\n\nFor **online replication**, total scaled scores (n = 204) range from -13 to 13 with a slightly lower mean score of (M = -2.83, SD = 9.26).\n\nWhen combined **overall**, total scaled scores (n = 330) range from -13 to 13 with a slightly lower mean score of (M = -2.78, SD = 9.56).\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/VIS-SUBJ-SCALED_9b50f3e71d34a5ac5e2239673dc4add4'}\n\n```{.r .cell-code}\n#GGFORMULA | DENSITY HISTOGRAM SUBJECT TOTAL SCALED\ngf_props(~s_SCALED, data = df_subjects) +\n  labs(x = \"total scaled score\",\n       y = \"% of subjects\",\n       title = \"Distribution of Subject Total Scaled Score\",\n       subtitle = \"Modes at high and low ends of scale suggest concentration of high (vs) low understanding\") + \n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/VIS-SUBJ-SCALED-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n##GGPUBR | HIST+DENSITY SCORE BY CONDITION/MODE\np <- gghistogram(df_subjects, x = \"s_SCALED\",binwidth=1,\n   add = \"mean\", rug = TRUE,\n   fill = \"pretty_condition\", #, palette = c(\"#00AFBB\", \"#E7B800\"),\n   add_density = TRUE) \nfacet(p, facet.by=c(\"pretty_condition\",\"pretty_mode\")) + \n  labs( title = \"Distribution of Total Scaled Score (by Condition and Mode)\",\n        subtitle =\"Pattern of response is similar across data collection modes but differs by condition\",\n        x = \"total scaled score\", y = \"number of participants\") + \n  theme_minimal() + theme(legend.position = \"blank\") \n```\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/VIS-SUBJ-SCALED-2.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n#PLOT EMPIRICIAL CUMULATIVE DISTRIBUTION FUNCTION\nggplot(data = df_subjects, aes(s_SCALED)) + \n  stat_ecdf(geom = \"step\") + \n  facet_grid(pretty_condition ~ pretty_mode) + \n  labs( title = \"Empirical Cumulative Density Function — Task Scaled Score\",\n        x = \"Task Scaled Score [-13, 13]\", \n        y = \"Cumulative Probability\") + theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Scaled\nScore' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Scaled\nScore' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Scaled\nScore' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Scaled\nScore' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Scaled\nScore' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Scaled\nScore' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Scaled\nScore' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Scaled\nScore' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Scaled\nScore' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Scaled\nScore' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Scaled\nScore' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Scaled\nScore' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Scaled\nScore' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Scaled\nScore' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Scaled\nScore' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Scaled\nScore' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Scaled\nScore' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Scaled\nScore' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Scaled\nScore' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Scaled\nScore' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Scaled\nScore' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Scaled\nScore' in 'mbcsToSbcs': dot substituted for <e2>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Scaled\nScore' in 'mbcsToSbcs': dot substituted for <80>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Empirical Cumulative Density Function — Task Scaled\nScore' in 'mbcsToSbcs': dot substituted for <94>\n```\n:::\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/VIS-SUBJ-SCALED-3.pdf){fig-pos='H'}\n:::\n:::\n\nVisual inspection of this distribution suggests it is not normal, and perhaps perhaps bimodal. We verify this via an excess mass test (Ameijeiras-Alsonso et. al 2018).\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/CHECK-SUBJ-SCALED_a10edff229a1b9fe630c674511e5390b'}\n\n```{.r .cell-code}\nmultimode::modetest(df_subjects$s_SCALED)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in multimode::modetest(df_subjects$s_SCALED): A modification of the data\nwas made in order to compute the excess mass or the dip statistic\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tAmeijeiras-Alonso et al. (2019) excess mass test\n\ndata:  df_subjects$s_SCALED\nExcess mass = 0.1, p-value <2e-16\nalternative hypothesis: true number of modes is greater than 1\n```\n:::\n\n```{.r .cell-code}\nn_modes = multimode::nmodes(df_subjects$s_SCALED, bw=2) #bw = 2questions/15 = 0.15%\nl_modes = multimode::locmodes(df_subjects$s_SCALED,mod0 =  n_modes, display = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in multimode::locmodes(df_subjects$s_SCALED, mod0 = n_modes, display =\nTRUE): If the density function has an unbounded support, artificial modes may\nhave been created in the tails\n```\n:::\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/CHECK-SUBJ-SCALED-1.pdf){fig-pos='H'}\n:::\n:::\n\nThe excess mass test for multimodality suggests the distribution is in fact multimodal (m = 0.1, p \\< 0.001), with two identifiable modes at -11.195 and 12.103, and an antimode at 2.942.\n\n**Analysis Notes**\n- As with absolute score, the distribution of scaled score is very bimodal\n- Same need to investigate transformations and alternative distributions for regression\n\n::: callout-note\n**Condition appears (through visual inspection) to yield a positive influence on Total Scaled Score across data collection modalities.**\n:::\n\n#### Total Interpretations\n\nNext we consider the the interpretations assigned to each response.\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/DESC-TOTAL-INTEPRETATIONS_e7f852693c3ca68720e56d3965f80c87'}\n\n```{.r .cell-code}\ntitle = \"Proportion of Interpretations Across Items Items By Condition (Lab)\"\nitem.contingency <- df_items %>% filter(mode == \"lab-synch\") %>% dplyr::select(interpretation, pretty_condition) %>% table() %>% prop.table() %>% addmargins()\nitem.contingency %>% kbl (caption = title) %>% kable_classic()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\n\\caption{\\label{tab:DESC-TOTAL-INTEPRETATIONS}Proportion of Interpretations Across Items Items By Condition (Lab)}\n\\centering\n\\begin{tabular}[t]{l|r|r|r}\n\\hline\n  & control & impasse & Sum\\\\\n\\hline\nOrthogonal & 0.297 & 0.116 & 0.414\\\\\n\\hline\nSatisfice & 0.000 & 0.028 & 0.028\\\\\n\\hline\nfrenzy & 0.002 & 0.005 & 0.007\\\\\n\\hline\n? & 0.026 & 0.053 & 0.079\\\\\n\\hline\nreference & 0.001 & 0.004 & 0.005\\\\\n\\hline\nblank & 0.008 & 0.034 & 0.042\\\\\n\\hline\nboth tri + orth & 0.060 & 0.056 & 0.116\\\\\n\\hline\nTversky & 0.004 & 0.017 & 0.021\\\\\n\\hline\nTriangular & 0.094 & 0.195 & 0.288\\\\\n\\hline\nSum & 0.492 & 0.508 & 1.000\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n\n```{.r .cell-code}\ntitle = \"Proportion of Interpretations Across Items Items By Condition (Online)\"\nitem.contingency <- df_items %>% filter(mode == \"asynch\") %>% dplyr::select(interpretation, pretty_condition) %>% table() %>% prop.table() %>% addmargins()\nitem.contingency %>% kbl (caption = title) %>% kable_classic()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\n\\caption{\\label{tab:DESC-TOTAL-INTEPRETATIONS}Proportion of Interpretations Across Items Items By Condition (Online)}\n\\centering\n\\begin{tabular}[t]{l|r|r|r}\n\\hline\n  & control & impasse & Sum\\\\\n\\hline\nOrthogonal & 0.260 & 0.122 & 0.382\\\\\n\\hline\nSatisfice & 0.000 & 0.024 & 0.024\\\\\n\\hline\nfrenzy & 0.002 & 0.001 & 0.003\\\\\n\\hline\n? & 0.050 & 0.066 & 0.116\\\\\n\\hline\nreference & 0.000 & 0.002 & 0.002\\\\\n\\hline\nblank & 0.013 & 0.055 & 0.068\\\\\n\\hline\nboth tri + orth & 0.056 & 0.061 & 0.117\\\\\n\\hline\nTversky & 0.011 & 0.023 & 0.035\\\\\n\\hline\nTriangular & 0.078 & 0.175 & 0.253\\\\\n\\hline\nSum & 0.471 & 0.529 & 1.000\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n\n```{.r .cell-code}\ntitle = \"Proportion of Interpretations Across Items Items By Condition (Combined)\"\nitem.contingency <- df_items %>%  dplyr::select(interpretation, pretty_condition) %>% table() %>% prop.table() %>% addmargins()\nitem.contingency %>% kbl (caption = title) %>% kable_classic()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\n\\caption{\\label{tab:DESC-TOTAL-INTEPRETATIONS}Proportion of Interpretations Across Items Items By Condition (Combined)}\n\\centering\n\\begin{tabular}[t]{l|r|r|r}\n\\hline\n  & control & impasse & Sum\\\\\n\\hline\nOrthogonal & 0.274 & 0.120 & 0.394\\\\\n\\hline\nSatisfice & 0.000 & 0.025 & 0.025\\\\\n\\hline\nfrenzy & 0.002 & 0.003 & 0.004\\\\\n\\hline\n? & 0.041 & 0.061 & 0.102\\\\\n\\hline\nreference & 0.001 & 0.002 & 0.003\\\\\n\\hline\nblank & 0.011 & 0.047 & 0.058\\\\\n\\hline\nboth tri + orth & 0.058 & 0.059 & 0.117\\\\\n\\hline\nTversky & 0.009 & 0.021 & 0.029\\\\\n\\hline\nTriangular & 0.084 & 0.183 & 0.267\\\\\n\\hline\nSum & 0.479 & 0.521 & 1.000\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n:::\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/VIS-ITEM-INTERPRETATION_c3760889a7f8f0f5edd4ea55e2179c65'}\n\n```{.r .cell-code}\n#PROPORTIONAL BAR CHART\ngf_propsh(~interpretation, data = df_items, fill = ~pretty_condition) %>% \n  gf_facet_grid(mode~pretty_condition, labeller = label_both) +\n  labs(x = \"% of items\",\n       title = \"Proportion of Interpretations Across Items\",\n       subtitle=\"Impasse Condition yields shift from Orthogonal to alternative interpretations\")+\n  theme_minimal()+ theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/VIS-ITEM-INTERPRETATION-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n#MOSAIC PLOT\nvcd::mosaic(main=\"Proportion of Interpretations across Conditions\",\n            data = df_items, pretty_condition ~ interpretation, rot_labels=c(0,90,0,0), \n            offset_varnames = c(left = 4.5), offset_labels = c(left = -0.5),just_labels = \"right\",\n            spacing = spacing_dimequal(unit(1:2, \"lines\"))) \n```\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/VIS-ITEM-INTERPRETATION-2.pdf){fig-pos='H'}\n:::\n:::\n\n### First Item Scores\n\nNext we consider the response accuracy on *just* the first question of the graph comprehension task: a subject's first exposure to the TM graph.\n\n#### First Item Absolute Score\n\nNext we consider the absolute score assigned the first response.\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/DESC-FIRST-ABSOLUTE_03515a8b2fada7f6989802a0959b7995'}\n\n```{.r .cell-code}\ntitle = \"Proportion of Correct Response on First Item (Lab)\"\nitem.contingency <- df_subjects %>% filter(mode == \"lab-synch\") %>% dplyr::select(item_q1_NABS, pretty_condition) %>% table() %>% prop.table() %>% addmargins()\nitem.contingency %>% kbl (caption = title) %>% kable_classic()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\n\\caption{\\label{tab:DESC-FIRST-ABSOLUTE}Proportion of Correct Response on First Item (Lab)}\n\\centering\n\\begin{tabular}[t]{l|r|r|r}\n\\hline\n  & control & impasse & Sum\\\\\n\\hline\n0 & 0.413 & 0.357 & 0.77\\\\\n\\hline\n1 & 0.079 & 0.151 & 0.23\\\\\n\\hline\nSum & 0.492 & 0.508 & 1.00\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n\n```{.r .cell-code}\ntitle = \"Proportion of Correct Response on First Item (Online)\"\nitem.contingency <- df_subjects %>% filter(mode == \"asynch\") %>% dplyr::select(item_q1_NABS, pretty_condition) %>% table() %>% prop.table() %>% addmargins()\nitem.contingency %>% kbl (caption = title) %>% kable_classic()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\n\\caption{\\label{tab:DESC-FIRST-ABSOLUTE}Proportion of Correct Response on First Item (Online)}\n\\centering\n\\begin{tabular}[t]{l|r|r|r}\n\\hline\n  & control & impasse & Sum\\\\\n\\hline\n0 & 0.412 & 0.382 & 0.794\\\\\n\\hline\n1 & 0.059 & 0.147 & 0.206\\\\\n\\hline\nSum & 0.471 & 0.529 & 1.000\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n\n```{.r .cell-code}\ntitle = \"Proportion of Correct Response on First Item (Combined)\"\nitem.contingency <- df_subjects %>%  dplyr::select(item_q1_NABS, pretty_condition) %>% table() %>% prop.table() %>% addmargins()\nitem.contingency %>% kbl (caption = title) %>% kable_classic()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\n\\caption{\\label{tab:DESC-FIRST-ABSOLUTE}Proportion of Correct Response on First Item (Combined)}\n\\centering\n\\begin{tabular}[t]{l|r|r|r}\n\\hline\n  & control & impasse & Sum\\\\\n\\hline\n0 & 0.412 & 0.373 & 0.785\\\\\n\\hline\n1 & 0.067 & 0.148 & 0.215\\\\\n\\hline\nSum & 0.479 & 0.521 & 1.000\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n:::\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/VIS-FIRST-ABSOLUTE_e4ff1344fc6cfa30b24aa262465057ce'}\n\n```{.r .cell-code}\n#PROPORTIONAL BAR CHART\ngf_props(~item_q1_NABS, data = df_subjects) +\n  labs(x = \"response accuracy\",\n       y = \"% subjects\",\n       title = \"Proportion of Correct Responses on First Item\",\n       subtitle=\"\")+\n  theme_minimal()+ theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/VIS-FIRST-ABSOLUTE-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n#PROPORTIONAL BAR CHART\ngf_props(~item_q1_NABS, data = df_subjects, fill = ~pretty_condition) %>% \n  gf_facet_grid(mode~pretty_condition, labeller = label_both) +\n  labs(x = \"% of items\",\n       title = \"Proportion of Correct Responses on First Item (by Modality and Condition)\",\n       subtitle=\"\")+\n  theme_minimal()+ theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/VIS-FIRST-ABSOLUTE-2.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n#MOSAIC PLOT\nvcd::mosaic(main=\"Proportion of Correct Responses on First Item\",\n            data = df_subjects, pretty_condition ~ item_q1_NABS, rot_labels=c(0,90,0,0), \n            offset_varnames = c(left = 4.5), offset_labels = c(left = -0.5),just_labels = \"right\",\n            spacing = spacing_dimequal(unit(1:2, \"lines\"))) \n```\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/VIS-FIRST-ABSOLUTE-3.pdf){fig-pos='H'}\n:::\n:::\n\n#### First Item Scaled Score\n\nAt the item level, the scaled score gives us a numeric measure of correctness of interpretation, ranging from -1 to 1. (note: we evaluate scaled_score on the first item rather than interpretation, because no orthogonal interpretation is available in the impasse condition)\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/DESC-FIRST-SCALED_f6e7d22f91610616d70e4b386db16f23'}\n\n```{.r .cell-code}\ntitle = \"Descriptive Statistics of Response Accuracy (First Item Scaled Score)\"\nfirstscaled.stats <- rbind(\n  \"lab\"= df_subjects %>% filter(mode == 'lab-synch') %>% dplyr::select(item_q1_SCALED) %>% unlist() %>% favstats(),\n  \"online\" = df_subjects %>% filter(mode == \"asynch\") %>% dplyr::select(item_q1_SCALED) %>% unlist() %>% favstats(),\n  \"combined\" = df_subjects %>% dplyr::select(item_q1_SCALED) %>% unlist() %>% favstats()\n) \nfirstscaled.stats %>% kbl (caption = title) %>% kable_classic()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\n\\caption{\\label{tab:DESC-FIRST-SCALED}Descriptive Statistics of Response Accuracy (First Item Scaled Score)}\n\\centering\n\\begin{tabular}[t]{l|r|r|r|r|r|r|r|r|r}\n\\hline\n  & min & Q1 & median & Q3 & max & mean & sd & n & missing\\\\\n\\hline\nlab & -1 & -1 & -1 & 0.5 & 1 & -0.298 & 0.849 & 126 & 0\\\\\n\\hline\nonline & -1 & -1 & -1 & 0.5 & 1 & -0.287 & 0.812 & 204 & 0\\\\\n\\hline\ncombined & -1 & -1 & -1 & 0.5 & 1 & -0.291 & 0.825 & 330 & 0\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n:::\n\nFor **in person** collection, first item scaled scores (n = 126) range from -1 to 1 with a mean score of (M = -0.3, SD = 0.85).\n\nFor **online replication**, (online) first item scaled scores (n = 204) range from -1 to 1 with a slightly lower mean score of (M = -0.29, SD = 0.81).\n\nWhen combined **overall**, first item scaled scores (n = 330) range from -1 to 1 with a slightly lower mean score of (M = -0.29, SD = 0.83).\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/VIS-FIRST-SCALED_8c00f7cb56083cd53d2fb295d2523cc4'}\n\n```{.r .cell-code}\n#GGFORMULA | PROPORTIONAL HISTOGRAM SUBJECT FIRST SCALED\ngf_props(~item_q1_SCALED, data = df_subjects) +\n  labs(x = \"scaled score (first item)\",\n       y = \"% of subjects\",\n       title = \"Distribution of First Item Scaled Score\",\n       subtitle = \"\") + \n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/VIS-FIRST-SCALED-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n##GGPUBR | HIST+DENSITY SCORE BY CONDITION/MODE\np <- gghistogram(df_subjects, x = \"item_q1_SCALED\", binwidth = 0.5,\n   add = \"mean\", rug = TRUE,\n   fill = \"pretty_condition\", #, palette = c(\"#00AFBB\", \"#E7B800\"),\n   add_density = TRUE) \nfacet(p, facet.by=c(\"pretty_condition\",\"mode\")) + \n  labs( title = \"Distribution of First Item Scaled Score (by Mode and Condition)\",\n        subtitle =\"Pattern of response is the same across data collection modes but differs by condition\",\n        x = \"scaled score (firt item) \", y = \"number of participants\") + \n  theme_minimal() + theme(legend.position = \"blank\") \n```\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/VIS-FIRST-SCALED-2.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n##GGFORMULA | HIST+DENSITY SCORE BY CONDITION/MODE\n# stats = df_subjects %>% group_by(pretty_condition, mode) %>% dplyr::summarise(mean = mean(item_q1_SCALED))\n# gf_density(~item_q1_SCALED, data = df_subjects) %>%\n#   gf_facet_grid(pretty_condition~mode, labeller = label_both) %>%\n#   gf_lims(x = c(-1, 1)) %>%\n#   gf_vline(data = stats, xintercept = ~mean, color = \"red\") +\n# labs( title = \"Distribution of First Item Scaled Score (by Mode and Condition)\",\n#         subtitle =\"Pattern of response is the same across data collection modes but differs by condition\",\n#         x = \"scaled score (firt item) \", y = \"number of participants\") + \n#   theme_minimal()\n```\n:::\n\n## RESPONSE LATENCY\n\n-   [TODO: Investigate super high and super low response times.]{style=\"color: red;\"}.\n\n-   [TODO: Investigate appropriate models for response time data. (see: https://lindeloev.github.io/shiny-rt/)]{style=\"color: red;\"}.\n\n-   Especially see https://lindeloev.github.io/shiny-rt/ for ideas on modelling reaction time data\n\n### Time on Study\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/DESCRIBE-TOTALTIME_6f72387c188726757a8082b0eeef9f67'}\n\n```{.r .cell-code}\n#DESCRIBE distribution of response time\ntime.stats <- rbind(\n  \"lab\"= df_lab %>% dplyr::select(totaltime_m) %>% unlist() %>% favstats(),\n  \"online\"= df_online %>% dplyr::select(totaltime_m) %>% unlist() %>% favstats(),\n  \"combined\"= df_subjects %>% dplyr::select(totaltime_m) %>% unlist() %>% favstats()\n)\n\ntitle = \"Descriptive Statistics of Response Latency (Time on Study)\"\ntime.stats %>% kbl(caption = title) %>% kable_classic()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\n\\caption{\\label{tab:DESCRIBE-TOTALTIME}Descriptive Statistics of Response Latency (Time on Study)}\n\\centering\n\\begin{tabular}[t]{l|r|r|r|r|r|r|r|r|r}\n\\hline\n  & min & Q1 & median & Q3 & max & mean & sd & n & missing\\\\\n\\hline\nlab & 6.01 & 10.50 & 12.2 & 14.4 & 23.9 & 12.8 & 3.37 & 126 & 0\\\\\n\\hline\nonline & 2.91 & 9.18 & 11.5 & 15.0 & 111.0 & 13.4 & 9.21 & 204 & 0\\\\\n\\hline\ncombined & 2.91 & 9.55 & 12.0 & 14.7 & 111.0 & 13.2 & 7.53 & 330 & 0\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n:::\n\nTotal time on study for *in person* subjects (n = 126) ranged from 6.01 to 23.86 minutes with a mean duration of (M = 12.8, SD = 3.37).\n\nTotal time on study for *online replication* subjects (n = 204) ranged from 2.91 to 111.02 minutes with a mean duration of (M = 13.37, SD = 9.21).\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/label - VIS-TOTALTIMEmessage - falsewarning - false_8a1aa4f97711d12e5818b27d3bf62325'}\n\n```{.r .cell-code}\n#VISUALIZE distribution of response time\nplab <- gf_dhistogram(~totaltime_m, data = df_subjects) %>%\n  gf_vline(xintercept = ~time.stats[\"lab\",]$mean, color = \"black\") %>% \n  gf_fitdistr(dist=\"gamma\", color=\"red\")+\n  labs(title=\"Lab\", x = \"Total Time (mins)\", y = \"% subjects\") +  theme_minimal()\n\nponline <- gf_dhistogram(~totaltime_m, data = df_subjects) %>%\n  gf_vline(xintercept = ~time.stats[\"online\",]$mean, color = \"black\") %>% \n  gf_fitdistr(dist = \"gamma\", color=\"red\")+\n  labs(title=\"Online\", x = \"Total Time (mins)\", y = \"% subjects\") +  theme_minimal()\n\nplot <-ggarrange(plab, ponline, common.legend = TRUE, nrow = 1, ncol =2)\n\nannotate_figure(plot, \n                top = text_grob(\"Total Time by Study Mode\",color = \"black\", face = \"bold\", size = 14),\n                bottom = text_grob(\"fit by Gamma distribution\", face = \"italic\", size = 10))\n```\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/label - VIS-TOTALTIMEmessage - falsewarning - false-1.pdf){fig-pos='H'}\n:::\n:::\n\n**TODO consider log transform of response latency data** *see* archive sgc3A_participants.Rmd\n\n### Time on Question\n\n**TODO time on question**\n\n## REPLICATION CHECK\n\n### Data Collection Mode on Absolute Score\n\n**Does Mode Change Effect of Condition on Score?**\n\nTo verify that the data collected in the lab and remotely online are comparable, we perform a t-test on group means of ABSOLUTE SCORE for each condition, and examine whether data collection modality is a significant predictor of variance in absolute score\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/label - MODEL-ABSCORE-BY-MODALITY_5fa80117dd92b9bff37abc27f27bee2e'}\n\n```{.r .cell-code}\npaste(\"Two Sample T-Test for S_ABS LAB vs. ONLINE control condition\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Two Sample T-Test for S_ABS LAB vs. ONLINE control condition\"\n```\n:::\n\n```{.r .cell-code}\nt.test(data = df_subjects %>% filter(condition == 111), s_ABS ~ mode )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  s_ABS by mode\nt = 0.5, df = 120, p-value = 0.6\nalternative hypothesis: true difference in means between group lab-synch and group asynch is not equal to 0\n95 percent confidence interval:\n -1.09  1.84\nsample estimates:\nmean in group lab-synch    mean in group asynch \n                   2.68                    2.30 \n```\n:::\n\n```{.r .cell-code}\npaste(\"Two Sample T-Test for S_ABS LAB vs. ONLINE impasse condition\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Two Sample T-Test for S_ABS LAB vs. ONLINE impasse condition\"\n```\n:::\n\n```{.r .cell-code}\nt.test(data = df_subjects %>% filter(condition == 121), s_ABS ~ mode )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  s_ABS by mode\nt = 1, df = 135, p-value = 0.3\nalternative hypothesis: true difference in means between group lab-synch and group asynch is not equal to 0\n95 percent confidence interval:\n -0.727  2.435\nsample estimates:\nmean in group lab-synch    mean in group asynch \n                   5.44                    4.58 \n```\n:::\n\n```{.r .cell-code}\npaste(\"OLS Linear Regression Predicting Absolute Score by Data Collection Mode\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"OLS Linear Regression Predicting Absolute Score by Data Collection Mode\"\n```\n:::\n\n```{.r .cell-code}\nsummary(lm(data = df_subjects, formula = s_ABS ~ mode ))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = s_ABS ~ mode, data = df_subjects)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n -4.08  -3.51  -2.51   4.49   9.49 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     4.08       0.44    9.27   <2e-16 ***\nmodeasynch     -0.57       0.56   -1.02     0.31    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.94 on 328 degrees of freedom\nMultiple R-squared:  0.00314,\tAdjusted R-squared:  0.000105 \nF-statistic: 1.03 on 1 and 328 DF,  p-value: 0.31\n```\n:::\n:::\n\nBoth t-tests are non-significant with 95% confidence intervals including 0. Further, an OLS linear regression model predicting cumulative absolute score indicates that data collection mode is not a significant predictor, explaining only 0.01% of variance in absolute score, F(1,328) = 1.03, p \\> 0.05.\n\n::: callout-decision\n**It is reasonable to infer that data from both in-person and remote studies arise from the same data generating process.**\n:::\n\n### Data Collection Mode on Cumulative Score\n\n**Are the by-condition group means significantly different by data collection modality?**\n\nTo verify that the data collected in the lab and remotely online are comparable, we perform a t-test on group means of SCALED SCORE for each condition.\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/label - MODEL-SCALEDSCORE-BY-MODALITY_945ee78c8bf340083fdbe1f38d2efbde'}\n\n```{.r .cell-code}\npaste(\"Two Sample T-Test for s_SCALED LAB vs. ONLINE control condition\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Two Sample T-Test for s_SCALED LAB vs. ONLINE control condition\"\n```\n:::\n\n```{.r .cell-code}\nt.test(data = df_subjects %>% filter(condition == 111), s_SCALED ~ mode )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  s_SCALED by mode\nt = -0.1, df = 117, p-value = 0.9\nalternative hypothesis: true difference in means between group lab-synch and group asynch is not equal to 0\n95 percent confidence interval:\n -3.15  2.83\nsample estimates:\nmean in group lab-synch    mean in group asynch \n                  -6.52                   -6.36 \n```\n:::\n\n```{.r .cell-code}\npaste(\"Two Sample T-Test for s_SCALED LAB vs. ONLINE impasse condition\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Two Sample T-Test for s_SCALED LAB vs. ONLINE impasse condition\"\n```\n:::\n\n```{.r .cell-code}\nt.test(data = df_subjects %>% filter(condition == 121), s_SCALED ~ mode )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  s_SCALED by mode\nt = 0.5, df = 130, p-value = 0.6\nalternative hypothesis: true difference in means between group lab-synch and group asynch is not equal to 0\n95 percent confidence interval:\n -2.08  3.49\nsample estimates:\nmean in group lab-synch    mean in group asynch \n                  1.008                   0.306 \n```\n:::\n\n```{.r .cell-code}\npaste(\"OLS Linear Regression Predicting Scaled Score by Data Collection Mode\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"OLS Linear Regression Predicting Scaled Score by Data Collection Mode\"\n```\n:::\n\n```{.r .cell-code}\nsummary(lm(data = df_subjects, formula = s_SCALED ~ mode ))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = s_SCALED ~ mode, data = df_subjects)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-10.30  -7.80  -4.42  10.33  15.83 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)   \n(Intercept)   -2.698      0.853   -3.16   0.0017 **\nmodeasynch    -0.135      1.085   -0.12   0.9011   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 9.58 on 328 degrees of freedom\nMultiple R-squared:  4.71e-05,\tAdjusted R-squared:  -0.003 \nF-statistic: 0.0155 on 1 and 328 DF,  p-value: 0.901\n```\n:::\n:::\n\nBoth t-tests are non-significant with 95% confidence intervals including 0. Further, an OLS linear regression model predicting cumulative scaled score indicates that data collection mode is not a significant predictor, explaining less than 0.001% of variance in absolute score, F(1,328) = 0.0078, p \\> 0.05.\n\n::: callout-decision\n**It is reasonable to infer that data from both in-person and remote studies arise from the same data generating process.**\n:::\n\n## RESOURCES\n\n-   https://rpkgs.datanovia.com/ggpubr/reference/index.html\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/session_c6027d87a395c194addd1b0a7be6e7bd'}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nR version 4.2.1 (2022-06-23)\nPlatform: x86_64-apple-darwin17.0 (64-bit)\nRunning under: macOS Big Sur ... 10.16\n\nMatrix products: default\nBLAS:   /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRblas.0.dylib\nLAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib\n\nlocale:\n[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8\n\nattached base packages:\n[1] grid      stats     graphics  grDevices utils     datasets  methods  \n[8] base     \n\nother attached packages:\n [1] forcats_0.5.1      stringr_1.4.0      purrr_0.3.4        readr_2.1.2       \n [5] tidyr_1.2.0        tibble_3.1.7       tidyverse_1.3.1    ggpubr_0.4.0      \n [9] vcd_1.4-10         kableExtra_1.3.4   performance_0.9.1  fitdistrplus_1.1-8\n[13] MASS_7.3-57        multimode_1.5      mosaic_1.8.3       ggridges_0.5.3    \n[17] mosaicData_0.20.2  ggformula_0.10.1   ggstance_0.3.5     dplyr_1.0.9       \n[21] Matrix_1.4-1       Hmisc_4.7-0        ggplot2_3.3.6      Formula_1.2-4     \n[25] survival_3.3-1     lattice_0.20-45   \n\nloaded via a namespace (and not attached):\n [1] colorspace_2.0-3    ggsignif_0.6.3      ellipsis_0.3.2     \n [4] mclust_5.4.10       leaflet_2.1.1       htmlTable_2.4.0    \n [7] fs_1.5.2            base64enc_0.1-3     ggdendro_0.1.23    \n[10] rstudioapi_0.13     farver_2.1.0        ggrepel_0.9.1      \n[13] lubridate_1.8.0     fansi_1.0.3         mvtnorm_1.1-3      \n[16] xml2_1.3.3          codetools_0.2-18    splines_4.2.1      \n[19] rootSolve_1.8.2.3   knitr_1.39          polyclip_1.10-0    \n[22] jsonlite_1.8.0      broom_0.8.0         dbplyr_2.2.1       \n[25] cluster_2.1.3       png_0.1-7           ggforce_0.3.3      \n[28] compiler_4.2.1      httr_1.4.3          backports_1.4.1    \n[31] assertthat_0.2.1    fastmap_1.1.0       cli_3.3.0          \n[34] tweenr_1.0.2        htmltools_0.5.2     tools_4.2.1        \n[37] gtable_0.3.0        glue_1.6.2          Rcpp_1.0.8.3       \n[40] carData_3.0-5       cellranger_1.1.0    vctrs_0.4.1        \n[43] svglite_2.1.0       crosstalk_1.2.0     lmtest_0.9-40      \n[46] insight_0.17.1      xfun_0.31           rvest_1.0.2        \n[49] lifecycle_1.0.1     mosaicCore_0.9.0    rstatix_0.7.0      \n[52] zoo_1.8-10          scales_1.2.0        hms_1.1.1          \n[55] RColorBrewer_1.1-3  yaml_2.3.5          gridExtra_2.3      \n[58] labelled_2.9.1      rpart_4.1.16        latticeExtra_0.6-29\n[61] stringi_1.7.6       checkmate_2.1.0     rlang_1.0.3        \n[64] pkgconfig_2.0.3     systemfonts_1.0.4   pracma_2.3.8       \n[67] evaluate_0.15       labeling_0.4.2      ks_1.13.5          \n[70] htmlwidgets_1.5.4   cowplot_1.1.1       tidyselect_1.1.2   \n[73] plyr_1.8.7          magrittr_2.0.3      R6_2.5.1           \n[76] generics_0.1.2      DBI_1.1.3           pillar_1.7.0       \n[79] haven_2.5.0         foreign_0.8-82      withr_2.5.0        \n[82] abind_1.4-5         nnet_7.3-17         modelr_0.1.8       \n[85] car_3.1-0           crayon_1.5.1        KernSmooth_2.23-20 \n[88] utf8_1.2.2          tzdb_0.3.0          rmarkdown_2.14     \n[91] jpeg_0.1-9          readxl_1.4.0        data.table_1.14.2  \n[94] reprex_2.0.1        digest_0.6.29       diptest_0.76-0     \n[97] webshot_0.5.3       munsell_0.5.0       viridisLite_0.4.0  \n```\n:::\n:::\n\n## ARCHIVE\n\nSample ridgeplot code\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/unnamed-chunk-29_83ea54a52d97e350fc03399a026f25fb'}\n\n```{.r .cell-code}\n#RIDGEPLOT\n# ggplot(data = df_subjects, aes(x = s_NABS, y = mode)) +\n#   geom_density_ridges() + xlim(0,13)+\n#   facet_wrap(~condition, labeller = label_both) +\n# labs(x = \"total number correct \",\n# y = \"proportion of subjects\",\n#        title = \"Subject Cumulative Score (Absolute)\",\n#        subtitle = \"Score distributions are comparable across modalities and different across conditions\") +\n#   theme_minimal()\n```\n:::\n\n**Item Absolute Score**\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/unnamed-chunk-30_4a6434b91fca9bd9e93fa7d65d0b21d6'}\n\n```{.r .cell-code}\nx <- df_items %>% mutate(score = as.logical(score_ABS))\n\ntitle = \"Proportion of Correct Items By Condition (Lab)\"\n\nitem.contingency <- df_items %>% filter(mode == \"lab-synch\") %>% dplyr::select(score_ABS, condition) %>% table() %>% prop.table() %>% addmargins()\nitem.contingency %>% kbl (caption = title) %>% kable_classic()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\n\\caption{\\label{tab:unnamed-chunk-30}Proportion of Correct Items By Condition (Lab)}\n\\centering\n\\begin{tabular}[t]{l|r|r|r}\n\\hline\n  & 111 & 121 & Sum\\\\\n\\hline\n0 & 0.344 & 0.268 & 0.613\\\\\n\\hline\n1 & 0.148 & 0.240 & 0.387\\\\\n\\hline\nSum & 0.492 & 0.508 & 1.000\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n\n```{.r .cell-code}\ntitle = \"Proportion of Correct Items By Condition (Online)\"\nitem.contingency <- df_items %>% filter(mode == \"asynch\") %>% dplyr::select(score_ABS, condition) %>% table() %>% prop.table() %>% addmargins()\nitem.contingency %>% kbl (caption = title) %>% kable_classic()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\n\\caption{\\label{tab:unnamed-chunk-30}Proportion of Correct Items By Condition (Online)}\n\\centering\n\\begin{tabular}[t]{l|r|r|r}\n\\hline\n  & 111 & 121 & Sum\\\\\n\\hline\n0 & 0.342 & 0.307 & 0.649\\\\\n\\hline\n1 & 0.128 & 0.223 & 0.351\\\\\n\\hline\nSum & 0.471 & 0.529 & 1.000\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n:::\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/unnamed-chunk-31_1646e7aaf622e46761333a536021bf71'}\n\n```{.r .cell-code}\n#VISUALIZE distribution of response accuracy across ITEMS\n\n#HISTOGRAM\nstats = df_items %>% group_by(condition, mode) %>% dplyr::summarise(mean = mean(score_niceABS))\ngf_props(~score_niceABS, data = df_items) %>% \n  gf_facet_grid(condition~mode, labeller = label_both) +\n  labs(x = \"Item Absolute Score\",\n       title = \"Item Absolute Score\",\n       subtitle=\"Across modalities, the impasse condition yielded more correct responses\")+\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/unnamed-chunk-31-1.pdf){fig-pos='H'}\n:::\n:::\n\n**Item Scaled Score**\n\nAt the item level, the scaled score gives us a numeric measure of correctness of interpretation, ranging from -1 to 1.\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/unnamed-chunk-32_0ad2828823ceaa57b83ab7cf271ad3f1'}\n\n```{.r .cell-code}\ntitle = \"Descriptive Statistics of Item Response Accuracy (Scaled Score)\"\nscaled.stats.items <- rbind(\n  \"lab\"= df_items %>% filter(mode == 'lab-synch') %>% dplyr::select(score_SCALED) %>% unlist() %>% favstats(),\n  \"online\" = df_items %>% filter(mode == \"asynch\") %>% dplyr::select(score_SCALED) %>% unlist() %>% favstats()\n) \nscaled.stats.items %>% kbl (caption = title) %>% kable_classic()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\n\\caption{\\label{tab:unnamed-chunk-32}Descriptive Statistics of Item Response Accuracy (Scaled Score)}\n\\centering\n\\begin{tabular}[t]{l|r|r|r|r|r|r|r|r|r}\n\\hline\n  & min & Q1 & median & Q3 & max & mean & sd & n & missing\\\\\n\\hline\nlab & -1 & -1 & -0.5 & 1 & 1 & -0.128 & 0.877 & 1890 & 0\\\\\n\\hline\nonline & -1 & -1 & -0.5 & 1 & 1 & -0.136 & 0.842 & 3060 & 0\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n:::\n\n::: {.cell hash='3_sgc3A_description_cache/pdf/unnamed-chunk-33_b2a72c4880f7acba38ee71c35881f508'}\n\n```{.r .cell-code}\n#VISUALIZE distribution of response accuracy across ITEMS\n\n#HISTOGRAM\nstats = df_items %>% group_by(condition, mode) %>% dplyr::summarise(mean = mean(score_SCALED))\ngf_props(~score_SCALED, data = df_items) %>% \n  gf_facet_grid(condition~mode, labeller = label_both) %>% \n  gf_vline(data = stats, xintercept = ~mean, color = \"red\") +\n  labs(x = \"Scaled Score for Item\",\n       y = \"Proportion of Items\",\n       title = \"Distribution of Accuracy per Item (Scale Score)\",\n       subtitle=\"The impasse condition shifts density toward the positive score\")+\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](3_sgc3A_description_files/figure-pdf/unnamed-chunk-33-1.pdf){fig-pos='H'}\n:::\n:::",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}