---
title: "R Notebook"
output: html_notebook
---

# RESOURCES
- software: https://dornsife.usc.edu/labs/rwilcox/software/
- tutorial https://garstats.wordpress.com/2016/07/12/shift-function/
- sample code https://github.com/GRousselet/blog/tree/master/shift_function
- explaining the shift function https://garstats.wordpress.com/2017/02/04/shift-function-illustration/

- ROGME package https://github.com/GRousselet/rogme

# SETUP

1. Install packages RR Wilcox's WRS package and dependencies

```{r}
# # first: install dependent packages
# install.packages(c("MASS", "akima", "robustbase"))
# 
# # second: install suggested packages
# install.packages(c("akima", "cobs", "robust", "mgcv", "scatterplot3d", "quantreg", "rrcov", "lars", "pwr", "trimcluster", "mc2d", "psych", "Rfit", "DepthProc", "class", "fda", "rankFD"))
# 
# # third: install an additional package which provides some C functions
# # install.packages("devtools")
# # NOTE: This seems to be stalled and not functional any more
# # devtools::install_github("mrxiaohe/WRScpp")
# 
# # fourth: install WRS
# install_github("nicebread/WRS", subdir="pkg")

#INSTALL ROGME PACKAGE 1
# devtools::install_github("GRousselet/rogme")
library(rogme)
library(WRS)
library(tidyverse)
library(ggformula)
```

```{r}
#IMPORT SAMPLE DATA 


#> generate data
set.seed(21)
g1 <- rnorm(1000) + 6
g2 <- rnorm(1000) * 1.5 + 6

#> make tibble
df <- mkt2(g1, g2)

#faceted histogram
gf_histogram(~obs, data = df) %>% gf_facet_grid(gr ~ .) +
  labs (title = "Sample Data")

```

```{r}
#PLOT AND DISPLAY SHIFT FUNCTION

#> compute shift function
sf <- shifthd(data = df, formula = obs ~ gr, nboot = 200)
#> sf <- shifthd_pbci(data = df, formula = obs ~ gr, nboot = 200, q = c(.1,.25,.5,.75,.9))

#> plot shift function
psf <- plot_sf(sf, plot_theme = 2)
#> Warning: Using alpha for a discrete variable is not advised.

#> Warning: Using alpha for a discrete variable is not advised.

#> add labels for deciles 1 & 9
psf <- add_sf_lab(psf, sf, 
                  y_lab_nudge = .1, 
                  text_size = 4)

#> change axis labels
psf[[1]] <- psf[[1]] +  labs(x = "Group 1 quantiles of scores (a.u.)",
                             y = "Group 1 - group 2 \nquantile differences (a.u.)")
psf[[1]]

```


```{r}
# HACK WD FOR LOCAL RUNNING?
imac = "/Users/amyraefox/Code/SGC-Scaffolding_Graph_Comprehension/SGC-X/ANALYSIS/MAIN"
# # mbp = "/Users/amyfox/Sites/RESEARCH/SGC—Scaffolding Graph Comprehension/SGC-X/ANALYSIS/MAIN"
setwd(imac)
df_items <- read_rds('analysis/SGC3A/data/2-scored-data/sgc3a_scored_items.rds')
df_subjects <- read_rds('analysis/SGC3A/data/2-scored-data/sgc3a_scored_participants.rds') 
```

```{r}
#PLOT AND DISPLAY SHIFT FUNCTION

#GENERATE DATA 
set.seed(21)
g1 <- rnorm(1000) + 6
g2 <- rnorm(1000) * 1.5 + 6

#> make tibble
gf <- mkt2(g1, g2)

#COMPUTE SHIFT FUNCTION
sf <- shifthd(data = gf, formula = obs ~ gr, nboot = 200)
#> sf <- shifthd_pbci(data = df, formula = obs ~ gr, nboot = 200, q = c(.1,.25,.5,.75,.9))


#SOLO SCATTERPLOT
ps <- plot_scat2(data = gf,
                 formula = obs ~ gr,
                 xlabel = "",
                 ylabel = "Scores (a.u.)",
                 alpha = 1,
                 shape = 21,
                 colour = "grey10",
                 fill = "grey90") #> scatterplots
ps <- ps + coord_flip()
# ps

#PLOT SHIFT FUNCTION
psf <- plot_sf(gf, plot_theme = 2)
#> Warning: Using alpha for a discrete variable is not advised.
#> Warning: Using alpha for a discrete variable is not advised.

#> add labels for deciles 1 & 9
psf <- add_sf_lab(psf, sf, 
                  y_lab_nudge = .1, 
                  text_size = 4)

#> change axis labels
psf[[1]] <- psf[[1]] +  labs(x = "Group 1 quantiles of scores (a.u.)",
                             y = "Group 1 - group 2 \nquantile differences (a.u.)")
# psf[[1]]


#SCATTERPLOT WITH DECILE DIFFERENCES LABELLED
p <- plot_scat2(df,
                xlabel = "",
                ylabel = "Scores (a.u.)",
                alpha = .3,
                shape = 21,
                colour = "grey10",
                fill = "grey90") #> scatterplots
p <- plot_hd_links(p, sf[[1]],
                    q_size = 1,
                    md_size = 1.5,
                    add_rect = TRUE,
                    rect_alpha = 0.1,
                    rect_col = "grey50",
                    add_lab = TRUE,
                    text_size = 5) #> superimposed deciles + rectangle
p <- p + coord_flip() #> flip axes
# p

#ARRANGE PLOTS
library(cowplot)
cowplot::plot_grid(ps, p, psf[[1]], labels=c("A", "B", "C"), ncol = 1, nrow = 3,
                   rel_heights = c(1, 1, 1), label_size = 20, hjust = -0.5, scale=.95)
```


```{r}
#PLOT AND DISPLAY SHIFT FUNCTION

#GENERATE DATA 
df <- df_subjects %>% dplyr::select(s_NABS, condition) %>% 
  mutate(
    obs = as.numeric(s_NABS),
    gr = condition
  )


#COMPUTE SHIFT FUNCTION
sf <- shifthd(data = df, formula = obs ~ gr, nboot = 200)
#> sf <- shifthd_pbci(data = df, formula = obs ~ gr, nboot = 200, q = c(.1,.25,.5,.75,.9))




#SOLO SCATTERPLOT
ps <- plot_scat2(data = df,
                 formula = obs ~ gr,
                 xlabel = "",
                 ylabel = "Scores (a.u.)",
                 alpha = 1,
                 shape = 21,
                 colour = "grey10",
                 fill = "grey90") #> scatterplots
ps <- ps + coord_flip()
# ps

#PLOT SHIFT FUNCTION
psf <- plot_sf(sf, plot_theme = 2)
#> Warning: Using alpha for a discrete variable is not advised.
#> Warning: Using alpha for a discrete variable is not advised.

#> add labels for deciles 1 & 9
psf <- add_sf_lab(psf, sf, 
                  y_lab_nudge = .1, 
                  text_size = 4)

#> change axis labels
psf[[1]] <- psf[[1]] +  labs(x = "Group 1 quantiles of scores (a.u.)",
                             y = "Group 1 - group 2 \nquantile differences (a.u.)")
# psf[[1]]


#SCATTERPLOT WITH DECILE DIFFERENCES LABELLED
p <- plot_scat2(df,
                xlabel = "",
                ylabel = "Scores (a.u.)",
                alpha = .3,
                shape = 21,
                colour = "grey10",
                fill = "grey90") #> scatterplots
p <- plot_hd_links(p, sf[[1]],
                    q_size = 1,
                    md_size = 1.5,
                    add_rect = TRUE,
                    rect_alpha = 0.1,
                    rect_col = "grey50",
                    add_lab = TRUE,
                    text_size = 5) #> superimposed deciles + rectangle
p <- p + coord_flip() #> flip axes
# p

#ARRANGE PLOTS
library(cowplot)
cowplot::plot_grid(ps, p, psf[[1]], labels=c("A", "B", "C"), ncol = 1, nrow = 3,
                   rel_heights = c(1, 1, 1), label_size = 20, hjust = -0.5, scale=.95)
```


```{r}

#COMPARE TWO INDEPENDENT GROUPS
#> make data: two skewed distributions
set.seed(1)
df <- 4 #> Chi2 degrees of freedom
n <- 50 #> sample size for both groups
g1 <- rnorm(n) + df
g1 <- g1 - hd(g1) + df + 1.001 #> median centre + shift
g2 <- rchisq(n, df)
g2 <- g2 - hd(g2)  + df + 1 #> median centre + shift

#> make tibble
df <- mkt2(g1,g2)

#> 1D scatterplots + superimposed deciles
p <- plot_scat2(df,
                xlabel = "",
                ylabel = "Scores (a.u.)",
                alpha = 1,
                shape = 21,
                colour = "grey10",
                fill = "grey90",
                size = 3) +
  scale_x_discrete(breaks=c("Group1", "Group2"),
                   labels=c("Group 1","Group 2")) +
  theme(axis.text.y = element_text(angle = 90, hjust = .5))
p <- plot_hd_bars(p,
                   col = "black",
                   q_size = 0.5,
                   md_size = 1.5,
                   alpha = 1)
p <- p + coord_flip() #> flip axes
pscat <- p
pscat

gf_histogram(~obs, data = df) %>% gf_facet_grid(gr ~ .)



# compute shift function
set.seed(4)
sf <- shifthd_pbci(data = df, formula = obs ~ gr)

#> plot shift function
psf <- plot_sf(sf, plot_theme = 2)[[1]] +
        scale_x_continuous(breaks = seq(4, 6, 0.5)) +
        scale_y_continuous(breaks = seq(-6, 6, 2), limits = c(-6, 6))
psf



#> ----------------------------------------------
#> compute all pairwise differences + save tibble
apd <- mkt1(allpdiff(g1,g2))

#> Compute confidence interval of the median of all pairwise differences
out <- allpdiff_hdpbci(g1,g2)

#> make kernel density plot of all pairwise differences
p <- ggplot(apd, aes(obs)) +
  geom_density(alpha = 1 , fill = "grey95", colour = "black") +
  theme_bw() +
  theme(legend.position="none",
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14),
        axis.title.x = element_text(size=16,face="bold"),
        axis.title.y = element_text(size=16,face="bold")) +
  ylab("Density") +
  xlab("All pairwise differences")
# p

#> add vertical lines marking the deciles
sizeseq <- c(rep(.5,4),2,rep(.5,4))
lineseq <- c(rep(1,4),1,rep(1,4))
alphaseq <- rep(1,9) #c(rep(.7,4),.7,rep(.7,4))
todo <- apd[[1]]

q_seq <- seq(.1,.9,.1)
for (qi in 1:length(q_seq)){
  p <- p + geom_vline(xintercept = hd(todo,q_seq[[qi]]),
                      alpha = alphaseq[[qi]],
                      size = sizeseq[[qi]],
                      linetype = lineseq[[qi]],
                      colour = "black")
}
pkd <- p
pkd

#> slow because of the bootstrap confidence intervals
set.seed(7)
dasym <- asymhd(data = df, formula = obs ~ gr, 
                q = seq(5,40,5)/100, alpha = .05, nboot = 100)

#> ggplot
diff_asym <- plot_diff_asym(data = dasym)[[1]]
diff_asym

#> combine plots
cowplot::plot_grid(pscat, pkd, psf, diff_asym,
          labels=c("A", "B", "C", "D"),
          ncol = 2,
          nrow = 2,
          rel_heights = c(1, 1),
          label_size = 18,
          hjust = -0.5,
          scale=.95,
          align = "v")
```

```{r}
#CREATE FOUR PART PLOT


#COMPARE TWO INDEPENDENT GROUPS

#GENERATE DATA 
df <- df_subjects %>% dplyr::select(s_NABS, pretty_condition) %>% 
  mutate(
    obs = as.numeric(s_NABS),
    #flip order levels to correctly orient graph
    # gr = recode_factor(pretty_condition, "impasse" = "impasse", "control"="control")
    gr = pretty_condition
  )

df.111 <- df %>% filter(gr == "control")
df.121 <- df %>% filter(gr == "impasse")

#1D scatterplots + superimposed deciles
pscat <- ggplot(df, aes(x=gr, y=obs))+geom_jitter(
                width = 0.2,
                # xlabel = "",
                # ylabel = "Scores (a.u.)",
                alpha = 0.2,
                shape = 21,
                colour = "grey10",
                fill = "grey90",
                size = 2) +
   scale_x_discrete(limits=c("impasse", "control"))+
  theme(axis.text.y = element_text(angle = 90, hjust = .5))
pscat <- plot_hd_bars(pscat,
                   q = c(.1,.25,.5,.75,.9),
                   col = "black",
                   q_size = 0.2,
                   md_size = 1,
                   alpha = 1)
pscat <- pscat + coord_flip() #> flip axes


#SHIFT FUNCTION <-  ISN'T WORKING FOR SOME REASON
# set.seed(4)
# sf <- shifthd_pbci(data = df, formula = obs ~ gr, q = c(.1,.25,.5,.75,.9))
# sf <- shifthd(data = df, formula = obs ~ gr)

#CALCULATE SHIFT FUNCTIONAL MANUALLY

#--CALC DECILES
decile = c(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9)
x <- Hmisc::hdquantile(df.111$obs, se = TRUE, probs =decile)
sh.111 <- as.data.frame(x) %>% rename("control" = x)
x <- Hmisc::hdquantile(df.121$obs, se = TRUE, probs = decile)
sh.121 <- as.data.frame(x) %>% rename("impasse" = x)
my_sf <- as.data.frame(cbind(control = sh.111$control, impasse= sh.121$impasse, q = decile)) %>% 
  mutate(
    difference = control - impasse
  ) %>% dplyr::select(q,control, impasse, difference)

#--CALC Confints USING WRS 
g1 <- df %>% filter(gr == "control") %>% dplyr::pull(obs)
g2 <- df %>% filter(gr == "impasse") %>% dplyr::pull(obs)
w_sf <- WRS::shifthd(g2,g1, nboot = 100) %>% as.data.frame() 

x <- as.data.frame(cbind(q=my_sf$q, control=my_sf$control, 
           impasse = my_sf$impasse, difference = my_sf$difference,
           check_diff = w_sf$Delta.hat, ci_lower = w_sf$ci.lower, ci_upper = w_sf$ci.upper))

#--CONVERT TO LIST OF DATAFRAMES
my_sf <- list(`control-impasse`=x)


#>PLOT SHIFT FUNCTION
# psf <- plot_sf(sf, plot_theme = 2)[[1]] +
#         scale_x_continuous(breaks = seq(4, 6, 0.5)) +
#         scale_y_continuous(breaks = seq(-6, 6, 2), limits = c(-6, 6))
# psf

psf <- plot_sf(my_sf, plot_theme = 2)[[1]] 


#> ----------------------------------------------
#> compute all pairwise differences + save tibble
apd <- mkt1(allpdiff(g1,g2))

#> Compute confidence interval of the median of all pairwise differences
out <- allpdiff_hdpbci(g1,g2)

#> make kernel density plot of all pairwise differences
p <- ggplot(apd, aes(obs)) +
  geom_density(alpha = 1 , fill = "grey95", colour = "black") +
  theme_bw() +
  theme(legend.position="none",
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14),
        axis.title.x = element_text(size=16,face="bold"),
        axis.title.y = element_text(size=16,face="bold")) +
  ylab("Density") +
  xlab("All pairwise differences")
p

#> add vertical lines marking the deciles
sizeseq <- c(rep(.5,4),2,rep(.5,4))
lineseq <- c(rep(1,4),1,rep(1,4))
alphaseq <- rep(1,9) #c(rep(.7,4),.7,rep(.7,4))
todo <- apd[[1]]

q_seq <- seq(.1,.9,.1)
for (qi in 1:length(q_seq)){
  p <- p + geom_vline(xintercept = hd(todo,q_seq[[qi]]),
                      alpha = alphaseq[[qi]],
                      size = sizeseq[[qi]],
                      linetype = lineseq[[qi]],
                      colour = "black")
}
pkd <- p
pkd

#> slow because of the bootstrap confidence intervals
set.seed(7)
dasym <- asymhd(data = df, formula = obs ~ gr, 
                q = seq(5,40,5)/100, alpha = .05, nboot = 100)

#> ggplot
diff_asym <- plot_diff_asym(data = dasym)[[1]]
diff_asym

# Kolmogorov-Smirnov test
#If y is numeric, a two-sample (Smirnov) test of the null hypothesis that x and y 
#were drawn from the same continuous distribution is performed. Alternatively, y ...

#null is X is drawn from CDF EQUAL TO Y
ks.test(df$obs ~ df$gr) 
print("SUGGESTS that impasse and control come from different population distributions")

#null is X is NOT LESS THAN Y
ks.test(df$obs ~ df$gr, alternative = "greater") 
print("SUGGESTS that true CDF of CONTROL is greater than that of IMPASSE [consistent with higher probability of low scores]")

#> combine plots
cowplot::plot_grid(pscat, pkd, psf, diff_asym,
          labels=c("A", "B", "C", "D"),
          ncol = 2,
          nrow = 2,
          rel_heights = c(1, 1),
          label_size = 18,
          hjust = -0.5,
          scale=.95,
          align = "v")
```

https://garstats.wordpress.com/2016/07/12/shift-function/
```{r}
## shift_function_demo

# Code to reproduce the figures in my blog post on the shift function
# Copyright (C) 2016 Guillaume Rousselet - University of Glasgow

## ============================
## dependencies
# The text files should be in working directory of this script,
# or you can specify the path in each `source()` command:
source("shift_function/Rallfun-v30.txt")
source("shift_function/wilcox_modified.txt")
source("shift_function/rgar_visualisation.txt")
source("shift_function/rgar_utils.txt")
# packages:
library("ggplot2")
library("cowplot")
## ============================

# --------------------------------
# example 1: difference in spread 
# --------------------------------
# set.seed(21)
# g1 <- rnorm(1000) + 6
# g2 <- rnorm(1000)*1.5 + 6


#What do common tests say about the difference?
ks(g1,g2, w=T) # Kolmogorov-Smirnov test
t.test(g1,g2) # regular Welsh t-test

# make data frame
df <- mkdf2(g1,g2)

# kernel density estimate + rug plot + superimposed deciles
kde <- plot.kde_rug_dec2(df)
kde

# compute shift function
out <- shifthd( g1, g2, nboot=200)

# plot shift function
sf <- plot.sf(data=out) # function from rgar_visualisation.txt
sf

# combine KDE + SF
plot_grid(kde, sf, labels=c("A", "B"), ncol = 1, nrow = 2, rel_heights = c(1.5, 1),label_size = 18,hjust = -1,scale=.95)

# save figure
ggsave(filename='shift_function_ex1_spread.jpeg') #path=pathname

# --------------------------------
# example 2: complete shift 
# --------------------------------
set.seed(21)
g1 <- rnorm(1000) + 6
g2 <- rnorm(1000) + 6.5

ks(g1,g2) # Kolmogorov-Smirnov test
t.test(g1,g2) # regular Welsh t-test

# make data frame
df <- mkdf2(g1,g2)
# kernel density estimate + rug plot + superimposed deciles
kde <- plot.kde_rug_dec2(df)
# compute shift function
out <- shifthd( g1, g2, nboot=200)
# plot shift function
sf <- plot.sf(data=out) # function from rgar_visualisation.txt
# combine KDE + SF
plot_grid(kde, sf, labels=c("A", "B"), ncol = 1, nrow = 2, rel_heights = c(1.5, 1),label_size = 18,hjust = -1,scale=.95)
# save figure
ggsave(filename='shift_function_ex2_complete.jpeg') #path=pathname

# --------------------------------
# example 3: one sided shift (I) 
# --------------------------------
set.seed(21)
g1 <- rnorm(1000)
g1[g1>0] <- g1[g1>0]*2
g2 <- rnorm(1000)

ks(g1,g2) # Kolmogorov-Smirnov test
t.test(g1,g2) # regular Welsh t-test

# make data frame
df <- mkdf2(g1,g2)
# kernel density estimate + rug plot + superimposed deciles
kde <- plot.kde_rug_dec2(df)
# compute shift function
out <- shifthd( g1, g2, nboot=200)
# plot shift function
sf <- plot.sf(data=out) # function from rgar_visualisation.txt
# combine KDE + SF
plot_grid(kde, sf, labels=c("A", "B"), ncol = 1, nrow = 2, rel_heights = c(1.5, 1),label_size = 18,hjust = -1,scale=.95)
# save figure
ggsave(filename='shift_function_ex3_onesided1.jpeg') #path=pathname

# -----------------------------------
# example 4: one sided shift (II)
# -----------------------------------
set.seed(4)
n = 300
g1 <- rgamma(n, shape = 7, scale = 2)
g2 <- rgamma(n, shape = 7, scale = 2.1)
md.g2 <- hd(g2) # median
# g2plot(g1,g2,op=4);abline(v=md.g2)
g2[g2>md.g2] <- sort(g2[g2>md.g2]) * seq(1,1.3,length.out=sum(g2>md.g2))
g1 <- g1*4 + 300
g2 <- g2*4 + 300

ks(g1,g2) # Kolmogorov-Smirnov test
t.test(g1,g2) # regular Welsh t-test

# make data frame
df <- mkdf2(g1,g2)
# kernel density estimate + rug plot + superimposed deciles
kde <- plot.kde_rug_dec2(df)
# compute shift function
out <- shifthd( g1, g2, nboot=200)
# plot shift function
sf <- plot.sf(data=out) # function from rgar_visualisation.txt
# combine KDE + SF
plot_grid(kde, sf, labels=c("A", "B"), ncol = 1, nrow = 2, rel_heights = c(1.5, 1),label_size = 18,hjust = -1,scale=.95)
# save figure
ggsave(filename='shift_function_ex4_onesided2.jpeg') #path=pathname

# --------------------------------
# example 5: no change
# --------------------------------
set.seed(7)
g1 <- rnorm(1000)
g2 <- rnorm(1000)

ks(g1,g2) # Kolmogorov-Smirnov test
t.test(g1,g2) # regular Welsh t-test

# make data frame
df <- mkdf2(g1,g2)
# kernel density estimate + rug plot + superimposed deciles
kde <- plot.kde_rug_dec2(df) + 
        scale_x_continuous(breaks = seq(-3, 3, 1))
# compute shift function
out <- shifthd( g1, g2, nboot=200)
# plot shift function
sf <- plot.sf(data=out) # function from rgar_visualisation.txt
# combine KDE + SF
plot_grid(kde, sf, labels=c("A", "B"), ncol = 1, nrow = 2, rel_heights = c(1.5, 1),label_size = 18,hjust = -1,scale=.95)
# save figure
ggsave(filename='shift_function_ex5_nochange.jpeg') #path=pathname

# -----------------------------------
# example 6: ozone data
# -----------------------------------
# data used in:
# Doksum, K.A. & Sievers, G.L. (1976)
# Plotting with Confidence - Graphical Comparisons of 2 Populations
# Biometrika, 63, 421-434
# control group:
g1 <- c(41,38.4,24.4,25.9,21.9,18.3,13.1,27.3,28.5,-16.9,26,17.4,21.8,15.4,27.4,19.2,22.4,17.7,26,29.4,21.4,26.6,22.7)
# ozone group:
g2 <- c(10.1,6.1,20.4,7.3,14.3,15.5,-9.9,6.8,28.2,17.9,-9,-12.9,14,6.6,12.1,15.7,39.9,-15.9,54.6,-14.7,44.1,-9)

ks(g1,g2) # Kolmogorov-Smirnov test
t.test(g1,g2) # regular Welsh t-test

# make data frame
df <- mkdf2(g1,g2)
# 1D scatterplots + superimposed deciles
scat <- plot.scat_dec(df,size=4,stroke=1) + 
      labs(list(x = "Rat groups", y = "Weight gains in grams")) +
  scale_x_discrete(breaks=c("Group 1", "Group 2"),
                   labels=c("Control group","Ozone group")) +
  theme(axis.text.y = element_text(angle = 90, hjust = .5))
# scat  

# compute shift function
set.seed(4)
out <- shifthd( g1, g2, nboot=200)
# plot shift function
sf <- plot.sf(data=out) # function from rgar_visualisation.txt
# combine scatterplots + SF
plot_grid(scat, sf, labels=c("A", "B"), ncol = 1, nrow = 2, rel_heights = c(1.5, 1),label_size = 18,hjust = -1,scale=.95)
# save figure
ggsave(filename='shift_function_ex6_ozone.jpeg') #path=pathname

# -----------------------------------
# example 7: Guinea pig survival data
# -----------------------------------
# data from:
# Bjerkedal, T. (1960)
# Acquisition of resistance in guinea pigs infected with different doses of virulent tubercle bacilli
# American Journal of Hygiene, 72(1):130?48
# Table 6, columns 1 & 2
# and used in:
# Doksum, K. (1974) 
# Empirical Probability Plots and Statistical Inference for Nonlinear Models in the two-Sample Case
# Annals of Statistics, 2, 267-277
g1 <- scan("bjerkedal_control_group.txt")
g2 <- scan("bjerkedal_treatment_group.txt")

ks(g1,g2) # Kolmogorov-Smirnov test
t.test(g1,g2) # regular Welsh t-test

# make data frame
df <- mkdf2(g1,g2)
# 1D scatterplots + superimposed deciles
scat <- plot.scat_dec(df,size=4,stroke=1) + 
  labs(list(x = "Rat groups", y = "Survival time in days")) +
  scale_x_discrete(breaks=c("Group 1", "Group 2"),
                   labels=c("Control group","Treatment group")) +
  theme(axis.text.y = element_text(angle = 90, hjust = .5))
scat
# compute shift function
set.seed(4)
out <- shifthd( g1, g2, nboot=200)
# plot shift function
sf <- plot.sf(data=out) # function from rgar_visualisation.txt
# combine KDE + SF
plot_grid(scat, sf, labels=c("A", "B"), ncol = 1, nrow = 2, rel_heights = c(1.5, 1),label_size = 18,hjust = -1,scale=.95)
# save figure
ggsave(filename='shift_function_ex7_guineapigs.jpeg') #path=pathname

# ----------------------------------------
# Other options to compute shift functions
# ----------------------------------------

# The `shifthd` function uses a percentile bootstrap estimation of the 
# standard error of the quantiles to compute the difference 
# confidence intervals (Wilcox 1995).
# An alternative strategy is to use straightforward percentile bootstrap 
# confidence intervals (Wilcox et al. 2012, 2014).
# I have modified these newer functions from Wilcox, so they can be used
# with the ggplot2 function plot.pbsf() in `rgar_visualisation.txt`. 
# The modified functions qcomhd() and Dqcomhd() are in `wilcox_modified.txt`
# here <https://github.com/GRousselet/rstats>.

# `qcomhd` can be used to compare the deciles using the Harrell-Davis estimator,
# similarly to shifhd:
qcomhd(g1,g2,q=seq(.1,.9,.1),xlab="Control",ylab="Control-treatment");abline(0,0)
# `qcomhd` can be also be used to:
# - compare quantiles other the deciles,
qcomhd(g1,g2,q=seq(.1,.9,.05),xlab="Control",ylab="Control-treatment");abline(0,0)
# - consider alpha other than 0.05
qcomhd(g1,g2,q=c(.1,.25,.5,.75,.9),xlab="Control",ylab="Control-treatment",alpha=0.1);abline(0,0)
# Also, unlike shifthd, qcomhd performs well even when there are tied values.

## ==========================================================================  
## Dependent groups
## ==========================================================================

### Example with repeated measures and systematic shift between conditions:
set.seed(4)
g1 <- rnorm(100)
g2 <- x+.1*runif(100,0,1)

### to look at deciles only, with alpha = 0.05 only, and no tied values
shiftdhd(g1,g2)

### Dqcomhd - equivalent to qcomhd, but for dependent groups
Dqcomhd(g1,g2)

### compare deciles using single order statistics + percentile bootstrap
qdec2ci(g1,g2)

# -----------------------------------
# example 8: test-retest
# -----------------------------------
# ses1 contains ERP onsets from 120 participants
# we only use participants tested twice
x <- read.table("onset.txt") 
twoses <- scan("onset_twoses.txt")
ses1 <- x[twoses==1,3]
# ses2 contains onsets from 74 participants who also provided ses1 onsets
x <- read.table("onset2.txt")
ses2 <- x[,3]

# make data frame
df <- mkdf2(ses1,ses2)
# kernel density estimate + rug plot + superimposed deciles
kde <- plot.kde_rug_dec2(df) + scale_x_continuous(breaks = seq(50,200,25))
# compute shift function
set.seed(4)
out <- shiftdhd( ses1, ses2, nboot=200) 
# plot shift function
sf <- plot.sf(data=out) +
  scale_x_continuous(breaks = seq(70,120,10))
# combine KDE + SF
plot_grid(kde, sf, labels=c("A", "B"), ncol = 1, nrow = 2, rel_heights = c(1.5, 1),label_size = 18,hjust = -1,scale=.95)
# save figure
ggsave(filename='shift_function_ex8_onsets.jpeg') #path=pathname

# with KDE of pairwise differences ----------------------------------
diff <- ses1-ses2 # pairwise differences
df1 <- mkdf1(diff) # make data frame
kde1 <- plot.kde_rug_dec1(df1) + xlab("Paired differences") +
        scale_x_continuous(breaks = seq(-50,60,10))

# combine KDE + KDE(difference) + SF
plot_grid(kde, kde1, sf, labels=c("A", "B", "C"), ncol = 1, nrow = 3, rel_heights = c(1.5, 1, 1),label_size = 18,hjust = -1,scale=.95)
# save figure
ggsave(filename='shift_function_ex9_onsets_diff.jpeg') #path=pathname

# with violinplot of pairwise differences ----------------------------------
p <- ggplot(df1, aes(x=1, y=data))
p1 <- p + geom_violin(fill="grey90",colour="black",adjust=.5,size=.5) +
  geom_abline(intercept = 0, slope = 0,colour="black",size=1,linetype=2) + 
  stat_summary(fun.data="plot.q123",geom="pointrange", color = "grey20",size=1) +
  scale_y_continuous(breaks = seq(-50, 60, 10)) +
  labs(y = "Pairwise differences") +
  theme(axis.text.y = element_text(colour="grey20",size=16),
        axis.title.y = element_text(colour="grey20",size=18),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank()) +
  scale_x_continuous(limits=c(0.2, 1.8))
# p1

toprow <- plot_grid(kde, p1, labels=c("A", "B"), ncol = 2, nrow = 1, rel_widths = c(3, 1),label_size = 18,hjust = -1)
plot_grid(toprow, sf, labels = c('', 'C'), ncol = 1, nrow = 2, rel_heights = c(1.5, 1), scale = 1,label_size = 18,
          align='h',hjust = -1)
# save figure
ggsave(filename='shift_function_ex10_onsets_diff_violin.jpeg') #path=pathname

# with scatterplot of pairwise differences ----------------------------------
p <- ggplot(df1, aes(x=gr, y=data))
p1 <- p + geom_jitter(position=position_jitter(0.3),fill="grey90",colour="grey50", 
                      shape=21,size=3,stroke=1,alpha=0.5) +
  geom_abline(intercept = 0, slope = 0,colour="black",size=1,linetype=2) +
  stat_summary(fun.data="plot.q123",geom="pointrange", color = "black",size=1) +
  scale_y_continuous(breaks = seq(-50, 60, 10)) +
  labs(y = "Pairwise differences") +
  theme(axis.text.y = element_text(colour="grey20",size=16),
        axis.title.y = element_text(colour="grey20",size=18),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())

# add horizintal lines markign the quartiles instead:
# p1 + stat_summary(fun.data="plot.q1", geom="errorbar", colour="grey20", width=.4, size=1) +
#   stat_summary(fun.data="plot.q2", geom="errorbar", colour="grey20", width=.4, size=2) +
#   stat_summary(fun.data="plot.q3", geom="errorbar", colour="grey20", width=.4, size=1)
# p1

toprow <- plot_grid(kde, p1, labels=c("A", "B"), ncol = 2, nrow = 1, rel_widths = c(3, 1),label_size = 18,hjust = -1)
plot_grid(toprow, sf, labels = c('', 'C'), ncol = 1, nrow = 2, rel_heights = c(1.5, 1), scale = 1,label_size = 18,
          align='h',hjust = -1)
# save figure
ggsave(filename='shift_function_ex11_onsets_diff_scatter.jpeg') #path=pathname
# ggsave(filename='shift_function_ex11_onsets_diff_scatter.jpeg',width=10,height=10) #path=pathname

```