<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-0.9.328">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2022-06-27">

<title>x_sgc3A_logistic</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
</style>

<script src="x_sgc3a_logistic_files/libs/clipboard/clipboard.min.js"></script>
<script src="x_sgc3a_logistic_files/libs/quarto-html/quarto.js"></script>
<script src="x_sgc3a_logistic_files/libs/quarto-html/popper.min.js"></script>
<script src="x_sgc3a_logistic_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="x_sgc3a_logistic_files/libs/quarto-html/anchor.min.js"></script>
<link href="x_sgc3a_logistic_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link id="quarto-text-highlighting-styles" href="x_sgc3a_logistic_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet">
<script src="x_sgc3a_logistic_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="x_sgc3a_logistic_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="x_sgc3a_logistic_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">x_sgc3A_logistic</h1>
</div>





<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 27, 2022</p>
    </div>
  </div>
    
  </div>
  

</header>

<p>The purpose of this notebook is to document learning about logistic regression, through the example of analyzing SGC3A data.</p>
<section id="logistic-regression" class="level2">
<h2 class="anchored" data-anchor-id="logistic-regression">Logistic Regression</h2>
<p>A few important concepts in logistic regression:</p>
<p><strong>ODDS</strong> Odds are <em>not</em> probabilities. Whereas a probability represents the ratio of instances when an event occurs, divided by the total number of events, odds are the ratio of instances when an event occurs, divided by the number of instances when the event does not occur. The scale of probabilities always range from 0 to 1. While the scale of odds range from 0 to + infinity. Values between 0 and 1 indicate odds not in favor, and 1+ indicate odds very in favor.</p>
<p>So for the example of a team winning one game out of 5:</p>
<ul>
<li><p>the probability of winning is = number of wins / number of games = 1/5 = 0.2 = 20% probability of win</p></li>
<li><p>the odds of winning is = number of wins / number of losses = 1/4 = 1:4 odds of winnning; 0.25 odds of winning</p></li>
<li><p>The odds can also be expressed as a ratio between probibilities : p / (1-p) ; 0.2 / 0.8 = 0.25</p></li>
</ul>
<p><strong>LOG ODDS</strong> Because the scale of odds ranges from 0 to +1 and is thus asymmetric, it is common to <em>log transform</em> the odds, producing <strong>log odds</strong>. This yields a value ranging from negative infinity to positive infinity.</p>
<p><strong>ODDS RATIO</strong> Although odds are ratios (probability of event occurring / probability of event not occurring), they are not the same as odds ratios. Odds ratios are ratios of odds, and they are used to explore relationships between variables.</p>
<p>Consider the example of the relationship between a team winning, and which uniforms they wear.</p>
<table class="table">
<thead>
<tr class="header">
<th>RESULT</th>
<th>Win</th>
<th>Loss</th>
<th>TOTAL</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>White Uniform</td>
<td>23</td>
<td>117</td>
<td>140</td>
</tr>
<tr class="even">
<td>Red Uniform</td>
<td>6</td>
<td>210</td>
<td>216</td>
</tr>
<tr class="odd">
<td><strong>TOTAL</strong></td>
<td>29</td>
<td>327</td>
<td>356</td>
</tr>
</tbody>
</table>
<ul>
<li><p>The total number of games played is 256.</p></li>
<li><p>The <strong>probability of winning</strong> = # wins / # games = 29 / 356 = 0.0815</p></li>
<li><p>The <strong>odds of winning</strong> = # wins / # losses = 29 / 327 = 0.0887</p></li>
</ul>
<p>To understand the relationship between uniform and game outcome we can calculate the odds ratio.</p>
<p><em>If the team is wearing white uniforms, are the odds higher that they will win the game?</em></p>
<p>odds ratio = odds of winning given white / odds of winning given red</p>
<p>Given that the team is wearing a white uniform, the odds that they win the game are = 23 / 17</p>
<p>Given that the team is wearing a red uniform, the odds that they win the game are = 6 / 210</p>
<p>odds ratio = [23/117] / [6/210] = 1.97 / 0.0286 = 6.88</p>
<p>The odds ratio tells us that the odds are 6.88 times greater that when the team wears a white uniform, they will also win the game.</p>
<p>log(odds ratio) = log(6.88) = 1.93</p>
<p>Compared to linear regression… the odds ratio (and logs odds ratio) are similar to R-squared in linear regression. They indicate the relationship between two variables. And like R-squared, they can be interpreted to yield a measure of effect size. Larger values mean the predictor explains more variation in the outcome, and smaller values indicate less variation explained.</p>
<p><em>What about statistical significance?</em></p>
<p>(1) Fisher’s Exact Test</p>
<p>(2) Chi-Square Test</p>
<p>(3) Wald Test</p>
</section>
<section id="resources" class="level2">
<h2 class="anchored" data-anchor-id="resources">Resources</h2>
<p><em>Helpful Explanation Videos</em></p>
<ul>
<li><p>Odds Ratios: https://www.youtube.com/watch?v=8nm0G-1uJzA</p></li>
<li><p>Odds https://www.youtube.com/watch?v=ARfXDSkQf1Y&amp;ab_channel=StatQuestwithJoshStarmer</p></li>
<li><p>Logistic Regression Clearly Explained https://www.youtube.com/watch?v=yIYKR4sgzI8&amp;ab_channel=StatQuestwithJoshStarmer</p></li>
</ul>
</section>

</main>
<!-- /main column -->
<script type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>