<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-0.9.328">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>SGC-X - 4&nbsp; Hypothesis Testing</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<link href="../../analysis/SGC3A/5_sgc3A_exploration.html" rel="next">
<link href="../../analysis/SGC3A/3_sgc3A_description.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link id="quarto-text-highlighting-styles" href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">SGC-X</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">Status</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="../../analysis/SGC3A/SGC3A.html" class="sidebar-item-text sidebar-link">SGC3A</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../analysis/SGC3A/1_sgc3A_harmonize.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Harmonization</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../analysis/SGC3A/2_sgc3A_scoring.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Response Scoring</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../analysis/SGC3A/3_sgc3A_description.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Description</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../analysis/SGC3A/4_sgc3A_hypotesting.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../analysis/SGC3A/5_sgc3A_exploration.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Exploratory Analyses</span></a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#initial-performance" id="toc-initial-performance" class="nav-link active" data-scroll-target="#initial-performance"> <span class="header-section-number">4.1</span> INITIAL PERFORMANCE</a>
  <ul class="collapse">
  <li><a href="#response-accuracy-of-first-question-by-condition" id="toc-response-accuracy-of-first-question-by-condition" class="nav-link" data-scroll-target="#response-accuracy-of-first-question-by-condition"> <span class="header-section-number">4.1.1</span> Response Accuracy of First Question by Condition</a>
  <ul class="collapse">
  <li><a href="#chi-square-accuracy-condition" id="toc-chi-square-accuracy-condition" class="nav-link" data-scroll-target="#chi-square-accuracy-condition"> <span class="header-section-number">4.1.1.1</span> Chi Square | Accuracy ~ Condition</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#cumulative-performance" id="toc-cumulative-performance" class="nav-link" data-scroll-target="#cumulative-performance"> <span class="header-section-number">4.2</span> CUMULATIVE PERFORMANCE</a>
  <ul class="collapse">
  <li><a href="#cumulative-score-by-condition" id="toc-cumulative-score-by-condition" class="nav-link" data-scroll-target="#cumulative-score-by-condition"> <span class="header-section-number">4.2.1</span> Cumulative Score By Condition</a>
  <ul class="collapse">
  <li><a href="#linear-regression" id="toc-linear-regression" class="nav-link" data-scroll-target="#linear-regression"> <span class="header-section-number">4.2.1.1</span> Linear Regression</a></li>
  <li><a href="#poisson-regression" id="toc-poisson-regression" class="nav-link" data-scroll-target="#poisson-regression"> <span class="header-section-number">4.2.1.2</span> Poisson Regression</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#resources" id="toc-resources" class="nav-link" data-scroll-target="#resources"> <span class="header-section-number">4.3</span> RESOURCES</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-SGC3A-hypotesting" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
<p class="subtitle lead">Study SGC3A | 4 Hypothesis Testing</p>
</div>





<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<div style="page-break-after: always;"></div>
<p><strong>TODO</strong><br>
</p>
<ul>
<li>clarify core questions being asked</li>
<li>update SGC3A main based on hypothesis organization</li>
<li>decision table for cummulative performance</li>
<li>review models already created in ARCHIVE?</li>
<li>explore response consistency</li>
</ul>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co">#ALL THE THINGS</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Hmisc) <span class="co"># %nin% operator</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr) <span class="co">#arrange plots</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggformula) <span class="co">#easy graphs</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(report) <span class="co">#easystats reporting</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(see) <span class="co">#easystats visualization</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance) <span class="co">#easystats model diagnostics</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gmodels) <span class="co">#contingency table and CHISQR</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vcd) <span class="co">#mosaic plots</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vcdExtra) <span class="co">#mosaic plots</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra) <span class="co">#printing tables </span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co">#set some output options</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">dplyr.summarise.inform =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">ggplot2.summarise.inform =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen=</span><span class="dv">1</span>, <span class="at">digits=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><em>The purpose of this notebook is test the hypotheses that determined the design of the SGC3A study.</em></p>
<table class="table">
<colgroup>
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th>Pre-Requisite</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1_sgc3A_harmonize.qmd<br>
2_sgc3A_scoring.qmd</td>
</tr>
</tbody>
</table>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#IMPORT DATA </span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>df_items <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">'data/2-scored-data/sgc3a_scored_items.rds'</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>df_subjects <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">'data/2-scored-data/sgc3a_scored_participants.rds'</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co">#SEPARATE ITEM DATA BY QUESTION TYPE</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>df_scaffold <span class="ot">&lt;-</span> df_items <span class="sc">%&gt;%</span> <span class="fu">filter</span>(q <span class="sc">&lt;</span> <span class="dv">6</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>df_test <span class="ot">&lt;-</span> df_items <span class="sc">%&gt;%</span> <span class="fu">filter</span>(q <span class="sc">&gt;</span> <span class="dv">6</span>) <span class="sc">%&gt;%</span> <span class="fu">filter</span> (q <span class="sc">%nin%</span> <span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">9</span>))</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>df_nondiscrim <span class="ot">&lt;-</span> df_items <span class="sc">%&gt;%</span> <span class="fu">filter</span> (q <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">9</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>There are x questions we aim to answer :</p>
<p>(1) Does the experimental condition yield significantly better performance on the first question?</p>
<p>(2) Does the experimental condition yield significantly better performance overall?</p>
<section id="initial-performance" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="initial-performance"><span class="header-section-number">4.1</span> INITIAL PERFORMANCE</h2>
<p>The graph comprehension tasks includes 15 questions completed in sequence. But the first question the reader encounters (Q1) is the most important, as it is their <em>first exposure</em> to the unconventional triangular coordinate system.</p>
<p>TODO: - does impasse yield different exploration behavior? (characterize mouse) - does impasse yield more time on task? (characterize response time ? number of answers then de-selected?)</p>
<p>TODO: Think about characterizing how variable the interpretations are across a participant. Do they form an interpretation and hold it constant? Or do they change question to question.</p>
<section id="response-accuracy-of-first-question-by-condition" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="response-accuracy-of-first-question-by-condition"><span class="header-section-number">4.1.1</span> Response Accuracy of First Question by Condition</h3>
<section id="chi-square-accuracy-condition" class="level4" data-number="4.1.1.1">
<h4 data-number="4.1.1.1" class="anchored" data-anchor-id="chi-square-accuracy-condition"><span class="header-section-number">4.1.1.1</span> Chi Square | Accuracy ~ Condition</h4>
<table class="table">
<colgroup>
<col style="width: 4%">
<col style="width: 95%">
</colgroup>
<thead>
<tr class="header">
<th>Research Question</th>
<th>Does the frequency of correct (vs) incorrect responses on the first question differ by condition? [Is response accuracy independent of condition?]</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Analysis Strategy</strong></td>
<td>Chi-Square test of independence on outcome <code>score_niceABS</code> by <code>condition</code> for <code>df_items</code> where <code>q == 1</code></td>
</tr>
<tr class="even">
<td><strong>Justification</strong></td>
<td><p>(0) simplest method to examine independence of two categorical factors; logistic regression is recommended for binomial ~ continuous</p>
<p>(1) independence assumption : as we only consider responses on the first question, each observation corresponds to an individual subject, and are thus independent</p>
<p>(2) frequency size assumption : expected frequency in each cell of the contingency table is greater than 5 (more than 5 correct , more than 5 incorrect responses)</p></td>
</tr>
<tr class="odd">
<td><strong>Steps</strong></td>
<td><p>(1) Express raw data as contingency table &amp; visualize</p>
<p>(2) Calculate Chi-Squared Statistic and p-value</p>
<p>(3) Interpret Odds-Ratio as effect size</p></td>
</tr>
<tr class="even">
<td><strong>Inference</strong></td>
<td><p><strong>Lab</strong> For the in-lab data collection (n=126) the Pearson’s Chi-squared test (of independence) indicates a relationship between response accuracy on the first question and experimental condition approaching statistical significance, <span class="math inline">\(\chi^2\)</span> (1) = 10.3, p = 0.07. In this particular data sample, the odds ratio (2.18, p = 0.055, 95% CI [0.982, +Inf]) indicates that the odds of producing a correct response on the first question were 2.18 times greater if a subject was in the impasse condition, than in the control condition.</p>
<p><strong>Online</strong> For online data collection (n=204), a Pearson’s Chi-squared test (of independence) indicates a statistically significant relationship between response accuracy on the first question and experimental condition, <span class="math inline">\(\chi^2\)</span> (1) = 7.26, p = 0.009. The odds ratio (2.68, p = 0.005, 95% CI [1.37, +Inf]) indicates that the odds of producing a correct response on the first question were 2.68 times greater if a subject was in the impasse condition, than in the control condition.</p></td>
</tr>
</tbody>
</table>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#FITER THE DATASET</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">=</span> df_items <span class="sc">%&gt;%</span> <span class="fu">filter</span>(q<span class="sc">==</span><span class="dv">1</span>) </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co">#PROPORTIONAL BAR CHART</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_props</span>(<span class="sc">~</span>score_niceABS, <span class="at">data =</span> df, <span class="at">fill =</span> <span class="sc">~</span>mode) <span class="sc">%&gt;%</span> </span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_facet_grid</span>(mode<span class="sc">~</span>condition, <span class="at">labeller =</span> label_both) <span class="sc">+</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Correct Response on Q 1"</span>,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Accuracy on First Question by Condition (Both Modalities)"</span>,</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle=</span><span class="st">"Impasse Condition yields a greater proportion of correct responses than control "</span>)<span class="sc">+</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()<span class="sc">+</span> <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="4_sgc3A_hypotesting_files/figure-html/VIS-Q1ACC.by.COND-bar-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>A proportional bar chart visualizing the proportion of incorrect (x =0) vs correct (x = 1) responses in each condition (right/left facet) for each data collection modality (top/bottom) reveal that the pattern of responses appear the same regardless of the data collection modality. In both data collection sessions, the proportion of incorrect responses is much greater than the proportion of correct responses, regardless of condition. In the impasse condition, the difference in proportions is smaller than the control condition (i.e.&nbsp;There are more correct responses in the impasse condition than the control condition).</p>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#MOSAIC PLOT</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>vcd<span class="sc">::</span><span class="fu">mosaic</span>(<span class="at">main=</span><span class="st">"Accuracy on First Question by Condition (Both Modalities)"</span>,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> df, score_niceABS <span class="sc">~</span> condition, <span class="at">rot_labels=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">90</span>,<span class="dv">0</span>,<span class="dv">0</span>),</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">offset_varnames =</span> <span class="fu">c</span>(<span class="at">left =</span> <span class="fl">4.5</span>), <span class="at">offset_labels =</span> <span class="fu">c</span>(<span class="at">left =</span> <span class="sc">-</span><span class="fl">0.5</span>),<span class="at">just_labels =</span> <span class="st">"right"</span>,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">spacing =</span> <span class="fu">spacing_dimequal</span>(<span class="fu">unit</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="st">"lines"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="4_sgc3A_hypotesting_files/figure-html/VIS-Q1ACC.by.COND-mosaic-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#PRINT CONTINGENCY TABLE</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>title <span class="ot">=</span> <span class="st">"Proportion of Correct Responses On First Item (Both Modalities)"</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>item.contingency <span class="ot">&lt;-</span>  df <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(condition, score_niceABS) <span class="sc">%&gt;%</span> <span class="fu">table</span>() <span class="sc">%&gt;%</span> <span class="fu">prop.table</span>() <span class="sc">%&gt;%</span> <span class="fu">addmargins</span>()</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>item.contingency <span class="sc">%&gt;%</span> <span class="fu">kbl</span> (<span class="at">caption =</span> title) <span class="sc">%&gt;%</span> <span class="fu">kable_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class=" lightable-classic" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; margin-left: auto; margin-right: auto;">
<caption>Proportion of Correct Responses On First Item (Both Modalities)</caption>
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:right;"> 0 </th>
   <th style="text-align:right;"> 1 </th>
   <th style="text-align:right;"> Sum </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 111 </td>
   <td style="text-align:right;"> 0.412 </td>
   <td style="text-align:right;"> 0.067 </td>
   <td style="text-align:right;"> 0.479 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 121 </td>
   <td style="text-align:right;"> 0.373 </td>
   <td style="text-align:right;"> 0.148 </td>
   <td style="text-align:right;"> 0.521 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Sum </td>
   <td style="text-align:right;"> 0.785 </td>
   <td style="text-align:right;"> 0.215 </td>
   <td style="text-align:right;"> 1.000 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>A mosaic plot condition by response accuracy on the first question (across both data collection modalities) reveals the same pattern (the mosaic plot is an alternative visualization technique to the proportional bar chart). The relative size of condition boxes (111 vs 121) reflects that the sample is roughly evenly split across experimental conditions. The difference in size between 0 (incorrect) and 1 (correct) reflects that the proportion of correct responses (1) is greater in the impasse condition (121).</p>
<p>Next, we compute a contingency table and Pearson’s Chi-Squared test for each data collection modality.</p>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">=</span> df_items <span class="sc">%&gt;%</span> <span class="fu">filter</span>(q<span class="sc">==</span><span class="dv">1</span>) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(mode <span class="sc">==</span> <span class="st">"lab-synch"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">CrossTable</span>( <span class="at">x =</span> df<span class="sc">$</span>condition, <span class="at">y =</span> df<span class="sc">$</span>score_niceABS, <span class="at">fisher =</span> <span class="cn">TRUE</span>, <span class="at">chisq=</span><span class="cn">TRUE</span>, <span class="at">expected =</span> <span class="cn">TRUE</span>, <span class="at">sresid =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
 
   Cell Contents
|-------------------------|
|                       N |
|              Expected N |
| Chi-square contribution |
|           N / Row Total |
|           N / Col Total |
|         N / Table Total |
|-------------------------|

 
Total Observations in Table:  126 

 
             | df$score_niceABS 
df$condition |         0 |         1 | Row Total | 
-------------|-----------|-----------|-----------|
         111 |        52 |        10 |        62 | 
             |    47.730 |    14.270 |           | 
             |     0.382 |     1.278 |           | 
             |     0.839 |     0.161 |     0.492 | 
             |     0.536 |     0.345 |           | 
             |     0.413 |     0.079 |           | 
-------------|-----------|-----------|-----------|
         121 |        45 |        19 |        64 | 
             |    49.270 |    14.730 |           | 
             |     0.370 |     1.238 |           | 
             |     0.703 |     0.297 |     0.508 | 
             |     0.464 |     0.655 |           | 
             |     0.357 |     0.151 |           | 
-------------|-----------|-----------|-----------|
Column Total |        97 |        29 |       126 | 
             |     0.770 |     0.230 |           | 
-------------|-----------|-----------|-----------|

 
Statistics for All Table Factors


Pearson's Chi-squared test 
------------------------------------------------------------
Chi^2 =  3.27     d.f. =  1     p =  0.0707 

Pearson's Chi-squared test with Yates' continuity correction 
------------------------------------------------------------
Chi^2 =  2.55     d.f. =  1     p =  0.111 

 
Fisher's Exact Test for Count Data
------------------------------------------------------------
Sample estimate odds ratio:  2.18 

Alternative hypothesis: true odds ratio is not equal to 1
p =  0.0909 
95% confidence interval:  0.86 5.84 

Alternative hypothesis: true odds ratio is less than 1
p =  0.979 
95% confidence interval:  0 5.03 

Alternative hypothesis: true odds ratio is greater than 1
p =  0.0547 
95% confidence interval:  0.982 Inf 


 </code></pre>
</div>
</div>
<p><strong>For the in-lab data collection</strong> (n=126) the Pearson’s Chi-squared test (of independence) indicates a relationship between response accuracy on the first question and experimental condition approaching statistical significance, <span class="math inline">\(\chi^2\)</span> (1) = 10.3, p = 0.07. Thus we have insufficient evidence to reject the null hypothesis that the odds ratio is equal to 1. In this particular data sample, the odds ratio (Odds Ratio = 2.18, p = 0.055, 95% CI [0.982, +Inf]) indicates that the odds of producing a correct response on the first question were 2.18 times greater if a subject was in the impasse condition, than in the control condition .</p>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">=</span> df_items <span class="sc">%&gt;%</span> <span class="fu">filter</span>(q<span class="sc">==</span><span class="dv">1</span>) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(mode <span class="sc">==</span> <span class="st">"asynch"</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">CrossTable</span>( <span class="at">x =</span> df<span class="sc">$</span>condition, <span class="at">y =</span> df<span class="sc">$</span>score_niceABS, <span class="at">fisher =</span> <span class="cn">TRUE</span>, <span class="at">chisq=</span><span class="cn">TRUE</span>, <span class="at">expected =</span> <span class="cn">TRUE</span>, <span class="at">sresid =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
 
   Cell Contents
|-------------------------|
|                       N |
|              Expected N |
| Chi-square contribution |
|           N / Row Total |
|           N / Col Total |
|         N / Table Total |
|-------------------------|

 
Total Observations in Table:  204 

 
             | df$score_niceABS 
df$condition |         0 |         1 | Row Total | 
-------------|-----------|-----------|-----------|
         111 |        84 |        12 |        96 | 
             |    76.235 |    19.765 |           | 
             |     0.791 |     3.050 |           | 
             |     0.875 |     0.125 |     0.471 | 
             |     0.519 |     0.286 |           | 
             |     0.412 |     0.059 |           | 
-------------|-----------|-----------|-----------|
         121 |        78 |        30 |       108 | 
             |    85.765 |    22.235 |           | 
             |     0.703 |     2.711 |           | 
             |     0.722 |     0.278 |     0.529 | 
             |     0.481 |     0.714 |           | 
             |     0.382 |     0.147 |           | 
-------------|-----------|-----------|-----------|
Column Total |       162 |        42 |       204 | 
             |     0.794 |     0.206 |           | 
-------------|-----------|-----------|-----------|

 
Statistics for All Table Factors


Pearson's Chi-squared test 
------------------------------------------------------------
Chi^2 =  7.26     d.f. =  1     p =  0.00707 

Pearson's Chi-squared test with Yates' continuity correction 
------------------------------------------------------------
Chi^2 =  6.35     d.f. =  1     p =  0.0117 

 
Fisher's Exact Test for Count Data
------------------------------------------------------------
Sample estimate odds ratio:  2.68 

Alternative hypothesis: true odds ratio is not equal to 1
p =  0.00894 
95% confidence interval:  1.23 6.17 

Alternative hypothesis: true odds ratio is less than 1
p =  0.998 
95% confidence interval:  0 5.42 

Alternative hypothesis: true odds ratio is greater than 1
p =  0.00539 
95% confidence interval:  1.37 Inf 


 </code></pre>
</div>
</div>
<p><strong>For online data collection</strong> (n=204), a Pearson’s Chi-squared test (of independence) indicates a statistically significant relationship between response accuracy on the first question and experimental condition, <span class="math inline">\(\chi^2\)</span> (1) = 7.26, p = 0.009. Thus we have sufficient evidence to reject the null hypothesis that the odds ratio is equal to 1. The odds ratio (Odds Ratio = 2.68, p = 0.005, 95% CI [1.37, +Inf]) indicates that the odds of producing a correct response on the first question were 2.68 times greater if a subject was in the impasse condition, than in the control condition .</p>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">=</span> df_items <span class="sc">%&gt;%</span> <span class="fu">filter</span>(q<span class="sc">==</span><span class="dv">1</span>) </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">CrossTable</span>( <span class="at">x =</span> df<span class="sc">$</span>condition, <span class="at">y =</span> df<span class="sc">$</span>score_niceABS, <span class="at">fisher =</span> <span class="cn">TRUE</span>, <span class="at">chisq=</span><span class="cn">TRUE</span>, <span class="at">expected =</span> <span class="cn">TRUE</span>, <span class="at">sresid =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
 
   Cell Contents
|-------------------------|
|                       N |
|              Expected N |
| Chi-square contribution |
|           N / Row Total |
|           N / Col Total |
|         N / Table Total |
|-------------------------|

 
Total Observations in Table:  330 

 
             | df$score_niceABS 
df$condition |         0 |         1 | Row Total | 
-------------|-----------|-----------|-----------|
         111 |       136 |        22 |       158 | 
             |   124.006 |    33.994 |           | 
             |     1.160 |     4.232 |           | 
             |     0.861 |     0.139 |     0.479 | 
             |     0.525 |     0.310 |           | 
             |     0.412 |     0.067 |           | 
-------------|-----------|-----------|-----------|
         121 |       123 |        49 |       172 | 
             |   134.994 |    37.006 |           | 
             |     1.066 |     3.887 |           | 
             |     0.715 |     0.285 |     0.521 | 
             |     0.475 |     0.690 |           | 
             |     0.373 |     0.148 |           | 
-------------|-----------|-----------|-----------|
Column Total |       259 |        71 |       330 | 
             |     0.785 |     0.215 |           | 
-------------|-----------|-----------|-----------|

 
Statistics for All Table Factors


Pearson's Chi-squared test 
------------------------------------------------------------
Chi^2 =  10.3     d.f. =  1     p =  0.0013 

Pearson's Chi-squared test with Yates' continuity correction 
------------------------------------------------------------
Chi^2 =  9.5     d.f. =  1     p =  0.00205 

 
Fisher's Exact Test for Count Data
------------------------------------------------------------
Sample estimate odds ratio:  2.46 

Alternative hypothesis: true odds ratio is not equal to 1
p =  0.00131 
95% confidence interval:  1.37 4.53 

Alternative hypothesis: true odds ratio is less than 1
p =  1 
95% confidence interval:  0 4.12 

Alternative hypothesis: true odds ratio is greater than 1
p =  0.000928 
95% confidence interval:  1.49 Inf 


 </code></pre>
</div>
</div>
<p><strong>Combining data across both sessions</strong> (n=330), a Pearson’s Chi-squared test suggests a statistically significant relationship between response accuracy on the first question and experimental condition, <span class="math inline">\(\chi_2\)</span> (1) = 10.3, p = 0.001. The sample odds ratio (2.46, p = 0.001, 95% CI [1.37, 4.53]) indicates that the odds of providing a correct response to the first question are 2.46 higher for subjects in the impasse condition than those in the control condition.</p>
</section>
</section>
</section>
<section id="cumulative-performance" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="cumulative-performance"><span class="header-section-number">4.2</span> CUMULATIVE PERFORMANCE</h2>
<p><em>Overall</em> does the impasse condition affect performance on the graph comprehension task?</p>
<section id="cumulative-score-by-condition" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="cumulative-score-by-condition"><span class="header-section-number">4.2.1</span> Cumulative Score By Condition</h3>
<p>Cumulative scores indicate the response accuracy by a particular participant across all discriminant items (n=13) in the graph comprehension task.</p>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#VISUALIZE distribution of response accuracy across SUBJECTS</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co">#HISTOGRAM</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>stats <span class="ot">=</span> df_subjects <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(condition, mode) <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(s_ABS))</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_density</span>(<span class="sc">~</span>s_ABS, <span class="at">data =</span> df_subjects) <span class="sc">%&gt;%</span> </span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_facet_grid</span>(condition<span class="sc">~</span>mode, <span class="at">labeller =</span> label_both) <span class="sc">%&gt;%</span> </span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_lims</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">13</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_vline</span>(<span class="at">data =</span> stats, <span class="at">xintercept =</span> <span class="sc">~</span>mean, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Cumulative Absolute Score"</span>,</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"proportion of subjects"</span>,</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Subject Cumulative Score (Absolute)"</span>,</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Score distributions are comparable across modalities and different across conditions"</span>) <span class="sc">+</span> </span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="4_sgc3A_hypotesting_files/figure-html/VIS-SUBJECT-ABS-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Does the IMPASSE condition yield higher scores?</strong></p>
<section id="linear-regression" class="level4" data-number="4.2.1.1">
<h4 data-number="4.2.1.1" class="anchored" data-anchor-id="linear-regression"><span class="header-section-number">4.2.1.1</span> Linear Regression</h4>
<p>To address this question we assess how much variance in cumulative (absolute) score is explained by experimental condition by utilizing OLS linear regression, predicting absolute score from condition.</p>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#SCORE predicted by CONDITION</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(s_ABS <span class="sc">~</span> condition, <span class="at">data =</span> df_subjects <span class="sc">%&gt;%</span> <span class="fu">filter</span>(mode<span class="sc">==</span><span class="st">"lab-synch"</span>))</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Model"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Model"</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = s_ABS ~ condition, data = df_subjects %&gt;% filter(mode == 
    "lab-synch"))

Residuals:
   Min     1Q Median     3Q    Max 
 -5.44  -2.68  -2.68   4.31  10.32 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     2.677      0.620    4.32 0.000031 ***
condition121    2.760      0.869    3.17   0.0019 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.88 on 124 degrees of freedom
Multiple R-squared:  0.0752,    Adjusted R-squared:  0.0677 
F-statistic: 10.1 on 1 and 124 DF,  p-value: 0.00189</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Partition Variance"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Partition Variance"</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: s_ABS
           Df Sum Sq Mean Sq F value Pr(&gt;F)   
condition   1    240   239.9    10.1 0.0019 **
Residuals 124   2951    23.8                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Confidence Interval on Parameter Estimates"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Confidence Interval on Parameter Estimates"</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             2.5 % 97.5 %
(Intercept)   1.45   3.90
condition121  1.04   4.48</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># report(m1) #sanity check</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><strong>For in-lab data collection</strong> an OLS linear regression predicting cumulative absolute score by experimental condition explains a statistically significant though small 7.5% variance in score (F(1,124) = 10.1, p &lt; 0.01). The estimated beta coefficient (<span class="math inline">\(/beta\)</span> = 2.76, 95% CI [1.04, 4.48]) predicts that participants in the impasse condition will on average score 2.76 points (21%) higher than those in the control condition.</p>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#SCORE predicted by CONDITION</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(s_ABS <span class="sc">~</span> condition, <span class="at">data =</span> df_subjects <span class="sc">%&gt;%</span> <span class="fu">filter</span>(mode<span class="sc">==</span><span class="st">"asynch"</span>))</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Model"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Model"</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = s_ABS ~ condition, data = df_subjects %&gt;% filter(mode == 
    "asynch"))

Residuals:
   Min     1Q Median     3Q    Max 
 -4.58  -3.58  -2.30   3.42  10.70 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     2.302      0.485    4.75  3.8e-06 ***
condition121    2.281      0.666    3.43  0.00074 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.75 on 202 degrees of freedom
Multiple R-squared:  0.0549,    Adjusted R-squared:  0.0502 
F-statistic: 11.7 on 1 and 202 DF,  p-value: 0.000745</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Partition Variance"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Partition Variance"</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: s_ABS
           Df Sum Sq Mean Sq F value  Pr(&gt;F)    
condition   1    264   264.5    11.7 0.00074 ***
Residuals 202   4554    22.5                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Confidence Interval on Parameter Estimates"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Confidence Interval on Parameter Estimates"</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             2.5 % 97.5 %
(Intercept)  1.347   3.26
condition121 0.968   3.59</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">#report(m1) #sanity check</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><strong>For the online replication</strong>, an OLS linear regression model predicting cumulative absolute score by condition explains a statistically significant though small 5.5% of variance in absolute score (F(1,202) = 11.73, p &lt; 0.001). The beta coefficient for condition indicates that on average, participants in the IMPASSE group scored 2.3 points higher on the task than those in the control condition (CI[0.97, 3.59]).</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>From these models we can reasonably conclude that the impasse condition yielded a small but reliable improvement in performance across items in the graph reading task.</strong></p>
</div>
</div>
<p><strong>Model Diagnostics</strong></p>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="4_sgc3A_hypotesting_files/figure-html/DIAGNOSTICS-ABSCORE-LINEAR-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="poisson-regression" class="level4" data-number="4.2.1.2">
<h4 data-number="4.2.1.2" class="anchored" data-anchor-id="poisson-regression"><span class="header-section-number">4.2.1.2</span> Poisson Regression</h4>
<p>The outcome variable absolute score is clearly not normal. As it represents the cumulative number of items a participant has answered correctly, we can consider it a type of <em>count</em>, (ie. count of the number of questions the participant got correct) and attempt to model it using a General Linear Model with the Poisson distribution (and the default log-link function).</p>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># library('fitdistrplus')</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="co"># plot(fitdist(df_subjects$s_ABS,"pois"))</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="co"># plot(fitdist(df_subjects$s_ABS,"norm"))</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="co"># plot(fitdist(df_subjects$s_ABS,"beta"))</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a><span class="co"># plotdist(df_subjects$s_ABS, histo = TRUE, demp = TRUE)</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a><span class="co"># descdist(df_subjects$s_ABS, discrete=FALSE, boot=500)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co">#SCORE predicted by CONDITION --&gt; POISSON DISTRIBUTION</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>mp1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(s_ABS <span class="sc">~</span> condition, <span class="at">data =</span> df_subjects <span class="sc">%&gt;%</span> <span class="fu">filter</span>(mode<span class="sc">==</span><span class="st">"lab-synch"</span>), <span class="at">family =</span> <span class="st">"poisson"</span>)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Model"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Model"</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mp1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = s_ABS ~ condition, family = "poisson", data = df_subjects %&gt;% 
    filter(mode == "lab-synch"))

Deviance Residuals: 
   Min      1Q  Median      3Q     Max  
 -3.30   -2.31   -2.31    1.75    4.52  

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)    0.9849     0.0776   12.69  &lt; 2e-16 ***
condition121   0.7085     0.0943    7.51  5.9e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 855.68  on 125  degrees of freedom
Residual deviance: 795.46  on 124  degrees of freedom
AIC: 1045

Number of Fisher Scoring iterations: 6</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Partition Variance"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Partition Variance"</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mp1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model: poisson, link: log

Response: s_ABS

Terms added sequentially (first to last)

          Df Deviance Resid. Df Resid. Dev
NULL                        125        856
condition  1     60.2       124        795</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Confidence Interval on Parameter Estimates"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Confidence Interval on Parameter Estimates"</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mp1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>             2.5 % 97.5 %
(Intercept)  0.829  1.133
condition121 0.525  0.896</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(mp1) <span class="co">#sanity check</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>We fitted a poisson model (estimated using ML) to predict s_ABS with condition (formula: s_ABS ~ condition). The model's explanatory power is substantial (Nagelkerke's R2 = 0.38). The model's intercept, corresponding to condition = 111, is at 0.98 (95% CI [0.83, 1.13], p &lt; .001). Within this model:

  - The effect of condition [121] is statistically significant and positive (beta = 0.71, 95% CI [0.53, 0.90], p &lt; .001; Std. beta = 0.71, 95% CI [0.53, 0.90])

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using </code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(mp1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="4_sgc3A_hypotesting_files/figure-html/DIAGNOSTICS-ABSCORE-POISSON-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Which is a better fit? linear or poisson?</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="fu">compare_performance</span>(m1,mp1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: When comparing models, please note that probably not all models were fit from
  same data.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># Comparison of Model Performance Indices

Name | Model |      AIC | AIC weights |      BIC | BIC weights |  RMSE | Sigma |    R2 | R2 (adj.) | Nagelkerke's R2 | Score_log | Score_spherical
--------------------------------------------------------------------------------------------------------------------------------------------------
m1   |    lm | 1218.500 |     &lt; 0.001 | 1228.454 |     &lt; 0.001 | 4.725 | 4.748 | 0.055 |     0.050 |                 |           |                
mp1  |   glm | 1044.751 |        1.00 | 1050.423 |        1.00 | 4.840 | 2.533 |       |           |           0.380 |    -4.130 |           0.063</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="resources" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="resources"><span class="header-section-number">4.3</span> RESOURCES</h2>
<ul>
<li>https://rpkgs.datanovia.com/ggpubr/reference/index.html</li>
</ul>


<!-- -->

</section>

</main> <!-- /main -->
<script type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../analysis/SGC3A/3_sgc3A_description.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Description</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../analysis/SGC3A/5_sgc3A_exploration.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Exploratory Analyses</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb60" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> 'Study SGC3A | 4 Hypothesis Testing'</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>\newpage</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a><span class="fu"># Hypothesis Testing {#sec-SGC3A-hypotesting}</span></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a>**TODO**\</span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>clarify core questions being asked</span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>update SGC3A main based on hypothesis organization</span>
<span id="cb60-13"><a href="#cb60-13" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>decision table for cummulative performance</span>
<span id="cb60-14"><a href="#cb60-14" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>review models already created in ARCHIVE?</span>
<span id="cb60-15"><a href="#cb60-15" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>explore response consistency</span>
<span id="cb60-16"><a href="#cb60-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-19"><a href="#cb60-19" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb60-20"><a href="#cb60-20" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: SETUP</span></span>
<span id="cb60-21"><a href="#cb60-21" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning : false</span></span>
<span id="cb60-22"><a href="#cb60-22" aria-hidden="true" tabindex="-1"></a><span class="co">#| message : false</span></span>
<span id="cb60-23"><a href="#cb60-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-24"><a href="#cb60-24" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co">#ALL THE THINGS</span></span>
<span id="cb60-25"><a href="#cb60-25" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Hmisc) <span class="co"># %nin% operator</span></span>
<span id="cb60-26"><a href="#cb60-26" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr) <span class="co">#arrange plots</span></span>
<span id="cb60-27"><a href="#cb60-27" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggformula) <span class="co">#easy graphs</span></span>
<span id="cb60-28"><a href="#cb60-28" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(report) <span class="co">#easystats reporting</span></span>
<span id="cb60-29"><a href="#cb60-29" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(see) <span class="co">#easystats visualization</span></span>
<span id="cb60-30"><a href="#cb60-30" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance) <span class="co">#easystats model diagnostics</span></span>
<span id="cb60-31"><a href="#cb60-31" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gmodels) <span class="co">#contingency table and CHISQR</span></span>
<span id="cb60-32"><a href="#cb60-32" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vcd) <span class="co">#mosaic plots</span></span>
<span id="cb60-33"><a href="#cb60-33" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vcdExtra) <span class="co">#mosaic plots</span></span>
<span id="cb60-34"><a href="#cb60-34" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra) <span class="co">#printing tables </span></span>
<span id="cb60-35"><a href="#cb60-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-36"><a href="#cb60-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-37"><a href="#cb60-37" aria-hidden="true" tabindex="-1"></a><span class="co">#set some output options</span></span>
<span id="cb60-38"><a href="#cb60-38" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>)</span>
<span id="cb60-39"><a href="#cb60-39" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">dplyr.summarise.inform =</span> <span class="cn">FALSE</span>)</span>
<span id="cb60-40"><a href="#cb60-40" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">ggplot2.summarise.inform =</span> <span class="cn">FALSE</span>)</span>
<span id="cb60-41"><a href="#cb60-41" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen=</span><span class="dv">1</span>, <span class="at">digits=</span><span class="dv">3</span>)</span>
<span id="cb60-42"><a href="#cb60-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-43"><a href="#cb60-43" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb60-44"><a href="#cb60-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-45"><a href="#cb60-45" aria-hidden="true" tabindex="-1"></a>*The purpose of this notebook is test the hypotheses that determined the design of the SGC3A study.*</span>
<span id="cb60-46"><a href="#cb60-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-47"><a href="#cb60-47" aria-hidden="true" tabindex="-1"></a>+------------------------+</span>
<span id="cb60-48"><a href="#cb60-48" aria-hidden="true" tabindex="-1"></a>| Pre-Requisite          |</span>
<span id="cb60-49"><a href="#cb60-49" aria-hidden="true" tabindex="-1"></a>+========================+</span>
<span id="cb60-50"><a href="#cb60-50" aria-hidden="true" tabindex="-1"></a>| 1_sgc3A_harmonize.qmd\ |</span>
<span id="cb60-51"><a href="#cb60-51" aria-hidden="true" tabindex="-1"></a>| 2_sgc3A_scoring.qmd    |</span>
<span id="cb60-52"><a href="#cb60-52" aria-hidden="true" tabindex="-1"></a>+------------------------+</span>
<span id="cb60-53"><a href="#cb60-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-56"><a href="#cb60-56" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb60-57"><a href="#cb60-57" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: IMPORT-DATA</span></span>
<span id="cb60-58"><a href="#cb60-58" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo : true</span></span>
<span id="cb60-59"><a href="#cb60-59" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning : false</span></span>
<span id="cb60-60"><a href="#cb60-60" aria-hidden="true" tabindex="-1"></a><span class="co">#| message : false</span></span>
<span id="cb60-61"><a href="#cb60-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-62"><a href="#cb60-62" aria-hidden="true" tabindex="-1"></a><span class="co">#IMPORT DATA </span></span>
<span id="cb60-63"><a href="#cb60-63" aria-hidden="true" tabindex="-1"></a>df_items <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">'data/2-scored-data/sgc3a_scored_items.rds'</span>)</span>
<span id="cb60-64"><a href="#cb60-64" aria-hidden="true" tabindex="-1"></a>df_subjects <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">'data/2-scored-data/sgc3a_scored_participants.rds'</span>)</span>
<span id="cb60-65"><a href="#cb60-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-66"><a href="#cb60-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-67"><a href="#cb60-67" aria-hidden="true" tabindex="-1"></a><span class="co">#SEPARATE ITEM DATA BY QUESTION TYPE</span></span>
<span id="cb60-68"><a href="#cb60-68" aria-hidden="true" tabindex="-1"></a>df_scaffold <span class="ot">&lt;-</span> df_items <span class="sc">%&gt;%</span> <span class="fu">filter</span>(q <span class="sc">&lt;</span> <span class="dv">6</span>)</span>
<span id="cb60-69"><a href="#cb60-69" aria-hidden="true" tabindex="-1"></a>df_test <span class="ot">&lt;-</span> df_items <span class="sc">%&gt;%</span> <span class="fu">filter</span>(q <span class="sc">&gt;</span> <span class="dv">6</span>) <span class="sc">%&gt;%</span> <span class="fu">filter</span> (q <span class="sc">%nin%</span> <span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">9</span>))</span>
<span id="cb60-70"><a href="#cb60-70" aria-hidden="true" tabindex="-1"></a>df_nondiscrim <span class="ot">&lt;-</span> df_items <span class="sc">%&gt;%</span> <span class="fu">filter</span> (q <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">9</span>))</span>
<span id="cb60-71"><a href="#cb60-71" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb60-72"><a href="#cb60-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-73"><a href="#cb60-73" aria-hidden="true" tabindex="-1"></a>There are x questions we aim to answer :</span>
<span id="cb60-74"><a href="#cb60-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-75"><a href="#cb60-75" aria-hidden="true" tabindex="-1"></a><span class="sc">\(</span>1<span class="sc">\)</span> Does the experimental condition yield significantly better performance on the first question?</span>
<span id="cb60-76"><a href="#cb60-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-77"><a href="#cb60-77" aria-hidden="true" tabindex="-1"></a><span class="sc">\(</span>2<span class="sc">\)</span> Does the experimental condition yield significantly better performance overall?</span>
<span id="cb60-78"><a href="#cb60-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-79"><a href="#cb60-79" aria-hidden="true" tabindex="-1"></a><span class="fu">## INITIAL PERFORMANCE</span></span>
<span id="cb60-80"><a href="#cb60-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-81"><a href="#cb60-81" aria-hidden="true" tabindex="-1"></a>The graph comprehension tasks includes 15 questions completed in sequence. But the first question the reader encounters (Q1) is the most important, as it is their *first exposure* to the unconventional triangular coordinate system.</span>
<span id="cb60-82"><a href="#cb60-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-83"><a href="#cb60-83" aria-hidden="true" tabindex="-1"></a>TODO: - does impasse yield different exploration behavior? (characterize mouse) - does impasse yield more time on task? (characterize response time ? number of answers then de-selected?)</span>
<span id="cb60-84"><a href="#cb60-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-85"><a href="#cb60-85" aria-hidden="true" tabindex="-1"></a>TODO: Think about characterizing how variable the interpretations are across a participant. Do they form an interpretation and hold it constant? Or do they change question to question.</span>
<span id="cb60-86"><a href="#cb60-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-87"><a href="#cb60-87" aria-hidden="true" tabindex="-1"></a><span class="fu">### Response Accuracy of First Question by Condition</span></span>
<span id="cb60-88"><a href="#cb60-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-89"><a href="#cb60-89" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Chi Square \| Accuracy \~ Condition</span></span>
<span id="cb60-90"><a href="#cb60-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-91"><a href="#cb60-91" aria-hidden="true" tabindex="-1"></a>+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+</span>
<span id="cb60-92"><a href="#cb60-92" aria-hidden="true" tabindex="-1"></a>| Research Question     | Does the frequency of correct (vs) incorrect responses on the first question differ by condition? <span class="sc">\[</span>Is response accuracy independent of condition?<span class="sc">\]</span>                                                                                                                                                                                                                                                                                                                                                                                              |</span>
<span id="cb60-93"><a href="#cb60-93" aria-hidden="true" tabindex="-1"></a>+=======================+===================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================+</span>
<span id="cb60-94"><a href="#cb60-94" aria-hidden="true" tabindex="-1"></a>| **Analysis Strategy** | Chi-Square test of independence on outcome <span class="in">`score_niceABS`</span> by <span class="in">`condition`</span> for <span class="in">`df_items`</span> where <span class="in">`q == 1`</span>                                                                                                                                                                                                                                                                                                                                                                                                                                           |</span>
<span id="cb60-95"><a href="#cb60-95" aria-hidden="true" tabindex="-1"></a>+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+</span>
<span id="cb60-96"><a href="#cb60-96" aria-hidden="true" tabindex="-1"></a>| **Justification**     | <span class="sc">\(</span>0<span class="sc">\)</span> simplest method to examine independence of two categorical factors; logistic regression is recommended for binomial \~ continuous                                                                                                                                                                                                                                                                                                                                                                                                           |</span>
<span id="cb60-97"><a href="#cb60-97" aria-hidden="true" tabindex="-1"></a>|                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |</span>
<span id="cb60-98"><a href="#cb60-98" aria-hidden="true" tabindex="-1"></a>|                       | <span class="sc">\(</span>1<span class="sc">\)</span> independence assumption : as we only consider responses on the first question, each observation corresponds to an individual subject, and are thus independent                                                                                                                                                                                                                                                                                                                                                                              |</span>
<span id="cb60-99"><a href="#cb60-99" aria-hidden="true" tabindex="-1"></a>|                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |</span>
<span id="cb60-100"><a href="#cb60-100" aria-hidden="true" tabindex="-1"></a>|                       | <span class="sc">\(</span>2<span class="sc">\)</span> frequency size assumption : expected frequency in each cell of the contingency table is greater than 5 (more than 5 correct , more than 5 incorrect responses)                                                                                                                                                                                                                                                                                                                                                                              |</span>
<span id="cb60-101"><a href="#cb60-101" aria-hidden="true" tabindex="-1"></a>+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+</span>
<span id="cb60-102"><a href="#cb60-102" aria-hidden="true" tabindex="-1"></a>| **Steps**             | <span class="sc">\(</span>1<span class="sc">\)</span> Express raw data as contingency table &amp; visualize                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |</span>
<span id="cb60-103"><a href="#cb60-103" aria-hidden="true" tabindex="-1"></a>|                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |</span>
<span id="cb60-104"><a href="#cb60-104" aria-hidden="true" tabindex="-1"></a>|                       | <span class="sc">\(</span>2<span class="sc">\)</span> Calculate Chi-Squared Statistic and p-value                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |</span>
<span id="cb60-105"><a href="#cb60-105" aria-hidden="true" tabindex="-1"></a>|                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |</span>
<span id="cb60-106"><a href="#cb60-106" aria-hidden="true" tabindex="-1"></a>|                       | <span class="sc">\(</span>3<span class="sc">\)</span> Interpret Odds-Ratio as effect size                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |</span>
<span id="cb60-107"><a href="#cb60-107" aria-hidden="true" tabindex="-1"></a>+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+</span>
<span id="cb60-108"><a href="#cb60-108" aria-hidden="true" tabindex="-1"></a>| **Inference**         | **Lab** For the in-lab data collection (n=126) the Pearson's Chi-squared test (of independence) indicates a relationship between response accuracy on the first question and experimental condition approaching statistical significance, $\chi^2$ (1) = 10.3, p = 0.07. In this particular data sample, the odds ratio (2.18, p = 0.055, 95% CI <span class="sc">\[</span>0.982, +Inf<span class="sc">\]</span>) indicates that the odds of producing a correct response on the first question were 2.18 times greater if a subject was in the impasse condition, than in the control condition. |</span>
<span id="cb60-109"><a href="#cb60-109" aria-hidden="true" tabindex="-1"></a>|                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |</span>
<span id="cb60-110"><a href="#cb60-110" aria-hidden="true" tabindex="-1"></a>|                       | **Online** For online data collection (n=204), a Pearson's Chi-squared test (of independence) indicates a statistically significant relationship between response accuracy on the first question and experimental condition, $\chi^2$ (1) = 7.26, p = 0.009. The odds ratio (2.68, p = 0.005, 95% CI <span class="sc">\[</span>1.37, +Inf<span class="sc">\]</span>) indicates that the odds of producing a correct response on the first question were 2.68 times greater if a subject was in the impasse condition, than in the control condition.                                              |</span>
<span id="cb60-111"><a href="#cb60-111" aria-hidden="true" tabindex="-1"></a>+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+</span>
<span id="cb60-112"><a href="#cb60-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-115"><a href="#cb60-115" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb60-116"><a href="#cb60-116" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: VIS-Q1ACC.by.COND-bar</span></span>
<span id="cb60-117"><a href="#cb60-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-118"><a href="#cb60-118" aria-hidden="true" tabindex="-1"></a><span class="co">#FITER THE DATASET</span></span>
<span id="cb60-119"><a href="#cb60-119" aria-hidden="true" tabindex="-1"></a>df <span class="ot">=</span> df_items <span class="sc">%&gt;%</span> <span class="fu">filter</span>(q<span class="sc">==</span><span class="dv">1</span>) </span>
<span id="cb60-120"><a href="#cb60-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-121"><a href="#cb60-121" aria-hidden="true" tabindex="-1"></a><span class="co">#PROPORTIONAL BAR CHART</span></span>
<span id="cb60-122"><a href="#cb60-122" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_props</span>(<span class="sc">~</span>score_niceABS, <span class="at">data =</span> df, <span class="at">fill =</span> <span class="sc">~</span>mode) <span class="sc">%&gt;%</span> </span>
<span id="cb60-123"><a href="#cb60-123" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_facet_grid</span>(mode<span class="sc">~</span>condition, <span class="at">labeller =</span> label_both) <span class="sc">+</span></span>
<span id="cb60-124"><a href="#cb60-124" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Correct Response on Q 1"</span>,</span>
<span id="cb60-125"><a href="#cb60-125" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Accuracy on First Question by Condition (Both Modalities)"</span>,</span>
<span id="cb60-126"><a href="#cb60-126" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle=</span><span class="st">"Impasse Condition yields a greater proportion of correct responses than control "</span>)<span class="sc">+</span></span>
<span id="cb60-127"><a href="#cb60-127" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()<span class="sc">+</span> <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span>
<span id="cb60-128"><a href="#cb60-128" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb60-129"><a href="#cb60-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-130"><a href="#cb60-130" aria-hidden="true" tabindex="-1"></a>A proportional bar chart visualizing the proportion of incorrect (x =0) vs correct (x = 1) responses in each condition (right/left facet) for each data collection modality (top/bottom) reveal that the pattern of responses appear the same regardless of the data collection modality. In both data collection sessions, the proportion of incorrect responses is much greater than the proportion of correct responses, regardless of condition. In the impasse condition, the difference in proportions is smaller than the control condition (i.e. There are more correct responses in the impasse condition than the control condition).</span>
<span id="cb60-131"><a href="#cb60-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-134"><a href="#cb60-134" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb60-135"><a href="#cb60-135" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: VIS-Q1ACC.by.COND-mosaic</span></span>
<span id="cb60-136"><a href="#cb60-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-137"><a href="#cb60-137" aria-hidden="true" tabindex="-1"></a><span class="co">#MOSAIC PLOT</span></span>
<span id="cb60-138"><a href="#cb60-138" aria-hidden="true" tabindex="-1"></a>vcd<span class="sc">::</span><span class="fu">mosaic</span>(<span class="at">main=</span><span class="st">"Accuracy on First Question by Condition (Both Modalities)"</span>,</span>
<span id="cb60-139"><a href="#cb60-139" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> df, score_niceABS <span class="sc">~</span> condition, <span class="at">rot_labels=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">90</span>,<span class="dv">0</span>,<span class="dv">0</span>),</span>
<span id="cb60-140"><a href="#cb60-140" aria-hidden="true" tabindex="-1"></a>            <span class="at">offset_varnames =</span> <span class="fu">c</span>(<span class="at">left =</span> <span class="fl">4.5</span>), <span class="at">offset_labels =</span> <span class="fu">c</span>(<span class="at">left =</span> <span class="sc">-</span><span class="fl">0.5</span>),<span class="at">just_labels =</span> <span class="st">"right"</span>,</span>
<span id="cb60-141"><a href="#cb60-141" aria-hidden="true" tabindex="-1"></a>            <span class="at">spacing =</span> <span class="fu">spacing_dimequal</span>(<span class="fu">unit</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="st">"lines"</span>)))</span>
<span id="cb60-142"><a href="#cb60-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-143"><a href="#cb60-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-144"><a href="#cb60-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-145"><a href="#cb60-145" aria-hidden="true" tabindex="-1"></a><span class="co">#PRINT CONTINGENCY TABLE</span></span>
<span id="cb60-146"><a href="#cb60-146" aria-hidden="true" tabindex="-1"></a>title <span class="ot">=</span> <span class="st">"Proportion of Correct Responses On First Item (Both Modalities)"</span></span>
<span id="cb60-147"><a href="#cb60-147" aria-hidden="true" tabindex="-1"></a>item.contingency <span class="ot">&lt;-</span>  df <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(condition, score_niceABS) <span class="sc">%&gt;%</span> <span class="fu">table</span>() <span class="sc">%&gt;%</span> <span class="fu">prop.table</span>() <span class="sc">%&gt;%</span> <span class="fu">addmargins</span>()</span>
<span id="cb60-148"><a href="#cb60-148" aria-hidden="true" tabindex="-1"></a>item.contingency <span class="sc">%&gt;%</span> <span class="fu">kbl</span> (<span class="at">caption =</span> title) <span class="sc">%&gt;%</span> <span class="fu">kable_classic</span>()</span>
<span id="cb60-149"><a href="#cb60-149" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb60-150"><a href="#cb60-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-151"><a href="#cb60-151" aria-hidden="true" tabindex="-1"></a>A mosaic plot condition by response accuracy on the first question (across both data collection modalities) reveals the same pattern (the mosaic plot is an alternative visualization technique to the proportional bar chart). The relative size of condition boxes (111 vs 121) reflects that the sample is roughly evenly split across experimental conditions. The difference in size between 0 (incorrect) and 1 (correct) reflects that the proportion of correct responses (1) is greater in the impasse condition (121).</span>
<span id="cb60-152"><a href="#cb60-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-153"><a href="#cb60-153" aria-hidden="true" tabindex="-1"></a>Next, we compute a contingency table and Pearson's Chi-Squared test for each data collection modality.</span>
<span id="cb60-154"><a href="#cb60-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-157"><a href="#cb60-157" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb60-158"><a href="#cb60-158" aria-hidden="true" tabindex="-1"></a><span class="co">#| label : CHISQR-Q1TRI.by.COND-LAB</span></span>
<span id="cb60-159"><a href="#cb60-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-160"><a href="#cb60-160" aria-hidden="true" tabindex="-1"></a>df <span class="ot">=</span> df_items <span class="sc">%&gt;%</span> <span class="fu">filter</span>(q<span class="sc">==</span><span class="dv">1</span>) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(mode <span class="sc">==</span> <span class="st">"lab-synch"</span>)</span>
<span id="cb60-161"><a href="#cb60-161" aria-hidden="true" tabindex="-1"></a><span class="fu">CrossTable</span>( <span class="at">x =</span> df<span class="sc">$</span>condition, <span class="at">y =</span> df<span class="sc">$</span>score_niceABS, <span class="at">fisher =</span> <span class="cn">TRUE</span>, <span class="at">chisq=</span><span class="cn">TRUE</span>, <span class="at">expected =</span> <span class="cn">TRUE</span>, <span class="at">sresid =</span> <span class="cn">TRUE</span>)</span>
<span id="cb60-162"><a href="#cb60-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-163"><a href="#cb60-163" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb60-164"><a href="#cb60-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-165"><a href="#cb60-165" aria-hidden="true" tabindex="-1"></a>**For the in-lab data collection** (n=126) the Pearson's Chi-squared test (of independence) indicates a relationship between response accuracy on the first question and experimental condition approaching statistical significance, $\chi^2$ (1) = 10.3, p = 0.07. Thus we have insufficient evidence to reject the null hypothesis that the odds ratio is equal to 1. In this particular data sample, the odds ratio (Odds Ratio = 2.18, p = 0.055, 95% CI <span class="sc">\[</span>0.982, +Inf<span class="sc">\]</span>) indicates that the odds of producing a correct response on the first question were 2.18 times greater if a subject was in the impasse condition, than in the control condition .</span>
<span id="cb60-166"><a href="#cb60-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-169"><a href="#cb60-169" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb60-170"><a href="#cb60-170" aria-hidden="true" tabindex="-1"></a><span class="co">#| label : CHISQR-Q1TRI.by.COND-ONLINE</span></span>
<span id="cb60-171"><a href="#cb60-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-172"><a href="#cb60-172" aria-hidden="true" tabindex="-1"></a>df <span class="ot">=</span> df_items <span class="sc">%&gt;%</span> <span class="fu">filter</span>(q<span class="sc">==</span><span class="dv">1</span>) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(mode <span class="sc">==</span> <span class="st">"asynch"</span>)</span>
<span id="cb60-173"><a href="#cb60-173" aria-hidden="true" tabindex="-1"></a><span class="fu">CrossTable</span>( <span class="at">x =</span> df<span class="sc">$</span>condition, <span class="at">y =</span> df<span class="sc">$</span>score_niceABS, <span class="at">fisher =</span> <span class="cn">TRUE</span>, <span class="at">chisq=</span><span class="cn">TRUE</span>, <span class="at">expected =</span> <span class="cn">TRUE</span>, <span class="at">sresid =</span> <span class="cn">TRUE</span>)</span>
<span id="cb60-174"><a href="#cb60-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-175"><a href="#cb60-175" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb60-176"><a href="#cb60-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-177"><a href="#cb60-177" aria-hidden="true" tabindex="-1"></a>**For online data collection** (n=204), a Pearson's Chi-squared test (of independence) indicates a statistically significant relationship between response accuracy on the first question and experimental condition, $\chi^2$ (1) = 7.26, p = 0.009. Thus we have sufficient evidence to reject the null hypothesis that the odds ratio is equal to 1. The odds ratio (Odds Ratio = 2.68, p = 0.005, 95% CI <span class="sc">\[</span>1.37, +Inf<span class="sc">\]</span>) indicates that the odds of producing a correct response on the first question were 2.68 times greater if a subject was in the impasse condition, than in the control condition .</span>
<span id="cb60-178"><a href="#cb60-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-181"><a href="#cb60-181" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb60-182"><a href="#cb60-182" aria-hidden="true" tabindex="-1"></a><span class="co">#| label : CHISQR-Q1TRI.by.COND-BOTH</span></span>
<span id="cb60-183"><a href="#cb60-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-184"><a href="#cb60-184" aria-hidden="true" tabindex="-1"></a>df <span class="ot">=</span> df_items <span class="sc">%&gt;%</span> <span class="fu">filter</span>(q<span class="sc">==</span><span class="dv">1</span>) </span>
<span id="cb60-185"><a href="#cb60-185" aria-hidden="true" tabindex="-1"></a><span class="fu">CrossTable</span>( <span class="at">x =</span> df<span class="sc">$</span>condition, <span class="at">y =</span> df<span class="sc">$</span>score_niceABS, <span class="at">fisher =</span> <span class="cn">TRUE</span>, <span class="at">chisq=</span><span class="cn">TRUE</span>, <span class="at">expected =</span> <span class="cn">TRUE</span>, <span class="at">sresid =</span> <span class="cn">TRUE</span>)</span>
<span id="cb60-186"><a href="#cb60-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-187"><a href="#cb60-187" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb60-188"><a href="#cb60-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-189"><a href="#cb60-189" aria-hidden="true" tabindex="-1"></a>**Combining data across both sessions** (n=330), a Pearson's Chi-squared test suggests a statistically significant relationship between response accuracy on the first question and experimental condition, $\chi_2$ (1) = 10.3, p = 0.001. The sample odds ratio (2.46, p = 0.001, 95% CI <span class="sc">\[</span>1.37, 4.53<span class="sc">\]</span>) indicates that the odds of providing a correct response to the first question are 2.46 higher for subjects in the impasse condition than those in the control condition.</span>
<span id="cb60-190"><a href="#cb60-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-191"><a href="#cb60-191" aria-hidden="true" tabindex="-1"></a><span class="fu">## CUMULATIVE PERFORMANCE</span></span>
<span id="cb60-192"><a href="#cb60-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-193"><a href="#cb60-193" aria-hidden="true" tabindex="-1"></a>*Overall* does the impasse condition affect performance on the graph comprehension task?</span>
<span id="cb60-194"><a href="#cb60-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-195"><a href="#cb60-195" aria-hidden="true" tabindex="-1"></a><span class="fu">### Cumulative Score By Condition</span></span>
<span id="cb60-196"><a href="#cb60-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-197"><a href="#cb60-197" aria-hidden="true" tabindex="-1"></a>Cumulative scores indicate the response accuracy by a particular participant across all discriminant items (n=13) in the graph comprehension task.</span>
<span id="cb60-198"><a href="#cb60-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-201"><a href="#cb60-201" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb60-202"><a href="#cb60-202" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: VIS-SUBJECT-ABS</span></span>
<span id="cb60-203"><a href="#cb60-203" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb60-204"><a href="#cb60-204" aria-hidden="true" tabindex="-1"></a><span class="co">#VISUALIZE distribution of response accuracy across SUBJECTS</span></span>
<span id="cb60-205"><a href="#cb60-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-206"><a href="#cb60-206" aria-hidden="true" tabindex="-1"></a><span class="co">#HISTOGRAM</span></span>
<span id="cb60-207"><a href="#cb60-207" aria-hidden="true" tabindex="-1"></a>stats <span class="ot">=</span> df_subjects <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(condition, mode) <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(s_ABS))</span>
<span id="cb60-208"><a href="#cb60-208" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_density</span>(<span class="sc">~</span>s_ABS, <span class="at">data =</span> df_subjects) <span class="sc">%&gt;%</span> </span>
<span id="cb60-209"><a href="#cb60-209" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_facet_grid</span>(condition<span class="sc">~</span>mode, <span class="at">labeller =</span> label_both) <span class="sc">%&gt;%</span> </span>
<span id="cb60-210"><a href="#cb60-210" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_lims</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">13</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb60-211"><a href="#cb60-211" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_vline</span>(<span class="at">data =</span> stats, <span class="at">xintercept =</span> <span class="sc">~</span>mean, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb60-212"><a href="#cb60-212" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Cumulative Absolute Score"</span>,</span>
<span id="cb60-213"><a href="#cb60-213" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"proportion of subjects"</span>,</span>
<span id="cb60-214"><a href="#cb60-214" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Subject Cumulative Score (Absolute)"</span>,</span>
<span id="cb60-215"><a href="#cb60-215" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Score distributions are comparable across modalities and different across conditions"</span>) <span class="sc">+</span> </span>
<span id="cb60-216"><a href="#cb60-216" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb60-217"><a href="#cb60-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-218"><a href="#cb60-218" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb60-219"><a href="#cb60-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-220"><a href="#cb60-220" aria-hidden="true" tabindex="-1"></a>**Does the IMPASSE condition yield higher scores?**</span>
<span id="cb60-221"><a href="#cb60-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-222"><a href="#cb60-222" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Linear Regression</span></span>
<span id="cb60-223"><a href="#cb60-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-224"><a href="#cb60-224" aria-hidden="true" tabindex="-1"></a>To address this question we assess how much variance in cumulative (absolute) score is explained by experimental condition by utilizing OLS linear regression, predicting absolute score from condition.</span>
<span id="cb60-225"><a href="#cb60-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-228"><a href="#cb60-228" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb60-229"><a href="#cb60-229" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: MODEL-cumulative-score-LAB</span></span>
<span id="cb60-230"><a href="#cb60-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-231"><a href="#cb60-231" aria-hidden="true" tabindex="-1"></a><span class="co">#SCORE predicted by CONDITION</span></span>
<span id="cb60-232"><a href="#cb60-232" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(s_ABS <span class="sc">~</span> condition, <span class="at">data =</span> df_subjects <span class="sc">%&gt;%</span> <span class="fu">filter</span>(mode<span class="sc">==</span><span class="st">"lab-synch"</span>))</span>
<span id="cb60-233"><a href="#cb60-233" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Model"</span>)</span>
<span id="cb60-234"><a href="#cb60-234" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span>
<span id="cb60-235"><a href="#cb60-235" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Partition Variance"</span>)</span>
<span id="cb60-236"><a href="#cb60-236" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1)</span>
<span id="cb60-237"><a href="#cb60-237" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Confidence Interval on Parameter Estimates"</span>)</span>
<span id="cb60-238"><a href="#cb60-238" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(m1)</span>
<span id="cb60-239"><a href="#cb60-239" aria-hidden="true" tabindex="-1"></a><span class="co"># report(m1) #sanity check</span></span>
<span id="cb60-240"><a href="#cb60-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-241"><a href="#cb60-241" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb60-242"><a href="#cb60-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-243"><a href="#cb60-243" aria-hidden="true" tabindex="-1"></a>**For in-lab data collection** an OLS linear regression predicting cumulative absolute score by experimental condition explains a statistically significant though small 7.5% variance in score (F(1,124) = 10.1, p <span class="sc">\&lt;</span> 0.01). The estimated beta coefficient ($/beta$ = 2.76, 95% CI <span class="sc">\[</span>1.04, 4.48<span class="sc">\]</span>) predicts that participants in the impasse condition will on average score 2.76 points (21%) higher than those in the control condition.</span>
<span id="cb60-244"><a href="#cb60-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-247"><a href="#cb60-247" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb60-248"><a href="#cb60-248" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: MODEL-cumulative-score-ONLINE</span></span>
<span id="cb60-249"><a href="#cb60-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-250"><a href="#cb60-250" aria-hidden="true" tabindex="-1"></a><span class="co">#SCORE predicted by CONDITION</span></span>
<span id="cb60-251"><a href="#cb60-251" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(s_ABS <span class="sc">~</span> condition, <span class="at">data =</span> df_subjects <span class="sc">%&gt;%</span> <span class="fu">filter</span>(mode<span class="sc">==</span><span class="st">"asynch"</span>))</span>
<span id="cb60-252"><a href="#cb60-252" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Model"</span>)</span>
<span id="cb60-253"><a href="#cb60-253" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span>
<span id="cb60-254"><a href="#cb60-254" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Partition Variance"</span>)</span>
<span id="cb60-255"><a href="#cb60-255" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1)</span>
<span id="cb60-256"><a href="#cb60-256" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Confidence Interval on Parameter Estimates"</span>)</span>
<span id="cb60-257"><a href="#cb60-257" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(m1)</span>
<span id="cb60-258"><a href="#cb60-258" aria-hidden="true" tabindex="-1"></a><span class="co">#report(m1) #sanity check</span></span>
<span id="cb60-259"><a href="#cb60-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-260"><a href="#cb60-260" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb60-261"><a href="#cb60-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-262"><a href="#cb60-262" aria-hidden="true" tabindex="-1"></a>**For the online replication**, an OLS linear regression model predicting cumulative absolute score by condition explains a statistically significant though small 5.5% of variance in absolute score (F(1,202) = 11.73, p <span class="sc">\&lt;</span> 0.001). The beta coefficient for condition indicates that on average, participants in the IMPASSE group scored 2.3 points higher on the task than those in the control condition (CI<span class="sc">\[</span>0.97, 3.59<span class="sc">\]</span>).</span>
<span id="cb60-263"><a href="#cb60-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-264"><a href="#cb60-264" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb60-265"><a href="#cb60-265" aria-hidden="true" tabindex="-1"></a>**From these models we can reasonably conclude that the impasse condition yielded a small but reliable improvement in performance across items in the graph reading task.**</span>
<span id="cb60-266"><a href="#cb60-266" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb60-267"><a href="#cb60-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-268"><a href="#cb60-268" aria-hidden="true" tabindex="-1"></a>**Model Diagnostics**</span>
<span id="cb60-269"><a href="#cb60-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-272"><a href="#cb60-272" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb60-273"><a href="#cb60-273" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: DIAGNOSTICS-ABSCORE-LINEAR</span></span>
<span id="cb60-274"><a href="#cb60-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-275"><a href="#cb60-275" aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(m1)</span>
<span id="cb60-276"><a href="#cb60-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-277"><a href="#cb60-277" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb60-278"><a href="#cb60-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-279"><a href="#cb60-279" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Poisson Regression</span></span>
<span id="cb60-280"><a href="#cb60-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-281"><a href="#cb60-281" aria-hidden="true" tabindex="-1"></a>The outcome variable absolute score is clearly not normal. As it represents the cumulative number of items a participant has answered correctly, we can consider it a type of *count*, (ie. count of the number of questions the participant got correct) and attempt to model it using a General Linear Model with the Poisson distribution (and the default log-link function).</span>
<span id="cb60-282"><a href="#cb60-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-285"><a href="#cb60-285" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb60-286"><a href="#cb60-286" aria-hidden="true" tabindex="-1"></a><span class="co"># library('fitdistrplus')</span></span>
<span id="cb60-287"><a href="#cb60-287" aria-hidden="true" tabindex="-1"></a><span class="co"># plot(fitdist(df_subjects$s_ABS,"pois"))</span></span>
<span id="cb60-288"><a href="#cb60-288" aria-hidden="true" tabindex="-1"></a><span class="co"># plot(fitdist(df_subjects$s_ABS,"norm"))</span></span>
<span id="cb60-289"><a href="#cb60-289" aria-hidden="true" tabindex="-1"></a><span class="co"># plot(fitdist(df_subjects$s_ABS,"beta"))</span></span>
<span id="cb60-290"><a href="#cb60-290" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb60-291"><a href="#cb60-291" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb60-292"><a href="#cb60-292" aria-hidden="true" tabindex="-1"></a><span class="co"># plotdist(df_subjects$s_ABS, histo = TRUE, demp = TRUE)</span></span>
<span id="cb60-293"><a href="#cb60-293" aria-hidden="true" tabindex="-1"></a><span class="co"># descdist(df_subjects$s_ABS, discrete=FALSE, boot=500)</span></span>
<span id="cb60-294"><a href="#cb60-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-295"><a href="#cb60-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-296"><a href="#cb60-296" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb60-297"><a href="#cb60-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-300"><a href="#cb60-300" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb60-301"><a href="#cb60-301" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: MODEL-ABSCORE-POISSON</span></span>
<span id="cb60-302"><a href="#cb60-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-303"><a href="#cb60-303" aria-hidden="true" tabindex="-1"></a><span class="co">#SCORE predicted by CONDITION --&gt; POISSON DISTRIBUTION</span></span>
<span id="cb60-304"><a href="#cb60-304" aria-hidden="true" tabindex="-1"></a>mp1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(s_ABS <span class="sc">~</span> condition, <span class="at">data =</span> df_subjects <span class="sc">%&gt;%</span> <span class="fu">filter</span>(mode<span class="sc">==</span><span class="st">"lab-synch"</span>), <span class="at">family =</span> <span class="st">"poisson"</span>)</span>
<span id="cb60-305"><a href="#cb60-305" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Model"</span>)</span>
<span id="cb60-306"><a href="#cb60-306" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mp1)</span>
<span id="cb60-307"><a href="#cb60-307" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Partition Variance"</span>)</span>
<span id="cb60-308"><a href="#cb60-308" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mp1)</span>
<span id="cb60-309"><a href="#cb60-309" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Confidence Interval on Parameter Estimates"</span>)</span>
<span id="cb60-310"><a href="#cb60-310" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mp1)</span>
<span id="cb60-311"><a href="#cb60-311" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(mp1) <span class="co">#sanity check</span></span>
<span id="cb60-312"><a href="#cb60-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-313"><a href="#cb60-313" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb60-314"><a href="#cb60-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-317"><a href="#cb60-317" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb60-318"><a href="#cb60-318" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: DIAGNOSTICS-ABSCORE-POISSON</span></span>
<span id="cb60-319"><a href="#cb60-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-320"><a href="#cb60-320" aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(mp1)</span>
<span id="cb60-321"><a href="#cb60-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-322"><a href="#cb60-322" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb60-323"><a href="#cb60-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-326"><a href="#cb60-326" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb60-327"><a href="#cb60-327" aria-hidden="true" tabindex="-1"></a><span class="co">#Which is a better fit? linear or poisson?</span></span>
<span id="cb60-328"><a href="#cb60-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-329"><a href="#cb60-329" aria-hidden="true" tabindex="-1"></a><span class="fu">compare_performance</span>(m1,mp1)</span>
<span id="cb60-330"><a href="#cb60-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-331"><a href="#cb60-331" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb60-332"><a href="#cb60-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-333"><a href="#cb60-333" aria-hidden="true" tabindex="-1"></a><span class="fu">## RESOURCES</span></span>
<span id="cb60-334"><a href="#cb60-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-335"><a href="#cb60-335" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>https://rpkgs.datanovia.com/ggpubr/reference/index.html</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>