<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-0.9.328">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>SGC-X - 4&nbsp; Modelling</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<link href="../../references.html" rel="next">
<link href="../../analysis/SGC3A/3_sgc3A_exploration.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link id="quarto-text-highlighting-styles" href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Modelling</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">SGC-X</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">Status</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="../../analysis/SGC3A/SGC3A.html" class="sidebar-item-text sidebar-link">SGC3A</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../analysis/SGC3A/1_sgc3A_harmonize.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Harmonization</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../analysis/SGC3A/2_sgc3A_scoring.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Response Scoring</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../analysis/SGC3A/3_sgc3A_exploration.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Exploration</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../analysis/SGC3A/4_sgc3A_modelling.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Modelling</span></a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#cumulative-performance" id="toc-cumulative-performance" class="nav-link active" data-scroll-target="#cumulative-performance"> <span class="header-section-number">4.1</span> Cumulative Performance</a>
  <ul class="collapse">
  <li><a href="#cumulative-score-by-condition" id="toc-cumulative-score-by-condition" class="nav-link" data-scroll-target="#cumulative-score-by-condition"> <span class="header-section-number">4.1.1</span> Cumulative Score By Condition</a>
  <ul class="collapse">
  <li><a href="#linear-regression" id="toc-linear-regression" class="nav-link" data-scroll-target="#linear-regression"> <span class="header-section-number">4.1.1.1</span> Linear Regression</a></li>
  <li><a href="#poisson-regression" id="toc-poisson-regression" class="nav-link" data-scroll-target="#poisson-regression"> <span class="header-section-number">4.1.1.2</span> Poisson Regression</a></li>
  <li><a href="#copied-from-3" id="toc-copied-from-3" class="nav-link" data-scroll-target="#copied-from-3"> <span class="header-section-number">4.1.1.3</span> COPIED FROM 3</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#first-question" id="toc-first-question" class="nav-link" data-scroll-target="#first-question"> <span class="header-section-number">4.2</span> First Question</a></li>
  <li><a href="#item-level-performance" id="toc-item-level-performance" class="nav-link" data-scroll-target="#item-level-performance"> <span class="header-section-number">4.3</span> Item-Level Performance</a></li>
  <li><a href="#model-peeking" id="toc-model-peeking" class="nav-link" data-scroll-target="#model-peeking"> <span class="header-section-number">4.4</span> Model Peeking</a></li>
  <li><a href="#resources" id="toc-resources" class="nav-link" data-scroll-target="#resources"> <span class="header-section-number">4.5</span> Resources</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-SGC3A-modelling" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Modelling</span></span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
<p class="subtitle lead">Study SGC3A | 4 Modelling</p>
</div>





<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<div style="page-break-after: always;"></div>
<p>TODO - port modelling from 3_exploration into 4_modelling</p>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co">#ALL THE THINGS</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Hmisc) <span class="co"># %nin% operator</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr) <span class="co">#arrange plots</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggformula) <span class="co">#easy graphs</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(report) <span class="co">#easystats reporting</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(see) <span class="co">#easystats visualization</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance) <span class="co">#easystats model diagnostics</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co">#set some output options</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">dplyr.summarise.inform =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">ggplot2.summarise.inform =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen=</span><span class="dv">1</span>, <span class="at">digits=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><em>The purpose of this notebook is explore the distribution of dependent variables for Study SGC3A.</em></p>
<table class="table">
<colgroup>
<col style="width: 36%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th>Pre-Requisite</th>
<th>Followed By</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1_sgc3A_harmonize.qmd<br>
2_sgc3A_rescoring.qmd<br>
3_sgc3A_exploration.qmd</td>
<td>|</td>
</tr>
</tbody>
</table>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#IMPORT DATA </span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>df_items <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">'data/2-scored-data/sgc3a_scored_items.rds'</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>df_subjects <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">'data/2-scored-data/sgc3a_scored_participants.rds'</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co">#SEPARATE ITEM DATA BY QUESTION TYPE</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>df_scaffold <span class="ot">&lt;-</span> df_items <span class="sc">%&gt;%</span> <span class="fu">filter</span>(q <span class="sc">&lt;</span> <span class="dv">6</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>df_test <span class="ot">&lt;-</span> df_items <span class="sc">%&gt;%</span> <span class="fu">filter</span>(q <span class="sc">&gt;</span> <span class="dv">6</span>) <span class="sc">%&gt;%</span> <span class="fu">filter</span> (q <span class="sc">%nin%</span> <span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">9</span>))</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>df_nondiscrim <span class="ot">&lt;-</span> df_items <span class="sc">%&gt;%</span> <span class="fu">filter</span> (q <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">9</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="cumulative-performance" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="cumulative-performance"><span class="header-section-number">4.1</span> Cumulative Performance</h2>
<p><em>Overall</em> does the impasse condition affect performance on the graph comprehension task?</p>
<section id="cumulative-score-by-condition" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="cumulative-score-by-condition"><span class="header-section-number">4.1.1</span> Cumulative Score By Condition</h3>
<p>Cumulative scores indicate the response accuracy by a particular participant across all discriminant items (n=13) in the graph comprehension task.</p>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#VISUALIZE distribution of response accuracy across SUBJECTS</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co">#HISTOGRAM</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>stats <span class="ot">=</span> df_subjects <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(condition, mode) <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(s_ABS))</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_density</span>(<span class="sc">~</span>s_ABS, <span class="at">data =</span> df_subjects) <span class="sc">%&gt;%</span> </span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_facet_grid</span>(condition<span class="sc">~</span>mode, <span class="at">labeller =</span> label_both) <span class="sc">%&gt;%</span> </span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_lims</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">13</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_vline</span>(<span class="at">data =</span> stats, <span class="at">xintercept =</span> <span class="sc">~</span>mean, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Cumulative Absolute Score"</span>,</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"proportion of subjects"</span>,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Subject Cumulative Score (Absolute)"</span>,</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Score distributions are comparable across modalities and different across conditions"</span>) <span class="sc">+</span> </span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="4_sgc3A_modelling_files/figure-html/VIS-SUBJECT-ABS-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Does the IMPASSE condition yield higher scores?</strong></p>
<section id="linear-regression" class="level4" data-number="4.1.1.1">
<h4 data-number="4.1.1.1" class="anchored" data-anchor-id="linear-regression"><span class="header-section-number">4.1.1.1</span> Linear Regression</h4>
<p>To address this question we assess how much variance in cumulative (absolute) score is explained by experimental condition by utilizing OLS linear regression, predicting absolute score from condition.</p>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#SCORE predicted by CONDITION</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(s_ABS <span class="sc">~</span> condition, <span class="at">data =</span> df_subjects <span class="sc">%&gt;%</span> <span class="fu">filter</span>(mode<span class="sc">==</span><span class="st">"lab-synch"</span>))</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Model"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Model"</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = s_ABS ~ condition, data = df_subjects %&gt;% filter(mode == 
    "lab-synch"))

Residuals:
   Min     1Q Median     3Q    Max 
 -5.44  -2.68  -2.68   4.31  10.32 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     2.677      0.620    4.32 0.000031 ***
condition121    2.760      0.869    3.17   0.0019 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.88 on 124 degrees of freedom
Multiple R-squared:  0.0752,    Adjusted R-squared:  0.0677 
F-statistic: 10.1 on 1 and 124 DF,  p-value: 0.00189</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Partition Variance"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Partition Variance"</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: s_ABS
           Df Sum Sq Mean Sq F value Pr(&gt;F)   
condition   1    240   239.9    10.1 0.0019 **
Residuals 124   2951    23.8                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Confidence Interval on Parameter Estimates"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Confidence Interval on Parameter Estimates"</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             2.5 % 97.5 %
(Intercept)   1.45   3.90
condition121  1.04   4.48</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># report(m1) #sanity check</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><strong>For in-lab data collection</strong> an OLS linear regression predicting cumulative absolute score by experimental condition explains a statistically significant though small 7.5% variance in score (F(1,124) = 10.1, p &lt; 0.01). The estimated beta coefficient (<span class="math inline">\(/beta\)</span> = 2.76, 95% CI [1.04, 4.48]) predicts that participants in the impasse condition will on average score 2.76 points (21%) higher than those in the control condition.</p>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#SCORE predicted by CONDITION</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(s_ABS <span class="sc">~</span> condition, <span class="at">data =</span> df_subjects <span class="sc">%&gt;%</span> <span class="fu">filter</span>(mode<span class="sc">==</span><span class="st">"asynch"</span>))</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Model"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Model"</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = s_ABS ~ condition, data = df_subjects %&gt;% filter(mode == 
    "asynch"))

Residuals:
   Min     1Q Median     3Q    Max 
 -4.58  -3.58  -2.30   3.42  10.70 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     2.302      0.485    4.75  3.8e-06 ***
condition121    2.281      0.666    3.43  0.00074 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.75 on 202 degrees of freedom
Multiple R-squared:  0.0549,    Adjusted R-squared:  0.0502 
F-statistic: 11.7 on 1 and 202 DF,  p-value: 0.000745</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Partition Variance"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Partition Variance"</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: s_ABS
           Df Sum Sq Mean Sq F value  Pr(&gt;F)    
condition   1    264   264.5    11.7 0.00074 ***
Residuals 202   4554    22.5                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Confidence Interval on Parameter Estimates"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Confidence Interval on Parameter Estimates"</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             2.5 % 97.5 %
(Intercept)  1.347   3.26
condition121 0.968   3.59</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">#report(m1) #sanity check</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><strong>For the online replication</strong>, an OLS linear regression model predicting cumulative absolute score by condition explains a statistically significant though small 5.5% of variance in absolute score (F(1,202) = 11.73, p &lt; 0.001). The beta coefficient for condition indicates that on average, participants in the IMPASSE group scored 2.3 points higher on the task than those in the control condition (CI[0.97, 3.59]).</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>From these models we can reasonably conclude that the impasse condition yielded a small but reliable improvement in performance across items in the graph reading task.</strong></p>
</div>
</div>
<p><strong>Model Diagnostics</strong></p>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="4_sgc3A_modelling_files/figure-html/DIAGNOSTICS-ABSCORE-LINEAR-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="poisson-regression" class="level4" data-number="4.1.1.2">
<h4 data-number="4.1.1.2" class="anchored" data-anchor-id="poisson-regression"><span class="header-section-number">4.1.1.2</span> Poisson Regression</h4>
<p>The outcome variable absolute score is clearly not normal. As it represents the cumulative number of items a participant has answered correctly, we can consider it a type of <em>count</em>, (ie. count of the number of questions the participant got correct) and attempt to model it using a General Linear Model with the Poisson distribution (and the default log-link function).</p>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># library('fitdistrplus')</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="co"># plot(fitdist(df_subjects$s_ABS,"pois"))</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="co"># plot(fitdist(df_subjects$s_ABS,"norm"))</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="co"># plot(fitdist(df_subjects$s_ABS,"beta"))</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="co"># plotdist(df_subjects$s_ABS, histo = TRUE, demp = TRUE)</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="co"># descdist(df_subjects$s_ABS, discrete=FALSE, boot=500)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#SCORE predicted by CONDITION --&gt; POISSON DISTRIBUTION</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>mp1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(s_ABS <span class="sc">~</span> condition, <span class="at">data =</span> df_subjects <span class="sc">%&gt;%</span> <span class="fu">filter</span>(mode<span class="sc">==</span><span class="st">"lab-synch"</span>), <span class="at">family =</span> <span class="st">"poisson"</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Model"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Model"</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mp1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = s_ABS ~ condition, family = "poisson", data = df_subjects %&gt;% 
    filter(mode == "lab-synch"))

Deviance Residuals: 
   Min      1Q  Median      3Q     Max  
 -3.30   -2.31   -2.31    1.75    4.52  

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)    0.9849     0.0776   12.69  &lt; 2e-16 ***
condition121   0.7085     0.0943    7.51  5.9e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 855.68  on 125  degrees of freedom
Residual deviance: 795.46  on 124  degrees of freedom
AIC: 1045

Number of Fisher Scoring iterations: 6</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Partition Variance"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Partition Variance"</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mp1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model: poisson, link: log

Response: s_ABS

Terms added sequentially (first to last)

          Df Deviance Resid. Df Resid. Dev
NULL                        125        856
condition  1     60.2       124        795</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Confidence Interval on Parameter Estimates"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Confidence Interval on Parameter Estimates"</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mp1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>             2.5 % 97.5 %
(Intercept)  0.829  1.133
condition121 0.525  0.896</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(mp1) <span class="co">#sanity check</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>We fitted a poisson model (estimated using ML) to predict s_ABS with condition (formula: s_ABS ~ condition). The model's explanatory power is substantial (Nagelkerke's R2 = 0.38). The model's intercept, corresponding to condition = 111, is at 0.98 (95% CI [0.83, 1.13], p &lt; .001). Within this model:

  - The effect of condition [121] is statistically significant and positive (beta = 0.71, 95% CI [0.53, 0.90], p &lt; .001; Std. beta = 0.71, 95% CI [0.53, 0.90])

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using </code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(mp1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="4_sgc3A_modelling_files/figure-html/DIAGNOSTICS-ABSCORE-POISSON-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Which is a better fit? linear or poisson?</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="fu">compare_performance</span>(m1,mp1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: When comparing models, please note that probably not all models were fit from
  same data.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># Comparison of Model Performance Indices

Name | Model |      AIC | AIC weights |      BIC | BIC weights |  RMSE | Sigma |    R2 | R2 (adj.) | Nagelkerke's R2 | Score_log | Score_spherical
--------------------------------------------------------------------------------------------------------------------------------------------------
m1   |    lm | 1218.500 |     &lt; 0.001 | 1228.454 |     &lt; 0.001 | 4.725 | 4.748 | 0.055 |     0.050 |                 |           |                
mp1  |   glm | 1044.751 |        1.00 | 1050.423 |        1.00 | 4.840 | 2.533 |       |           |           0.380 |    -4.130 |           0.063</code></pre>
</div>
</div>
</section>
<section id="copied-from-3" class="level4" data-number="4.1.1.3">
<h4 data-number="4.1.1.3" class="anchored" data-anchor-id="copied-from-3"><span class="header-section-number">4.1.1.3</span> COPIED FROM 3</h4>
<p><strong>Does the IMPASSE condition more accurate interpretation?</strong></p>
<p>To address this question we assess how much variance in cumulative (absolute) score is explained by experimental condition.</p>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co">#SCORE predicted by CONDITION</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(s_SCALED <span class="sc">~</span> condition, <span class="at">data =</span> df_subjects <span class="sc">%&gt;%</span> <span class="fu">filter</span>(mode<span class="sc">==</span><span class="st">"lab-synch"</span>))</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Model"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Model"</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = s_SCALED ~ condition, data = df_subjects %&gt;% filter(mode == 
    "lab-synch"))

Residuals:
   Min     1Q Median     3Q    Max 
-12.75  -6.87  -4.87   9.03  19.13 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     -6.13       1.18   -5.20  8.0e-07 ***
condition121     7.88       1.65    4.76  5.2e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.28 on 124 degrees of freedom
Multiple R-squared:  0.155, Adjusted R-squared:  0.148 
F-statistic: 22.7 on 1 and 124 DF,  p-value: 5.21e-06</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Partition Variance"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Partition Variance"</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: s_SCALED
           Df Sum Sq Mean Sq F value  Pr(&gt;F)    
condition   1   1955    1955    22.7 5.2e-06 ***
Residuals 124  10681      86                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Confidence Interval on Parameter Estimates"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Confidence Interval on Parameter Estimates"</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             2.5 % 97.5 %
(Intercept)  -8.46   -3.8
condition121  4.61   11.2</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># report(m1) #sanity check</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><strong>For in-lab data collection</strong> an OLS linear regression predicting scaled score by experimental condition explains a statistically significant and moderate 15% variance in score (F(1,124) = 22.7, p &lt; 0.001). The estimated beta coefficient (<span class="math inline">\(/beta\)</span> = 7.88, 95% CI [4.61, 11.2]) predicts that participants in the impasse condition will on average score around 8 points (31%) higher than those in the control condition.</p>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co">#SCORE predicted by CONDITION</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(s_SCALED <span class="sc">~</span> condition, <span class="at">data =</span> df_subjects <span class="sc">%&gt;%</span> <span class="fu">filter</span>(mode<span class="sc">==</span><span class="st">"asynch"</span>))</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Model"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Model"</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = s_SCALED ~ condition, data = df_subjects %&gt;% filter(mode == 
    "asynch"))

Residuals:
   Min     1Q Median     3Q    Max 
-13.16  -7.16  -3.02   7.12  18.62 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    -5.620      0.866   -6.49  6.5e-10 ***
condition121    6.777      1.190    5.70  4.3e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.48 on 202 degrees of freedom
Multiple R-squared:  0.138, Adjusted R-squared:  0.134 
F-statistic: 32.4 on 1 and 202 DF,  p-value: 4.3e-08</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Partition Variance"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Partition Variance"</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: s_SCALED
           Df Sum Sq Mean Sq F value  Pr(&gt;F)    
condition   1   2334    2334    32.4 4.3e-08 ***
Residuals 202  14536      72                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Confidence Interval on Parameter Estimates"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Confidence Interval on Parameter Estimates"</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             2.5 % 97.5 %
(Intercept)  -7.33  -3.91
condition121  4.43   9.12</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co">#report(m1) #sanity check</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><strong>For the online replication</strong>, an OLS linear regression model predicting scaled score by condition explains a statistically significant and moderate 14% of variance in absolute score (F(1,202) = 32.4, p &lt; 0.001). The beta coefficient for condition indicates that on average, participants in the IMPASSE group scored 6.8 points higher on the task than those in the control condition (CI[4.43, 9.12]).</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>From these models we can reasonably conclude that the impasse condition yields a reliable, moderate sized effect of improved interpretation on the graph reading tasks.</strong></p>
</div>
</div>
</section>
</section>
</section>
<section id="first-question" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="first-question"><span class="header-section-number">4.2</span> First Question</h2>
<p>Does the impasse condition affect performance <em>on the first item</em> of the graph comprehension task?</p>
</section>
<section id="item-level-performance" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="item-level-performance"><span class="header-section-number">4.3</span> Item-Level Performance</h2>
<p>Individual differences with a mixed model.</p>
</section>
<section id="model-peeking" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="model-peeking"><span class="header-section-number">4.4</span> Model Peeking</h2>
<p>TODO</p>
<ul>
<li>multiple regression with condition and response time</li>
</ul>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(supernova)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'supernova'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:scales':

    number</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(report)</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmerTest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lme4</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: Matrix</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'Matrix'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:tidyr':

    expand, pack, unpack</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 methods overwritten by 'lme4':
  method                          from
  cooks.distance.influence.merMod car 
  influence.merMod                car 
  dfbeta.influence.merMod         car 
  dfbetas.influence.merMod        car </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'lmerTest'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:lme4':

    lmer</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:stats':

    step</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>( s_SCALED <span class="sc">~</span> condition, <span class="at">data =</span> df_subjects <span class="sc">%&gt;%</span> <span class="fu">filter</span>(mode<span class="sc">==</span><span class="st">'asynch'</span>))</span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>m1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = s_SCALED ~ condition, data = df_subjects %&gt;% filter(mode == 
    "asynch"))

Coefficients:
 (Intercept)  condition121  
       -5.62          6.78  </code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = s_SCALED ~ condition, data = df_subjects %&gt;% filter(mode == 
    "asynch"))

Residuals:
   Min     1Q Median     3Q    Max 
-13.16  -7.16  -3.02   7.12  18.62 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    -5.620      0.866   -6.49  6.5e-10 ***
condition121    6.777      1.190    5.70  4.3e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.48 on 202 degrees of freedom
Multiple R-squared:  0.138, Adjusted R-squared:  0.134 
F-statistic: 32.4 on 1 and 202 DF,  p-value: 4.3e-08</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: s_SCALED
           Df Sum Sq Mean Sq F value  Pr(&gt;F)    
condition   1   2334    2334    32.4 4.3e-08 ***
Residuals 202  14536      72                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">superanova</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> Analysis of Variance Table (Type III SS)
 Model: s_SCALED ~ condition

                                SS  df       MS      F    PRE     p
 ----- --------------- | --------- --- -------- ------ ------ -----
 Model (error reduced) |  2334.346   1 2334.346 32.439 0.1384 .0000
 Error (from model)    | 14536.196 202   71.961                    
 ----- --------------- | --------- --- -------- ------ ------ -----
 Total (empty model)   | 16870.543 203   83.106                    </code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="4_sgc3A_modelling_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="4_sgc3A_modelling_files/figure-html/unnamed-chunk-16-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="4_sgc3A_modelling_files/figure-html/unnamed-chunk-16-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="4_sgc3A_modelling_files/figure-html/unnamed-chunk-16-4.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_histogram</span>(<span class="sc">~</span>s_SCALED, <span class="at">data =</span> df_subjects)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="4_sgc3A_modelling_files/figure-html/unnamed-chunk-16-5.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_histogram</span>(<span class="sc">~</span>m1<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="4_sgc3A_modelling_files/figure-html/unnamed-chunk-16-6.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Assess assumption of independence of errors</span></span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a><span class="co">#DW statistic should be close to 2</span></span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'car'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    recode</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    some</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">durbinWatsonTest</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> lag Autocorrelation D-W Statistic p-value
   1         -0.0134          2.01   0.848
 Alternative hypothesis: rho != 0</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Test for equality of variance</span></span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a><span class="co">#H0 is equality; p &gt; 0.05 infer you can't reject null</span></span>
<span id="cb107-3"><a href="#cb107-3" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
       Df F value Pr(&gt;F)  
group   1     5.4  0.021 *
      202                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>A simple linear regression model predicting cumulative scaled score (at subject level) by condition explains 13% of the total variance, F(1,329) = 47.8, p &lt; 0.001. The model predicts that participants in the impasse condition will score on average 6.38 points higher than those in the control condition, 95% CI [4.56, 8.19].</p>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(s_SCALED <span class="sc">~</span> condition, <span class="at">data =</span> df_subjects)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  s_SCALED by condition
t = -7, df = 322, p-value = 1e-12
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -9.10 -5.29
sample estimates:
mean in group 111 mean in group 121 
            -5.82              1.38 </code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="co">#%&gt;% report()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="co"># report_participants(df_subjects)</span></span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a>m1 <span class="sc">%&gt;%</span> <span class="fu">report</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>We fitted a linear model (estimated using OLS) to predict s_SCALED with condition (formula: s_SCALED ~ condition). The model explains a statistically significant and moderate proportion of variance (R2 = 0.14, F(1, 202) = 32.44, p &lt; .001, adj. R2 = 0.13). The model's intercept, corresponding to condition = 111, is at -5.62 (95% CI [-7.33, -3.91], t(202) = -6.49, p &lt; .001). Within this model:

  - The effect of condition [121] is statistically significant and positive (beta = 6.78, 95% CI [4.43, 9.12], t(202) = 5.70, p &lt; .001; Std. beta = 0.74, 95% CI [0.49, 1.00])

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using the Wald approximation.</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1) <span class="sc">%&gt;%</span> <span class="fu">report</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>For one-way between subjects designs, partial eta squared is equivalent to eta squared.
Returning eta squared.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>The ANOVA suggests that:

  - The main effect of condition is statistically significant and medium (F(1, 202) = 32.44, p &lt; .001; Eta2 = 0.14, 95% CI [0.07, 1.00])</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="co">#significant intercept means that group is significantly different than zero</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="co">#logistic regression on on scaled df_subjects because residuals not normal in lm?</span></span>
<span id="cb118-2"><a href="#cb118-2" aria-hidden="true" tabindex="-1"></a>mlog <span class="ot">&lt;-</span> <span class="fu">glm</span>(s_SCALED <span class="sc">~</span> condition , <span class="at">data =</span> df_subjects, <span class="at">family =</span> gaussian)</span>
<span id="cb118-3"><a href="#cb118-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mlog)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = s_SCALED ~ condition, family = gaussian, data = df_subjects)

Deviance Residuals: 
   Min      1Q  Median      3Q     Max  
-13.38   -7.18   -3.28    8.50   18.82  

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    -5.820      0.698   -8.34  2.1e-15 ***
condition121    7.198      0.967    7.45  8.6e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for gaussian family taken to be 77)

    Null deviance: 29508  on 329  degrees of freedom
Residual deviance: 25242  on 328  degrees of freedom
AIC: 2374

Number of Fisher Scoring iterations: 2</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(mlog)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>We fitted a linear model (estimated using ML) to predict s_SCALED with condition (formula: s_SCALED ~ condition). The model's explanatory power is moderate (R2 = 0.14). The model's intercept, corresponding to condition = 111, is at -5.82 (95% CI [-7.19, -4.45], t(328) = -8.34, p &lt; .001). Within this model:

  - The effect of condition [121] is statistically significant and positive (beta = 7.20, 95% CI [5.30, 9.09], t(328) = 7.45, p &lt; .001; Std. beta = 0.76, 95% CI [0.56, 0.96])

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using </code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a><span class="co">#logistic regression on niceABS by condition</span></span>
<span id="cb122-2"><a href="#cb122-2" aria-hidden="true" tabindex="-1"></a><span class="co">#pretends that questions are independent and not from same subjects INVALID</span></span>
<span id="cb122-3"><a href="#cb122-3" aria-hidden="true" tabindex="-1"></a>mlog <span class="ot">&lt;-</span> <span class="fu">glm</span>(score_niceABS <span class="sc">~</span> condition , <span class="at">data =</span> df_items <span class="sc">%&gt;%</span> <span class="fu">filter</span>(q<span class="sc">&lt;</span><span class="dv">6</span>), <span class="at">family =</span> <span class="fu">binomial</span>())</span>
<span id="cb122-4"><a href="#cb122-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mlog)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = score_niceABS ~ condition, family = binomial(), 
    data = df_items %&gt;% filter(q &lt; 6))

Deviance Residuals: 
   Min      1Q  Median      3Q     Max  
-0.980  -0.980  -0.649   1.389   1.823  

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)   -1.4508     0.0907  -15.99   &lt;2e-16 ***
condition121   0.9672     0.1147    8.43   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1986.2  on 1649  degrees of freedom
Residual deviance: 1911.3  on 1648  degrees of freedom
AIC: 1915

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(mlog)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>We fitted a logistic model (estimated using ML) to predict score_niceABS with condition (formula: score_niceABS ~ condition). The model's explanatory power is weak (Tjur's R2 = 0.04). The model's intercept, corresponding to condition = 111, is at -1.45 (95% CI [-1.63, -1.28], p &lt; .001). Within this model:

  - The effect of condition [121] is statistically significant and positive (beta = 0.97, 95% CI [0.74, 1.19], p &lt; .001; Std. beta = 0.97, 95% CI [0.74, 1.19])

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using </code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb126"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>( s_NABS <span class="sc">~</span> condition, <span class="at">data =</span> df_subjects)</span>
<span id="cb126-2"><a href="#cb126-2" aria-hidden="true" tabindex="-1"></a>m2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = s_NABS ~ condition, data = df_subjects)

Coefficients:
 (Intercept)  condition121  
        2.47          2.46  </code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = s_NABS ~ condition, data = df_subjects)

Residuals:
   Min     1Q Median     3Q    Max 
 -4.92  -3.67  -2.47   4.08  10.53 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     2.468      0.384    6.43  4.4e-10 ***
condition121    2.456      0.531    4.62  5.5e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.82 on 328 degrees of freedom
Multiple R-squared:  0.0611,    Adjusted R-squared:  0.0583 
F-statistic: 21.4 on 1 and 328 DF,  p-value: 5.49e-06</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: s_NABS
           Df Sum Sq Mean Sq F value  Pr(&gt;F)    
condition   1    497     497    21.4 5.5e-06 ***
Residuals 328   7629      23                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb132"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" aria-hidden="true" tabindex="-1"></a><span class="fu">supernova</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> Analysis of Variance Table (Type III SS)
 Model: s_NABS ~ condition

                               SS  df      MS      F    PRE     p
 ----- --------------- | -------- --- ------- ------ ------ -----
 Model (error reduced) |  496.765   1 496.765 21.357 0.0611 .0000
 Error (from model)    | 7629.359 328  23.260                    
 ----- --------------- | -------- --- ------- ------ ------ -----
 Total (empty model)   | 8126.124 329  24.699                    </code></pre>
</div>
</div>
<p>A simple linear regression model predicting cumulative absolute score by condition explains 5% of variance, F(1,328) = 16.36, p &lt; 0.001. The model predicts that subjects in the impasse condition will score on average 2 points higher than those in the control condition (Beta = 2.02, 95% CI [1.04, 3.00])</p>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb134"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>We fitted a linear model (estimated using OLS) to predict s_NABS with condition (formula: s_NABS ~ condition). The model explains a statistically significant and weak proportion of variance (R2 = 0.06, F(1, 328) = 21.36, p &lt; .001, adj. R2 = 0.06). The model's intercept, corresponding to condition = 111, is at 2.47 (95% CI [1.71, 3.22], t(328) = 6.43, p &lt; .001). Within this model:

  - The effect of condition [121] is statistically significant and positive (beta = 2.46, 95% CI [1.41, 3.50], t(328) = 4.62, p &lt; .001; Std. beta = 0.49, 95% CI [0.28, 0.70])

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using the Wald approximation.</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb136"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb136-1"><a href="#cb136-1" aria-hidden="true" tabindex="-1"></a>m.m1 <span class="ot">&lt;-</span> <span class="fu">lmer</span>( score_SCALED <span class="sc">~</span> (<span class="dv">1</span> <span class="sc">+</span> condition<span class="sc">|</span>subject), <span class="at">data =</span> df_items)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Model failed to converge with 1 negative eigenvalue: -8.1e-04</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb138"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb138-1"><a href="#cb138-1" aria-hidden="true" tabindex="-1"></a>m.m1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerModLmerTest']
Formula: score_SCALED ~ (1 + condition | subject)
   Data: df_items
REML criterion at convergence: 9773
Random effects:
 Groups   Name         Std.Dev. Corr 
 subject  (Intercept)  0.632         
          condition121 0.827    -0.71
 Residual              0.591         
Number of obs: 4950, groups:  subject, 330
Fixed Effects:
(Intercept)  
    -0.0617  </code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb140"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb140-1"><a href="#cb140-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m.m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: score_SCALED ~ (1 + condition | subject)
   Data: df_items

REML criterion at convergence: 9773

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.9664 -0.6738 -0.0461  0.5889  2.7646 

Random effects:
 Groups   Name         Variance Std.Dev. Corr 
 subject  (Intercept)  0.400    0.632         
          condition121 0.685    0.827    -0.71
 Residual              0.349    0.591         
Number of obs: 4950, groups:  subject, 330

Fixed effects:
            Estimate Std. Error       df t value Pr(&gt;|t|)  
(Intercept)  -0.0617     0.0344 326.4131   -1.79    0.074 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb142"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb142-1"><a href="#cb142-1" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(m.m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>We fitted a constant (intercept-only) linear mixed model (estimated using REML and nloptwrap optimizer) to predict score_SCALED (formula: score_SCALED ~ 1). The model included condition and subject as random effects (formula: ~1 + condition | subject). . The model's intercept is at -0.06 (95% CI [-0.13, 5.71e-03], t(4945) = -1.79, p = 0.073). Within this model:

  -  ()

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using </code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb144"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb144-1"><a href="#cb144-1" aria-hidden="true" tabindex="-1"></a>m.m2 <span class="ot">&lt;-</span> <span class="fu">lmer</span>( score_SCALED <span class="sc">~</span> (<span class="dv">1</span><span class="sc">+</span> condition<span class="sc">|</span>q), <span class="at">data =</span> df_items)</span>
<span id="cb144-2"><a href="#cb144-2" aria-hidden="true" tabindex="-1"></a>m.m2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerModLmerTest']
Formula: score_SCALED ~ (1 + condition | q)
   Data: df_items
REML criterion at convergence: 11500
Random effects:
 Groups   Name         Std.Dev. Corr 
 q        (Intercept)  0.602         
          condition121 0.530    -0.93
 Residual              0.765         
Number of obs: 4950, groups:  q, 15
Fixed Effects:
(Intercept)  
      0.172  </code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb146"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb146-1"><a href="#cb146-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m.m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: score_SCALED ~ (1 + condition | q)
   Data: df_items

REML criterion at convergence: 11500

Scaled residuals: 
   Min     1Q Median     3Q    Max 
-1.972 -0.794 -0.093  0.887  2.164 

Random effects:
 Groups   Name         Variance Std.Dev. Corr 
 q        (Intercept)  0.363    0.602         
          condition121 0.281    0.530    -0.93
 Residual              0.585    0.765         
Number of obs: 4950, groups:  q, 15

Fixed effects:
            Estimate Std. Error      df t value Pr(&gt;|t|)   
(Intercept)   0.1717     0.0575 14.0014    2.98   0.0099 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb148"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb148-1"><a href="#cb148-1" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(m.m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>We fitted a constant (intercept-only) linear mixed model (estimated using REML and nloptwrap optimizer) to predict score_SCALED (formula: score_SCALED ~ 1). The model included condition and q as random effects (formula: ~1 + condition | q). . The model's intercept is at 0.17 (95% CI [0.06, 0.28], t(4945) = 2.98, p = 0.003). Within this model:

  -  ()

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using </code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb150"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb150-1"><a href="#cb150-1" aria-hidden="true" tabindex="-1"></a>m.m3 <span class="ot">&lt;-</span> <span class="fu">lmer</span>( score_SCALED <span class="sc">~</span> (<span class="dv">1</span><span class="sc">+</span> condition<span class="sc">|</span>q) <span class="sc">+</span> (<span class="dv">1</span><span class="sc">+</span>condition<span class="sc">|</span>subject), <span class="at">data =</span> df_items)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv, :
Model failed to converge with max|grad| = 0.00208782 (tol = 0.002, component 1)</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb152"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb152-1"><a href="#cb152-1" aria-hidden="true" tabindex="-1"></a>m.m3 <span class="sc">%&gt;%</span> <span class="fu">summary</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: score_SCALED ~ (1 + condition | q) + (1 + condition | subject)
   Data: df_items

REML criterion at convergence: 8593

Scaled residuals: 
   Min     1Q Median     3Q    Max 
-3.724 -0.644 -0.016  0.697  3.599 

Random effects:
 Groups   Name         Variance Std.Dev. Corr 
 subject  (Intercept)  0.339    0.583         
          condition121 0.218    0.467    -0.46
 q        (Intercept)  0.268    0.517         
          condition121 0.197    0.443    -0.91
 Residual              0.266    0.516         
Number of obs: 4950, groups:  subject, 330; q, 15

Fixed effects:
            Estimate Std. Error     df t value Pr(&gt;|t|)
(Intercept)    0.117      0.071 24.208    1.65     0.11
optimizer (nloptwrap) convergence code: 0 (OK)
Model failed to converge with max|grad| = 0.00208782 (tol = 0.002, component 1)</code></pre>
</div>
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb154"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb154-1"><a href="#cb154-1" aria-hidden="true" tabindex="-1"></a>m.m3 <span class="sc">%&gt;%</span> <span class="fu">report</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>We fitted a constant (intercept-only) linear mixed model (estimated using REML and nloptwrap optimizer) to predict score_SCALED (formula: score_SCALED ~ 1). The model included condition, q and subject as random effects (formula: list(~1 + condition | q, ~1 + condition | subject)). . The model's intercept is at 0.12 (95% CI [-0.02, 0.26], t(4942) = 1.65, p = 0.098). Within this model:

  -  ()

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using </code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>CODE</summary>
<div class="sourceCode cell-code" id="cb156"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb156-1"><a href="#cb156-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m.m1, m.m2, m.m3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>refitting model(s) with ML (instead of REML)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Data: df_items
Models:
m.m1: score_SCALED ~ (1 + condition | subject)
m.m2: score_SCALED ~ (1 + condition | q)
m.m3: score_SCALED ~ (1 + condition | q) + (1 + condition | subject)
     npar   AIC   BIC logLik deviance Chisq Df Pr(&gt;Chisq)    
m.m1    5  9778  9811  -4884     9768                        
m.m2    5 11506 11539  -5748    11496     0  0               
m.m3    8  8605  8657  -4295     8589  2907  3     &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="resources" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="resources"><span class="header-section-number">4.5</span> Resources</h2>
<ul>
<li>https://rpkgs.datanovia.com/ggpubr/reference/index.html</li>
</ul>


<!-- -->

</section>

</main> <!-- /main -->
<script type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../analysis/SGC3A/3_sgc3A_exploration.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Exploration</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../references.html" class="pagination-link">
        <span class="nav-page-text">References</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb159" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb159-1"><a href="#cb159-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb159-2"><a href="#cb159-2" aria-hidden="true" tabindex="-1"></a><span class="co"># title: 'Exploration'</span></span>
<span id="cb159-3"><a href="#cb159-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> 'Study SGC3A | 4 Modelling'</span></span>
<span id="cb159-4"><a href="#cb159-4" aria-hidden="true" tabindex="-1"></a><span class="co"># author: 'Amy Rae Fox'</span></span>
<span id="cb159-5"><a href="#cb159-5" aria-hidden="true" tabindex="-1"></a><span class="co"># always_allow_html: true  </span></span>
<span id="cb159-6"><a href="#cb159-6" aria-hidden="true" tabindex="-1"></a><span class="co"># header-includes:</span></span>
<span id="cb159-7"><a href="#cb159-7" aria-hidden="true" tabindex="-1"></a><span class="co">#    - \usepackage{amsmath}</span></span>
<span id="cb159-8"><a href="#cb159-8" aria-hidden="true" tabindex="-1"></a><span class="co"># output:</span></span>
<span id="cb159-9"><a href="#cb159-9" aria-hidden="true" tabindex="-1"></a><span class="co">#   html_document:</span></span>
<span id="cb159-10"><a href="#cb159-10" aria-hidden="true" tabindex="-1"></a><span class="co">#     theme: yeti</span></span>
<span id="cb159-11"><a href="#cb159-11" aria-hidden="true" tabindex="-1"></a><span class="co">#     code_folding: hide</span></span>
<span id="cb159-12"><a href="#cb159-12" aria-hidden="true" tabindex="-1"></a><span class="co">#     fig_caption: yes</span></span>
<span id="cb159-13"><a href="#cb159-13" aria-hidden="true" tabindex="-1"></a><span class="co">#     number_sections: yes</span></span>
<span id="cb159-14"><a href="#cb159-14" aria-hidden="true" tabindex="-1"></a><span class="co">#     toc: yes</span></span>
<span id="cb159-15"><a href="#cb159-15" aria-hidden="true" tabindex="-1"></a><span class="co">#     toc_depth: 4</span></span>
<span id="cb159-16"><a href="#cb159-16" aria-hidden="true" tabindex="-1"></a><span class="co">#     toc_float:</span></span>
<span id="cb159-17"><a href="#cb159-17" aria-hidden="true" tabindex="-1"></a><span class="co">#       collapsed: no</span></span>
<span id="cb159-18"><a href="#cb159-18" aria-hidden="true" tabindex="-1"></a><span class="co">#       smooth_scroll: yes</span></span>
<span id="cb159-19"><a href="#cb159-19" aria-hidden="true" tabindex="-1"></a><span class="co">#   pdf_document: </span></span>
<span id="cb159-20"><a href="#cb159-20" aria-hidden="true" tabindex="-1"></a><span class="co">#     toc: true</span></span>
<span id="cb159-21"><a href="#cb159-21" aria-hidden="true" tabindex="-1"></a><span class="co">#     toc_depth: 3</span></span>
<span id="cb159-22"><a href="#cb159-22" aria-hidden="true" tabindex="-1"></a><span class="co">#     latex_engine: xelatex</span></span>
<span id="cb159-23"><a href="#cb159-23" aria-hidden="true" tabindex="-1"></a><span class="co"># font-family: "DejaVu Sans"</span></span>
<span id="cb159-24"><a href="#cb159-24" aria-hidden="true" tabindex="-1"></a><span class="co"># mainfont: "DejaVu Sans"</span></span>
<span id="cb159-25"><a href="#cb159-25" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb159-26"><a href="#cb159-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-27"><a href="#cb159-27" aria-hidden="true" tabindex="-1"></a>\newpage</span>
<span id="cb159-28"><a href="#cb159-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-29"><a href="#cb159-29" aria-hidden="true" tabindex="-1"></a><span class="fu"># Modelling {#sec-SGC3A-modelling}</span></span>
<span id="cb159-30"><a href="#cb159-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-31"><a href="#cb159-31" aria-hidden="true" tabindex="-1"></a>TODO - port modelling from 3_exploration into 4_modelling</span>
<span id="cb159-32"><a href="#cb159-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-35"><a href="#cb159-35" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb159-36"><a href="#cb159-36" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: SETUP</span></span>
<span id="cb159-37"><a href="#cb159-37" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo : true</span></span>
<span id="cb159-38"><a href="#cb159-38" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning : false</span></span>
<span id="cb159-39"><a href="#cb159-39" aria-hidden="true" tabindex="-1"></a><span class="co">#| message : false</span></span>
<span id="cb159-40"><a href="#cb159-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-41"><a href="#cb159-41" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co">#ALL THE THINGS</span></span>
<span id="cb159-42"><a href="#cb159-42" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Hmisc) <span class="co"># %nin% operator</span></span>
<span id="cb159-43"><a href="#cb159-43" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr) <span class="co">#arrange plots</span></span>
<span id="cb159-44"><a href="#cb159-44" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggformula) <span class="co">#easy graphs</span></span>
<span id="cb159-45"><a href="#cb159-45" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(report) <span class="co">#easystats reporting</span></span>
<span id="cb159-46"><a href="#cb159-46" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(see) <span class="co">#easystats visualization</span></span>
<span id="cb159-47"><a href="#cb159-47" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance) <span class="co">#easystats model diagnostics</span></span>
<span id="cb159-48"><a href="#cb159-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-49"><a href="#cb159-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-50"><a href="#cb159-50" aria-hidden="true" tabindex="-1"></a><span class="co">#set some output options</span></span>
<span id="cb159-51"><a href="#cb159-51" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>)</span>
<span id="cb159-52"><a href="#cb159-52" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">dplyr.summarise.inform =</span> <span class="cn">FALSE</span>)</span>
<span id="cb159-53"><a href="#cb159-53" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">ggplot2.summarise.inform =</span> <span class="cn">FALSE</span>)</span>
<span id="cb159-54"><a href="#cb159-54" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen=</span><span class="dv">1</span>, <span class="at">digits=</span><span class="dv">3</span>)</span>
<span id="cb159-55"><a href="#cb159-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-56"><a href="#cb159-56" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb159-57"><a href="#cb159-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-58"><a href="#cb159-58" aria-hidden="true" tabindex="-1"></a>*The purpose of this notebook is explore the distribution of dependent variables for Study SGC3A.*</span>
<span id="cb159-59"><a href="#cb159-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-60"><a href="#cb159-60" aria-hidden="true" tabindex="-1"></a>+-------------------------+---------------+</span>
<span id="cb159-61"><a href="#cb159-61" aria-hidden="true" tabindex="-1"></a>| Pre-Requisite           | Followed By   |</span>
<span id="cb159-62"><a href="#cb159-62" aria-hidden="true" tabindex="-1"></a>+=========================+===============+</span>
<span id="cb159-63"><a href="#cb159-63" aria-hidden="true" tabindex="-1"></a>| 1_sgc3A_harmonize.qmd\  | \|            |</span>
<span id="cb159-64"><a href="#cb159-64" aria-hidden="true" tabindex="-1"></a>| 2_sgc3A_rescoring.qmd\  |               |</span>
<span id="cb159-65"><a href="#cb159-65" aria-hidden="true" tabindex="-1"></a>| 3_sgc3A_exploration.qmd |               |</span>
<span id="cb159-66"><a href="#cb159-66" aria-hidden="true" tabindex="-1"></a>+-------------------------+---------------+</span>
<span id="cb159-67"><a href="#cb159-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-70"><a href="#cb159-70" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb159-71"><a href="#cb159-71" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: IMPORT-DATA</span></span>
<span id="cb159-72"><a href="#cb159-72" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo : true</span></span>
<span id="cb159-73"><a href="#cb159-73" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning : false</span></span>
<span id="cb159-74"><a href="#cb159-74" aria-hidden="true" tabindex="-1"></a><span class="co">#| message : false</span></span>
<span id="cb159-75"><a href="#cb159-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-76"><a href="#cb159-76" aria-hidden="true" tabindex="-1"></a><span class="co">#IMPORT DATA </span></span>
<span id="cb159-77"><a href="#cb159-77" aria-hidden="true" tabindex="-1"></a>df_items <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">'data/2-scored-data/sgc3a_scored_items.rds'</span>)</span>
<span id="cb159-78"><a href="#cb159-78" aria-hidden="true" tabindex="-1"></a>df_subjects <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">'data/2-scored-data/sgc3a_scored_participants.rds'</span>)</span>
<span id="cb159-79"><a href="#cb159-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-80"><a href="#cb159-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-81"><a href="#cb159-81" aria-hidden="true" tabindex="-1"></a><span class="co">#SEPARATE ITEM DATA BY QUESTION TYPE</span></span>
<span id="cb159-82"><a href="#cb159-82" aria-hidden="true" tabindex="-1"></a>df_scaffold <span class="ot">&lt;-</span> df_items <span class="sc">%&gt;%</span> <span class="fu">filter</span>(q <span class="sc">&lt;</span> <span class="dv">6</span>)</span>
<span id="cb159-83"><a href="#cb159-83" aria-hidden="true" tabindex="-1"></a>df_test <span class="ot">&lt;-</span> df_items <span class="sc">%&gt;%</span> <span class="fu">filter</span>(q <span class="sc">&gt;</span> <span class="dv">6</span>) <span class="sc">%&gt;%</span> <span class="fu">filter</span> (q <span class="sc">%nin%</span> <span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">9</span>))</span>
<span id="cb159-84"><a href="#cb159-84" aria-hidden="true" tabindex="-1"></a>df_nondiscrim <span class="ot">&lt;-</span> df_items <span class="sc">%&gt;%</span> <span class="fu">filter</span> (q <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">9</span>))</span>
<span id="cb159-85"><a href="#cb159-85" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb159-86"><a href="#cb159-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-87"><a href="#cb159-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-88"><a href="#cb159-88" aria-hidden="true" tabindex="-1"></a><span class="fu">## Cumulative Performance</span></span>
<span id="cb159-89"><a href="#cb159-89" aria-hidden="true" tabindex="-1"></a>_Overall_ does the impasse condition affect performance on the graph comprehension task? </span>
<span id="cb159-90"><a href="#cb159-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-91"><a href="#cb159-91" aria-hidden="true" tabindex="-1"></a><span class="fu">### Cumulative Score By Condition</span></span>
<span id="cb159-92"><a href="#cb159-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-93"><a href="#cb159-93" aria-hidden="true" tabindex="-1"></a>Cumulative scores indicate the response accuracy by a particular participant across all discriminant items (n=13) in the graph comprehension task.</span>
<span id="cb159-94"><a href="#cb159-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-97"><a href="#cb159-97" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb159-98"><a href="#cb159-98" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: VIS-SUBJECT-ABS</span></span>
<span id="cb159-99"><a href="#cb159-99" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb159-100"><a href="#cb159-100" aria-hidden="true" tabindex="-1"></a><span class="co">#VISUALIZE distribution of response accuracy across SUBJECTS</span></span>
<span id="cb159-101"><a href="#cb159-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-102"><a href="#cb159-102" aria-hidden="true" tabindex="-1"></a><span class="co">#HISTOGRAM</span></span>
<span id="cb159-103"><a href="#cb159-103" aria-hidden="true" tabindex="-1"></a>stats <span class="ot">=</span> df_subjects <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(condition, mode) <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(s_ABS))</span>
<span id="cb159-104"><a href="#cb159-104" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_density</span>(<span class="sc">~</span>s_ABS, <span class="at">data =</span> df_subjects) <span class="sc">%&gt;%</span> </span>
<span id="cb159-105"><a href="#cb159-105" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_facet_grid</span>(condition<span class="sc">~</span>mode, <span class="at">labeller =</span> label_both) <span class="sc">%&gt;%</span> </span>
<span id="cb159-106"><a href="#cb159-106" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_lims</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">13</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb159-107"><a href="#cb159-107" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_vline</span>(<span class="at">data =</span> stats, <span class="at">xintercept =</span> <span class="sc">~</span>mean, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb159-108"><a href="#cb159-108" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Cumulative Absolute Score"</span>,</span>
<span id="cb159-109"><a href="#cb159-109" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"proportion of subjects"</span>,</span>
<span id="cb159-110"><a href="#cb159-110" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Subject Cumulative Score (Absolute)"</span>,</span>
<span id="cb159-111"><a href="#cb159-111" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Score distributions are comparable across modalities and different across conditions"</span>) <span class="sc">+</span> </span>
<span id="cb159-112"><a href="#cb159-112" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb159-113"><a href="#cb159-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-114"><a href="#cb159-114" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb159-115"><a href="#cb159-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-116"><a href="#cb159-116" aria-hidden="true" tabindex="-1"></a>**Does the IMPASSE condition yield higher scores?**</span>
<span id="cb159-117"><a href="#cb159-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-118"><a href="#cb159-118" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Linear Regression</span></span>
<span id="cb159-119"><a href="#cb159-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-120"><a href="#cb159-120" aria-hidden="true" tabindex="-1"></a>To address this question we assess how much variance in cumulative (absolute) score is explained by experimental condition by utilizing OLS linear regression, predicting absolute score from condition.</span>
<span id="cb159-121"><a href="#cb159-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-124"><a href="#cb159-124" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb159-125"><a href="#cb159-125" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: MODEL-cumulative-score-LAB</span></span>
<span id="cb159-126"><a href="#cb159-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-127"><a href="#cb159-127" aria-hidden="true" tabindex="-1"></a><span class="co">#SCORE predicted by CONDITION</span></span>
<span id="cb159-128"><a href="#cb159-128" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(s_ABS <span class="sc">~</span> condition, <span class="at">data =</span> df_subjects <span class="sc">%&gt;%</span> <span class="fu">filter</span>(mode<span class="sc">==</span><span class="st">"lab-synch"</span>))</span>
<span id="cb159-129"><a href="#cb159-129" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Model"</span>)</span>
<span id="cb159-130"><a href="#cb159-130" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span>
<span id="cb159-131"><a href="#cb159-131" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Partition Variance"</span>)</span>
<span id="cb159-132"><a href="#cb159-132" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1)</span>
<span id="cb159-133"><a href="#cb159-133" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Confidence Interval on Parameter Estimates"</span>)</span>
<span id="cb159-134"><a href="#cb159-134" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(m1)</span>
<span id="cb159-135"><a href="#cb159-135" aria-hidden="true" tabindex="-1"></a><span class="co"># report(m1) #sanity check</span></span>
<span id="cb159-136"><a href="#cb159-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-137"><a href="#cb159-137" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb159-138"><a href="#cb159-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-139"><a href="#cb159-139" aria-hidden="true" tabindex="-1"></a>**For in-lab data collection** an OLS linear regression predicting cumulative absolute score by experimental condition explains a statistically significant though small 7.5% variance in score (F(1,124) = 10.1, p <span class="sc">\&lt;</span> 0.01). The estimated beta coefficient ($/beta$ = 2.76, 95% CI <span class="sc">\[</span>1.04, 4.48<span class="sc">\]</span>) predicts that participants in the impasse condition will on average score 2.76 points (21%) higher than those in the control condition.</span>
<span id="cb159-140"><a href="#cb159-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-143"><a href="#cb159-143" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb159-144"><a href="#cb159-144" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: MODEL-cumulative-score-ONLINE</span></span>
<span id="cb159-145"><a href="#cb159-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-146"><a href="#cb159-146" aria-hidden="true" tabindex="-1"></a><span class="co">#SCORE predicted by CONDITION</span></span>
<span id="cb159-147"><a href="#cb159-147" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(s_ABS <span class="sc">~</span> condition, <span class="at">data =</span> df_subjects <span class="sc">%&gt;%</span> <span class="fu">filter</span>(mode<span class="sc">==</span><span class="st">"asynch"</span>))</span>
<span id="cb159-148"><a href="#cb159-148" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Model"</span>)</span>
<span id="cb159-149"><a href="#cb159-149" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span>
<span id="cb159-150"><a href="#cb159-150" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Partition Variance"</span>)</span>
<span id="cb159-151"><a href="#cb159-151" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1)</span>
<span id="cb159-152"><a href="#cb159-152" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Confidence Interval on Parameter Estimates"</span>)</span>
<span id="cb159-153"><a href="#cb159-153" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(m1)</span>
<span id="cb159-154"><a href="#cb159-154" aria-hidden="true" tabindex="-1"></a><span class="co">#report(m1) #sanity check</span></span>
<span id="cb159-155"><a href="#cb159-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-156"><a href="#cb159-156" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb159-157"><a href="#cb159-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-158"><a href="#cb159-158" aria-hidden="true" tabindex="-1"></a>**For the online replication**, an OLS linear regression model predicting cumulative absolute score by condition explains a statistically significant though small 5.5% of variance in absolute score (F(1,202) = 11.73, p <span class="sc">\&lt;</span> 0.001). The beta coefficient for condition indicates that on average, participants in the IMPASSE group scored 2.3 points higher on the task than those in the control condition (CI<span class="sc">\[</span>0.97, 3.59<span class="sc">\]</span>).</span>
<span id="cb159-159"><a href="#cb159-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-160"><a href="#cb159-160" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb159-161"><a href="#cb159-161" aria-hidden="true" tabindex="-1"></a>**From these models we can reasonably conclude that the impasse condition yielded a small but reliable improvement in performance across items in the graph reading task.**</span>
<span id="cb159-162"><a href="#cb159-162" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb159-163"><a href="#cb159-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-164"><a href="#cb159-164" aria-hidden="true" tabindex="-1"></a>**Model Diagnostics**</span>
<span id="cb159-165"><a href="#cb159-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-168"><a href="#cb159-168" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb159-169"><a href="#cb159-169" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: DIAGNOSTICS-ABSCORE-LINEAR</span></span>
<span id="cb159-170"><a href="#cb159-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-171"><a href="#cb159-171" aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(m1)</span>
<span id="cb159-172"><a href="#cb159-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-173"><a href="#cb159-173" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb159-174"><a href="#cb159-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-175"><a href="#cb159-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-176"><a href="#cb159-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-177"><a href="#cb159-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-178"><a href="#cb159-178" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Poisson Regression</span></span>
<span id="cb159-179"><a href="#cb159-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-180"><a href="#cb159-180" aria-hidden="true" tabindex="-1"></a>The outcome variable absolute score is clearly not normal. As it represents the cumulative number of items a participant has answered correctly, we can consider it a type of *count*, (ie. count of the number of questions the participant got correct) and attempt to model it using a General Linear Model with the Poisson distribution (and the default log-link function).</span>
<span id="cb159-181"><a href="#cb159-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-184"><a href="#cb159-184" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb159-185"><a href="#cb159-185" aria-hidden="true" tabindex="-1"></a><span class="co"># library('fitdistrplus')</span></span>
<span id="cb159-186"><a href="#cb159-186" aria-hidden="true" tabindex="-1"></a><span class="co"># plot(fitdist(df_subjects$s_ABS,"pois"))</span></span>
<span id="cb159-187"><a href="#cb159-187" aria-hidden="true" tabindex="-1"></a><span class="co"># plot(fitdist(df_subjects$s_ABS,"norm"))</span></span>
<span id="cb159-188"><a href="#cb159-188" aria-hidden="true" tabindex="-1"></a><span class="co"># plot(fitdist(df_subjects$s_ABS,"beta"))</span></span>
<span id="cb159-189"><a href="#cb159-189" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb159-190"><a href="#cb159-190" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb159-191"><a href="#cb159-191" aria-hidden="true" tabindex="-1"></a><span class="co"># plotdist(df_subjects$s_ABS, histo = TRUE, demp = TRUE)</span></span>
<span id="cb159-192"><a href="#cb159-192" aria-hidden="true" tabindex="-1"></a><span class="co"># descdist(df_subjects$s_ABS, discrete=FALSE, boot=500)</span></span>
<span id="cb159-193"><a href="#cb159-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-194"><a href="#cb159-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-195"><a href="#cb159-195" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb159-196"><a href="#cb159-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-199"><a href="#cb159-199" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb159-200"><a href="#cb159-200" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: MODEL-ABSCORE-POISSON</span></span>
<span id="cb159-201"><a href="#cb159-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-202"><a href="#cb159-202" aria-hidden="true" tabindex="-1"></a><span class="co">#SCORE predicted by CONDITION --&gt; POISSON DISTRIBUTION</span></span>
<span id="cb159-203"><a href="#cb159-203" aria-hidden="true" tabindex="-1"></a>mp1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(s_ABS <span class="sc">~</span> condition, <span class="at">data =</span> df_subjects <span class="sc">%&gt;%</span> <span class="fu">filter</span>(mode<span class="sc">==</span><span class="st">"lab-synch"</span>), <span class="at">family =</span> <span class="st">"poisson"</span>)</span>
<span id="cb159-204"><a href="#cb159-204" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Model"</span>)</span>
<span id="cb159-205"><a href="#cb159-205" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mp1)</span>
<span id="cb159-206"><a href="#cb159-206" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Partition Variance"</span>)</span>
<span id="cb159-207"><a href="#cb159-207" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mp1)</span>
<span id="cb159-208"><a href="#cb159-208" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Confidence Interval on Parameter Estimates"</span>)</span>
<span id="cb159-209"><a href="#cb159-209" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mp1)</span>
<span id="cb159-210"><a href="#cb159-210" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(mp1) <span class="co">#sanity check</span></span>
<span id="cb159-211"><a href="#cb159-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-212"><a href="#cb159-212" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb159-213"><a href="#cb159-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-216"><a href="#cb159-216" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb159-217"><a href="#cb159-217" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: DIAGNOSTICS-ABSCORE-POISSON</span></span>
<span id="cb159-218"><a href="#cb159-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-219"><a href="#cb159-219" aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(mp1)</span>
<span id="cb159-220"><a href="#cb159-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-221"><a href="#cb159-221" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb159-222"><a href="#cb159-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-225"><a href="#cb159-225" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb159-226"><a href="#cb159-226" aria-hidden="true" tabindex="-1"></a><span class="co">#Which is a better fit? linear or poisson?</span></span>
<span id="cb159-227"><a href="#cb159-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-228"><a href="#cb159-228" aria-hidden="true" tabindex="-1"></a><span class="fu">compare_performance</span>(m1,mp1)</span>
<span id="cb159-229"><a href="#cb159-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-230"><a href="#cb159-230" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb159-231"><a href="#cb159-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-232"><a href="#cb159-232" aria-hidden="true" tabindex="-1"></a><span class="fu">#### COPIED FROM 3</span></span>
<span id="cb159-233"><a href="#cb159-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-234"><a href="#cb159-234" aria-hidden="true" tabindex="-1"></a>**Does the IMPASSE condition more accurate interpretation?**</span>
<span id="cb159-235"><a href="#cb159-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-236"><a href="#cb159-236" aria-hidden="true" tabindex="-1"></a>To address this question we assess how much variance in cumulative (absolute) score is explained by experimental condition.</span>
<span id="cb159-237"><a href="#cb159-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-240"><a href="#cb159-240" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb159-241"><a href="#cb159-241" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: MODEL-scaled-score-LAB</span></span>
<span id="cb159-242"><a href="#cb159-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-243"><a href="#cb159-243" aria-hidden="true" tabindex="-1"></a><span class="co">#SCORE predicted by CONDITION</span></span>
<span id="cb159-244"><a href="#cb159-244" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(s_SCALED <span class="sc">~</span> condition, <span class="at">data =</span> df_subjects <span class="sc">%&gt;%</span> <span class="fu">filter</span>(mode<span class="sc">==</span><span class="st">"lab-synch"</span>))</span>
<span id="cb159-245"><a href="#cb159-245" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Model"</span>)</span>
<span id="cb159-246"><a href="#cb159-246" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span>
<span id="cb159-247"><a href="#cb159-247" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Partition Variance"</span>)</span>
<span id="cb159-248"><a href="#cb159-248" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1)</span>
<span id="cb159-249"><a href="#cb159-249" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Confidence Interval on Parameter Estimates"</span>)</span>
<span id="cb159-250"><a href="#cb159-250" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(m1)</span>
<span id="cb159-251"><a href="#cb159-251" aria-hidden="true" tabindex="-1"></a><span class="co"># report(m1) #sanity check</span></span>
<span id="cb159-252"><a href="#cb159-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-253"><a href="#cb159-253" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb159-254"><a href="#cb159-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-255"><a href="#cb159-255" aria-hidden="true" tabindex="-1"></a>**For in-lab data collection** an OLS linear regression predicting scaled score by experimental condition explains a statistically significant and moderate 15% variance in score (F(1,124) = 22.7, p <span class="sc">\&lt;</span> 0.001). The estimated beta coefficient ($/beta$ = 7.88, 95% CI <span class="sc">\[</span>4.61, 11.2<span class="sc">\]</span>) predicts that participants in the impasse condition will on average score around 8 points (31%) higher than those in the control condition.</span>
<span id="cb159-256"><a href="#cb159-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-259"><a href="#cb159-259" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb159-260"><a href="#cb159-260" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: MODEL-scaled-score-ONLINE</span></span>
<span id="cb159-261"><a href="#cb159-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-262"><a href="#cb159-262" aria-hidden="true" tabindex="-1"></a><span class="co">#SCORE predicted by CONDITION</span></span>
<span id="cb159-263"><a href="#cb159-263" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(s_SCALED <span class="sc">~</span> condition, <span class="at">data =</span> df_subjects <span class="sc">%&gt;%</span> <span class="fu">filter</span>(mode<span class="sc">==</span><span class="st">"asynch"</span>))</span>
<span id="cb159-264"><a href="#cb159-264" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Model"</span>)</span>
<span id="cb159-265"><a href="#cb159-265" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span>
<span id="cb159-266"><a href="#cb159-266" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Partition Variance"</span>)</span>
<span id="cb159-267"><a href="#cb159-267" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1)</span>
<span id="cb159-268"><a href="#cb159-268" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Confidence Interval on Parameter Estimates"</span>)</span>
<span id="cb159-269"><a href="#cb159-269" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(m1)</span>
<span id="cb159-270"><a href="#cb159-270" aria-hidden="true" tabindex="-1"></a><span class="co">#report(m1) #sanity check</span></span>
<span id="cb159-271"><a href="#cb159-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-272"><a href="#cb159-272" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb159-273"><a href="#cb159-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-274"><a href="#cb159-274" aria-hidden="true" tabindex="-1"></a>**For the online replication**, an OLS linear regression model predicting scaled score by condition explains a statistically significant and moderate 14% of variance in absolute score (F(1,202) = 32.4, p <span class="sc">\&lt;</span> 0.001). The beta coefficient for condition indicates that on average, participants in the IMPASSE group scored 6.8 points higher on the task than those in the control condition (CI<span class="sc">\[</span>4.43, 9.12<span class="sc">\]</span>).</span>
<span id="cb159-275"><a href="#cb159-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-276"><a href="#cb159-276" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb159-277"><a href="#cb159-277" aria-hidden="true" tabindex="-1"></a>**From these models we can reasonably conclude that the impasse condition yields a reliable, moderate sized effect of improved interpretation on the graph reading tasks.**</span>
<span id="cb159-278"><a href="#cb159-278" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb159-279"><a href="#cb159-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-280"><a href="#cb159-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-281"><a href="#cb159-281" aria-hidden="true" tabindex="-1"></a><span class="fu">## First Question</span></span>
<span id="cb159-282"><a href="#cb159-282" aria-hidden="true" tabindex="-1"></a>Does the impasse condition affect performance _on the first item_ of the graph comprehension task? </span>
<span id="cb159-283"><a href="#cb159-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-284"><a href="#cb159-284" aria-hidden="true" tabindex="-1"></a><span class="fu">## Item-Level Performance</span></span>
<span id="cb159-285"><a href="#cb159-285" aria-hidden="true" tabindex="-1"></a>Individual differences with a mixed model. </span>
<span id="cb159-286"><a href="#cb159-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-287"><a href="#cb159-287" aria-hidden="true" tabindex="-1"></a><span class="fu">## Model Peeking</span></span>
<span id="cb159-288"><a href="#cb159-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-289"><a href="#cb159-289" aria-hidden="true" tabindex="-1"></a>TODO</span>
<span id="cb159-290"><a href="#cb159-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-291"><a href="#cb159-291" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>multiple regression with condition and response time</span>
<span id="cb159-292"><a href="#cb159-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-295"><a href="#cb159-295" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb159-296"><a href="#cb159-296" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(supernova)</span>
<span id="cb159-297"><a href="#cb159-297" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(report)</span>
<span id="cb159-298"><a href="#cb159-298" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmerTest)</span>
<span id="cb159-299"><a href="#cb159-299" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb159-300"><a href="#cb159-300" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>( s_SCALED <span class="sc">~</span> condition, <span class="at">data =</span> df_subjects <span class="sc">%&gt;%</span> <span class="fu">filter</span>(mode<span class="sc">==</span><span class="st">'asynch'</span>))</span>
<span id="cb159-301"><a href="#cb159-301" aria-hidden="true" tabindex="-1"></a>m1</span>
<span id="cb159-302"><a href="#cb159-302" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span>
<span id="cb159-303"><a href="#cb159-303" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1)</span>
<span id="cb159-304"><a href="#cb159-304" aria-hidden="true" tabindex="-1"></a><span class="fu">superanova</span>(m1)</span>
<span id="cb159-305"><a href="#cb159-305" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m1)</span>
<span id="cb159-306"><a href="#cb159-306" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_histogram</span>(<span class="sc">~</span>s_SCALED, <span class="at">data =</span> df_subjects)</span>
<span id="cb159-307"><a href="#cb159-307" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_histogram</span>(<span class="sc">~</span>m1<span class="sc">$</span>residuals)</span>
<span id="cb159-308"><a href="#cb159-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-309"><a href="#cb159-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-310"><a href="#cb159-310" aria-hidden="true" tabindex="-1"></a><span class="co">#Assess assumption of independence of errors</span></span>
<span id="cb159-311"><a href="#cb159-311" aria-hidden="true" tabindex="-1"></a><span class="co">#DW statistic should be close to 2</span></span>
<span id="cb159-312"><a href="#cb159-312" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb159-313"><a href="#cb159-313" aria-hidden="true" tabindex="-1"></a><span class="fu">durbinWatsonTest</span>(m1)</span>
<span id="cb159-314"><a href="#cb159-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-315"><a href="#cb159-315" aria-hidden="true" tabindex="-1"></a><span class="co">#Test for equality of variance</span></span>
<span id="cb159-316"><a href="#cb159-316" aria-hidden="true" tabindex="-1"></a><span class="co">#H0 is equality; p &gt; 0.05 infer you can't reject null</span></span>
<span id="cb159-317"><a href="#cb159-317" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(m1)</span>
<span id="cb159-318"><a href="#cb159-318" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb159-319"><a href="#cb159-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-320"><a href="#cb159-320" aria-hidden="true" tabindex="-1"></a>A simple linear regression model predicting cumulative scaled score (at subject level) by condition explains 13% of the total variance, F(1,329) = 47.8, p <span class="sc">\&lt;</span> 0.001. The model predicts that participants in the impasse condition will score on average 6.38 points higher than those in the control condition, 95% CI <span class="sc">\[</span>4.56, 8.19<span class="sc">\]</span>.</span>
<span id="cb159-321"><a href="#cb159-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-324"><a href="#cb159-324" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb159-325"><a href="#cb159-325" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(s_SCALED <span class="sc">~</span> condition, <span class="at">data =</span> df_subjects)</span>
<span id="cb159-326"><a href="#cb159-326" aria-hidden="true" tabindex="-1"></a><span class="co">#%&gt;% report()</span></span>
<span id="cb159-327"><a href="#cb159-327" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb159-328"><a href="#cb159-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-331"><a href="#cb159-331" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb159-332"><a href="#cb159-332" aria-hidden="true" tabindex="-1"></a><span class="co"># report_participants(df_subjects)</span></span>
<span id="cb159-333"><a href="#cb159-333" aria-hidden="true" tabindex="-1"></a>m1 <span class="sc">%&gt;%</span> <span class="fu">report</span>()</span>
<span id="cb159-334"><a href="#cb159-334" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1) <span class="sc">%&gt;%</span> <span class="fu">report</span>()</span>
<span id="cb159-335"><a href="#cb159-335" aria-hidden="true" tabindex="-1"></a><span class="co">#significant intercept means that group is significantly different than zero</span></span>
<span id="cb159-336"><a href="#cb159-336" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb159-337"><a href="#cb159-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-340"><a href="#cb159-340" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb159-341"><a href="#cb159-341" aria-hidden="true" tabindex="-1"></a><span class="co">#logistic regression on on scaled df_subjects because residuals not normal in lm?</span></span>
<span id="cb159-342"><a href="#cb159-342" aria-hidden="true" tabindex="-1"></a>mlog <span class="ot">&lt;-</span> <span class="fu">glm</span>(s_SCALED <span class="sc">~</span> condition , <span class="at">data =</span> df_subjects, <span class="at">family =</span> gaussian)</span>
<span id="cb159-343"><a href="#cb159-343" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mlog)</span>
<span id="cb159-344"><a href="#cb159-344" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(mlog)</span>
<span id="cb159-345"><a href="#cb159-345" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb159-346"><a href="#cb159-346" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-349"><a href="#cb159-349" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb159-350"><a href="#cb159-350" aria-hidden="true" tabindex="-1"></a><span class="co">#logistic regression on niceABS by condition</span></span>
<span id="cb159-351"><a href="#cb159-351" aria-hidden="true" tabindex="-1"></a><span class="co">#pretends that questions are independent and not from same subjects INVALID</span></span>
<span id="cb159-352"><a href="#cb159-352" aria-hidden="true" tabindex="-1"></a>mlog <span class="ot">&lt;-</span> <span class="fu">glm</span>(score_niceABS <span class="sc">~</span> condition , <span class="at">data =</span> df_items <span class="sc">%&gt;%</span> <span class="fu">filter</span>(q<span class="sc">&lt;</span><span class="dv">6</span>), <span class="at">family =</span> <span class="fu">binomial</span>())</span>
<span id="cb159-353"><a href="#cb159-353" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mlog)</span>
<span id="cb159-354"><a href="#cb159-354" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(mlog)</span>
<span id="cb159-355"><a href="#cb159-355" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb159-356"><a href="#cb159-356" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-359"><a href="#cb159-359" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb159-360"><a href="#cb159-360" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>( s_NABS <span class="sc">~</span> condition, <span class="at">data =</span> df_subjects)</span>
<span id="cb159-361"><a href="#cb159-361" aria-hidden="true" tabindex="-1"></a>m2</span>
<span id="cb159-362"><a href="#cb159-362" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span>
<span id="cb159-363"><a href="#cb159-363" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m2)</span>
<span id="cb159-364"><a href="#cb159-364" aria-hidden="true" tabindex="-1"></a><span class="fu">supernova</span>(m2)</span>
<span id="cb159-365"><a href="#cb159-365" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-366"><a href="#cb159-366" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb159-367"><a href="#cb159-367" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-368"><a href="#cb159-368" aria-hidden="true" tabindex="-1"></a>A simple linear regression model predicting cumulative absolute score by condition explains 5% of variance, F(1,328) = 16.36, p <span class="sc">\&lt;</span> 0.001. The model predicts that subjects in the impasse condition will score on average 2 points higher than those in the control condition (Beta = 2.02, 95% CI <span class="sc">\[</span>1.04, 3.00<span class="sc">\]</span>)</span>
<span id="cb159-369"><a href="#cb159-369" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-372"><a href="#cb159-372" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb159-373"><a href="#cb159-373" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(m2)</span>
<span id="cb159-374"><a href="#cb159-374" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb159-375"><a href="#cb159-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-378"><a href="#cb159-378" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb159-379"><a href="#cb159-379" aria-hidden="true" tabindex="-1"></a>m.m1 <span class="ot">&lt;-</span> <span class="fu">lmer</span>( score_SCALED <span class="sc">~</span> (<span class="dv">1</span> <span class="sc">+</span> condition<span class="sc">|</span>subject), <span class="at">data =</span> df_items)</span>
<span id="cb159-380"><a href="#cb159-380" aria-hidden="true" tabindex="-1"></a>m.m1</span>
<span id="cb159-381"><a href="#cb159-381" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m.m1)</span>
<span id="cb159-382"><a href="#cb159-382" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(m.m1)</span>
<span id="cb159-383"><a href="#cb159-383" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb159-384"><a href="#cb159-384" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-387"><a href="#cb159-387" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb159-388"><a href="#cb159-388" aria-hidden="true" tabindex="-1"></a>m.m2 <span class="ot">&lt;-</span> <span class="fu">lmer</span>( score_SCALED <span class="sc">~</span> (<span class="dv">1</span><span class="sc">+</span> condition<span class="sc">|</span>q), <span class="at">data =</span> df_items)</span>
<span id="cb159-389"><a href="#cb159-389" aria-hidden="true" tabindex="-1"></a>m.m2</span>
<span id="cb159-390"><a href="#cb159-390" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m.m2)</span>
<span id="cb159-391"><a href="#cb159-391" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(m.m2)</span>
<span id="cb159-392"><a href="#cb159-392" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb159-393"><a href="#cb159-393" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-396"><a href="#cb159-396" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb159-397"><a href="#cb159-397" aria-hidden="true" tabindex="-1"></a>m.m3 <span class="ot">&lt;-</span> <span class="fu">lmer</span>( score_SCALED <span class="sc">~</span> (<span class="dv">1</span><span class="sc">+</span> condition<span class="sc">|</span>q) <span class="sc">+</span> (<span class="dv">1</span><span class="sc">+</span>condition<span class="sc">|</span>subject), <span class="at">data =</span> df_items)</span>
<span id="cb159-398"><a href="#cb159-398" aria-hidden="true" tabindex="-1"></a>m.m3 <span class="sc">%&gt;%</span> <span class="fu">summary</span>() </span>
<span id="cb159-399"><a href="#cb159-399" aria-hidden="true" tabindex="-1"></a>m.m3 <span class="sc">%&gt;%</span> <span class="fu">report</span>()</span>
<span id="cb159-400"><a href="#cb159-400" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb159-401"><a href="#cb159-401" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-404"><a href="#cb159-404" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb159-405"><a href="#cb159-405" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m.m1, m.m2, m.m3)</span>
<span id="cb159-406"><a href="#cb159-406" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb159-407"><a href="#cb159-407" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-408"><a href="#cb159-408" aria-hidden="true" tabindex="-1"></a><span class="fu">## Resources</span></span>
<span id="cb159-409"><a href="#cb159-409" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-410"><a href="#cb159-410" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>https://rpkgs.datanovia.com/ggpubr/reference/index.html</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>